/- This file is generated by table-generators/makeTablesForLookup. -/
module

public import UnicodeBasicCommon.Types.LineBreak

@[expose] public section

namespace Unicode.TableLookupTables.LineBreak.Chunk0

@[inline_if_reduce, reducible]
def getInsideSparseRangeValueTable (v : UInt32) : Option LineBreak :=
  if v < 0x0982 then
    if v < 0x0483 then
      if v < 0x00B9 then
        if v < 0x005F then
          if v < 0x002A then
            if v < 0x0022 then
              if v < 0x000D then
                if v < 0x000A then
                  if v < 0x0009 then
                    if 0x0000 ≤ v ∧ v ≤ 0x0008 then some (LineBreak.combiningMark) else none
                  else if 0x0009 < v then
                    none
                  else some (LineBreak.breakAfter)
                else if 0x000A < v then
                  if 0x000B ≤ v ∧ v ≤ 0x000C then some (LineBreak.mandatoryBreak) else none
                else some (LineBreak.lineFeed)
              else if 0x000D < v then
                if v < 0x0020 then
                  if 0x000E ≤ v ∧ v ≤ 0x001F then some (LineBreak.combiningMark) else none
                else if 0x0020 < v then
                  if v == 0x0021 then some (LineBreak.exclamation) else none
                else some (LineBreak.space)
              else some (LineBreak.carriageReturn)
            else if 0x0022 < v then
              if v < 0x0026 then
                if v < 0x0024 then
                  if v == 0x0023 then some (LineBreak.alphabetic) else none
                else if 0x0024 < v then
                  if v == 0x0025 then some (LineBreak.postfixNumeric) else none
                else some (LineBreak.prefixNumeric)
              else if 0x0026 < v then
                if v < 0x0028 then
                  if v == 0x0027 then some (LineBreak.quotation) else none
                else if 0x0028 < v then
                  if v == 0x0029 then some (LineBreak.closeParenthesis) else none
                else some (LineBreak.openPunctuation)
              else some (LineBreak.alphabetic)
            else some (LineBreak.quotation)
          else if 0x002A < v then
            if v < 0x003C then
              if v < 0x002E then
                if v < 0x002C then
                  if v == 0x002B then some (LineBreak.prefixNumeric) else none
                else if 0x002C < v then
                  if v == 0x002D then some (LineBreak.hyphen) else none
                else some (LineBreak.infixNumeric)
              else if 0x002E < v then
                if v < 0x0030 then
                  if v == 0x002F then some (LineBreak.breakSymbols) else none
                else if 0x0039 < v then
                  if 0x003A ≤ v ∧ v ≤ 0x003B then some (LineBreak.infixNumeric) else none
                else some (LineBreak.numeric)
              else some (LineBreak.infixNumeric)
            else if 0x003E < v then
              if v < 0x005B then
                if v < 0x0040 then
                  if v == 0x003F then some (LineBreak.exclamation) else none
                else if 0x0040 < v then
                  if 0x0041 ≤ v ∧ v ≤ 0x005A then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x005B < v then
                if v < 0x005D then
                  if v == 0x005C then some (LineBreak.prefixNumeric) else none
                else if 0x005D < v then
                  if v == 0x005E then some (LineBreak.alphabetic) else none
                else some (LineBreak.closeParenthesis)
              else some (LineBreak.openPunctuation)
            else some (LineBreak.alphabetic)
          else some (LineBreak.alphabetic)
        else if 0x005F < v then
          if v < 0x00A7 then
            if v < 0x0080 then
              if v < 0x007C then
                if v < 0x0061 then
                  if v == 0x0060 then some (LineBreak.alphabetic) else none
                else if 0x007A < v then
                  if v == 0x007B then some (LineBreak.openPunctuation) else none
                else some (LineBreak.alphabetic)
              else if 0x007C < v then
                if v < 0x007E then
                  if v == 0x007D then some (LineBreak.closePunctuation) else none
                else if 0x007E < v then
                  if v == 0x007F then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.breakAfter)
            else if 0x0084 < v then
              if v < 0x00A1 then
                if v < 0x0086 then
                  if v == 0x0085 then some (LineBreak.nextLine) else none
                else if 0x009F < v then
                  if v == 0x00A0 then some (LineBreak.glue) else none
                else some (LineBreak.combiningMark)
              else if 0x00A1 < v then
                if v < 0x00A3 then
                  if v == 0x00A2 then some (LineBreak.postfixNumeric) else none
                else if 0x00A5 < v then
                  if v == 0x00A6 then some (LineBreak.alphabetic) else none
                else some (LineBreak.prefixNumeric)
              else some (LineBreak.openPunctuation)
            else some (LineBreak.combiningMark)
          else if 0x00A7 < v then
            if v < 0x00AF then
              if v < 0x00AB then
                if v < 0x00A9 then
                  if v == 0x00A8 then some (LineBreak.ambiguous) else none
                else if 0x00A9 < v then
                  if v == 0x00AA then some (LineBreak.ambiguous) else none
                else some (LineBreak.alphabetic)
              else if 0x00AB < v then
                if v < 0x00AD then
                  if v == 0x00AC then some (LineBreak.alphabetic) else none
                else if 0x00AD < v then
                  if v == 0x00AE then some (LineBreak.alphabetic) else none
                else some (LineBreak.breakAfter)
              else some (LineBreak.quotation)
            else if 0x00AF < v then
              if v < 0x00B4 then
                if v < 0x00B1 then
                  if v == 0x00B0 then some (LineBreak.postfixNumeric) else none
                else if 0x00B1 < v then
                  if 0x00B2 ≤ v ∧ v ≤ 0x00B3 then some (LineBreak.ambiguous) else none
                else some (LineBreak.prefixNumeric)
              else if 0x00B4 < v then
                if v < 0x00B6 then
                  if v == 0x00B5 then some (LineBreak.alphabetic) else none
                else if 0x00B7 < v then
                  if v == 0x00B8 then some (LineBreak.ambiguous) else none
                else some (LineBreak.ambiguous)
              else some (LineBreak.breakBefore)
            else some (LineBreak.alphabetic)
          else some (LineBreak.ambiguous)
        else some (LineBreak.alphabetic)
      else if 0x00B9 < v then
        if v < 0x02DC then
          if v < 0x0250 then
            if v < 0x00F7 then
              if v < 0x00BF then
                if v < 0x00BB then
                  if v == 0x00BA then some (LineBreak.ambiguous) else none
                else if 0x00BB < v then
                  if 0x00BC ≤ v ∧ v ≤ 0x00BE then some (LineBreak.ambiguous) else none
                else some (LineBreak.quotation)
              else if 0x00BF < v then
                if v < 0x00D7 then
                  if 0x00C0 ≤ v ∧ v ≤ 0x00D6 then some (LineBreak.alphabetic) else none
                else if 0x00D7 < v then
                  if 0x00D8 ≤ v ∧ v ≤ 0x00F6 then some (LineBreak.alphabetic) else none
                else some (LineBreak.ambiguous)
              else some (LineBreak.openPunctuation)
            else if 0x00F7 < v then
              if v < 0x01BB then
                if v < 0x0100 then
                  if 0x00F8 ≤ v ∧ v ≤ 0x00FF then some (LineBreak.alphabetic) else none
                else if 0x017F < v then
                  if 0x0180 ≤ v ∧ v ≤ 0x01BA then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x01BB < v then
                if v < 0x01C0 then
                  if 0x01BC ≤ v ∧ v ≤ 0x01BF then some (LineBreak.alphabetic) else none
                else if 0x01C3 < v then
                  if 0x01C4 ≤ v ∧ v ≤ 0x024F then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else some (LineBreak.ambiguous)
          else if 0x0293 < v then
            if v < 0x02C9 then
              if v < 0x02C2 then
                if v < 0x0296 then
                  if 0x0294 ≤ v ∧ v ≤ 0x0295 then some (LineBreak.alphabetic) else none
                else if 0x02AF < v then
                  if 0x02B0 ≤ v ∧ v ≤ 0x02C1 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x02C5 < v then
                if v < 0x02C7 then
                  if v == 0x02C6 then some (LineBreak.alphabetic) else none
                else if 0x02C7 < v then
                  if v == 0x02C8 then some (LineBreak.breakBefore) else none
                else some (LineBreak.ambiguous)
              else some (LineBreak.alphabetic)
            else if 0x02CB < v then
              if v < 0x02D0 then
                if v < 0x02CD then
                  if v == 0x02CC then some (LineBreak.breakBefore) else none
                else if 0x02CD < v then
                  if 0x02CE ≤ v ∧ v ≤ 0x02CF then some (LineBreak.alphabetic) else none
                else some (LineBreak.ambiguous)
              else if 0x02D0 < v then
                if v < 0x02D2 then
                  if v == 0x02D1 then some (LineBreak.alphabetic) else none
                else if 0x02D7 < v then
                  if 0x02D8 ≤ v ∧ v ≤ 0x02DB then some (LineBreak.ambiguous) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.ambiguous)
            else some (LineBreak.ambiguous)
          else some (LineBreak.alphabetic)
        else if 0x02DC < v then
          if v < 0x0376 then
            if v < 0x02EE then
              if v < 0x02E0 then
                if v < 0x02DE then
                  if v == 0x02DD then some (LineBreak.ambiguous) else none
                else if 0x02DE < v then
                  if v == 0x02DF then some (LineBreak.breakBefore) else none
                else some (LineBreak.alphabetic)
              else if 0x02E4 < v then
                if v < 0x02EC then
                  if 0x02E5 ≤ v ∧ v ≤ 0x02EB then some (LineBreak.alphabetic) else none
                else if 0x02EC < v then
                  if v == 0x02ED then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else if 0x02EE < v then
              if v < 0x0363 then
                if v < 0x0300 then
                  if 0x02EF ≤ v ∧ v ≤ 0x02FF then some (LineBreak.alphabetic) else none
                else if 0x035B < v then
                  if 0x035C ≤ v ∧ v ≤ 0x0362 then some (LineBreak.glue) else none
                else some (LineBreak.combiningMark)
              else if 0x036F < v then
                if v < 0x0374 then
                  if 0x0370 ≤ v ∧ v ≤ 0x0373 then some (LineBreak.alphabetic) else none
                else if 0x0374 < v then
                  if v == 0x0375 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else some (LineBreak.alphabetic)
          else if 0x0377 < v then
            if v < 0x0388 then
              if v < 0x037F then
                if v < 0x037B then
                  if v == 0x037A then some (LineBreak.alphabetic) else none
                else if 0x037D < v then
                  if v == 0x037E then some (LineBreak.infixNumeric) else none
                else some (LineBreak.alphabetic)
              else if 0x037F < v then
                if v < 0x0386 then
                  if 0x0384 ≤ v ∧ v ≤ 0x0385 then some (LineBreak.alphabetic) else none
                else if 0x0386 < v then
                  if v == 0x0387 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else if 0x038A < v then
              if v < 0x03F6 then
                if v < 0x038E then
                  if v == 0x038C then some (LineBreak.alphabetic) else none
                else if 0x03A1 < v then
                  if 0x03A3 ≤ v ∧ v ≤ 0x03F5 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x03F6 < v then
                if v < 0x0400 then
                  if 0x03F7 ≤ v ∧ v ≤ 0x03FF then some (LineBreak.alphabetic) else none
                else if 0x0481 < v then
                  if v == 0x0482 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else some (LineBreak.alphabetic)
          else some (LineBreak.alphabetic)
        else some (LineBreak.alphabetic)
      else some (LineBreak.ambiguous)
    else if 0x0487 < v then
      if v < 0x0712 then
        if v < 0x061C then
          if v < 0x05C1 then
            if v < 0x0589 then
              if v < 0x0531 then
                if v < 0x048A then
                  if 0x0488 ≤ v ∧ v ≤ 0x0489 then some (LineBreak.combiningMark) else none
                else if 0x04FF < v then
                  if 0x0500 ≤ v ∧ v ≤ 0x052F then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x0556 < v then
                if v < 0x055A then
                  if v == 0x0559 then some (LineBreak.alphabetic) else none
                else if 0x055F < v then
                  if 0x0560 ≤ v ∧ v ≤ 0x0588 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else if 0x0589 < v then
              if v < 0x0591 then
                if v < 0x058D then
                  if v == 0x058A then some (LineBreak.unambiguousHyphen) else none
                else if 0x058E < v then
                  if v == 0x058F then some (LineBreak.prefixNumeric) else none
                else some (LineBreak.alphabetic)
              else if 0x05BD < v then
                if v < 0x05BF then
                  if v == 0x05BE then some (LineBreak.unambiguousHyphen) else none
                else if 0x05BF < v then
                  if v == 0x05C0 then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else some (LineBreak.infixNumeric)
          else if 0x05C2 < v then
            if v < 0x0600 then
              if v < 0x05C7 then
                if v < 0x05C4 then
                  if v == 0x05C3 then some (LineBreak.alphabetic) else none
                else if 0x05C5 < v then
                  if v == 0x05C6 then some (LineBreak.exclamation) else none
                else some (LineBreak.combiningMark)
              else if 0x05C7 < v then
                if v < 0x05EF then
                  if 0x05D0 ≤ v ∧ v ≤ 0x05EA then some (LineBreak.hebrewLetter) else none
                else if 0x05F2 < v then
                  if 0x05F3 ≤ v ∧ v ≤ 0x05F4 then some (LineBreak.alphabetic) else none
                else some (LineBreak.hebrewLetter)
              else some (LineBreak.combiningMark)
            else if 0x0605 < v then
              if v < 0x060C then
                if v < 0x0609 then
                  if 0x0606 ≤ v ∧ v ≤ 0x0608 then some (LineBreak.alphabetic) else none
                else if 0x060A < v then
                  if v == 0x060B then some (LineBreak.postfixNumeric) else none
                else some (LineBreak.postfixNumeric)
              else if 0x060D < v then
                if v < 0x0610 then
                  if 0x060E ≤ v ∧ v ≤ 0x060F then some (LineBreak.alphabetic) else none
                else if 0x061A < v then
                  if v == 0x061B then some (LineBreak.exclamation) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.infixNumeric)
            else some (LineBreak.numeric)
          else some (LineBreak.combiningMark)
        else if 0x061C < v then
          if v < 0x06DD then
            if v < 0x066B then
              if v < 0x0641 then
                if v < 0x0620 then
                  if 0x061D ≤ v ∧ v ≤ 0x061F then some (LineBreak.exclamation) else none
                else if 0x063F < v then
                  if v == 0x0640 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x064A < v then
                if v < 0x0660 then
                  if 0x064B ≤ v ∧ v ≤ 0x065F then some (LineBreak.combiningMark) else none
                else if 0x0669 < v then
                  if v == 0x066A then some (LineBreak.postfixNumeric) else none
                else some (LineBreak.numeric)
              else some (LineBreak.alphabetic)
            else if 0x066C < v then
              if v < 0x0671 then
                if v < 0x066E then
                  if v == 0x066D then some (LineBreak.alphabetic) else none
                else if 0x066F < v then
                  if v == 0x0670 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x06D3 < v then
                if v < 0x06D5 then
                  if v == 0x06D4 then some (LineBreak.exclamation) else none
                else if 0x06D5 < v then
                  if 0x06D6 ≤ v ∧ v ≤ 0x06DC then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else some (LineBreak.numeric)
          else if 0x06DD < v then
            if v < 0x06F0 then
              if v < 0x06E7 then
                if v < 0x06DF then
                  if v == 0x06DE then some (LineBreak.alphabetic) else none
                else if 0x06E4 < v then
                  if 0x06E5 ≤ v ∧ v ≤ 0x06E6 then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else if 0x06E8 < v then
                if v < 0x06EA then
                  if v == 0x06E9 then some (LineBreak.alphabetic) else none
                else if 0x06ED < v then
                  if 0x06EE ≤ v ∧ v ≤ 0x06EF then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else if 0x06F9 < v then
              if v < 0x0700 then
                if v < 0x06FD then
                  if 0x06FA ≤ v ∧ v ≤ 0x06FC then some (LineBreak.alphabetic) else none
                else if 0x06FE < v then
                  if v == 0x06FF then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x070D < v then
                if v < 0x0710 then
                  if v == 0x070F then some (LineBreak.alphabetic) else none
                else if 0x0710 < v then
                  if v == 0x0711 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else some (LineBreak.numeric)
          else some (LineBreak.numeric)
        else some (LineBreak.combiningMark)
      else if 0x072F < v then
        if v < 0x0888 then
          if v < 0x07FD then
            if v < 0x07CA then
              if v < 0x0780 then
                if v < 0x074D then
                  if 0x0730 ≤ v ∧ v ≤ 0x074A then some (LineBreak.combiningMark) else none
                else if 0x074F < v then
                  if 0x0750 ≤ v ∧ v ≤ 0x077F then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x07A5 < v then
                if v < 0x07B1 then
                  if 0x07A6 ≤ v ∧ v ≤ 0x07B0 then some (LineBreak.combiningMark) else none
                else if 0x07B1 < v then
                  if 0x07C0 ≤ v ∧ v ≤ 0x07C9 then some (LineBreak.numeric) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else if 0x07EA < v then
              if v < 0x07F7 then
                if v < 0x07F4 then
                  if 0x07EB ≤ v ∧ v ≤ 0x07F3 then some (LineBreak.combiningMark) else none
                else if 0x07F5 < v then
                  if v == 0x07F6 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x07F7 < v then
                if v < 0x07F9 then
                  if v == 0x07F8 then some (LineBreak.infixNumeric) else none
                else if 0x07F9 < v then
                  if v == 0x07FA then some (LineBreak.alphabetic) else none
                else some (LineBreak.exclamation)
              else some (LineBreak.alphabetic)
            else some (LineBreak.alphabetic)
          else if 0x07FD < v then
            if v < 0x0828 then
              if v < 0x081A then
                if v < 0x0800 then
                  if 0x07FE ≤ v ∧ v ≤ 0x07FF then some (LineBreak.prefixNumeric) else none
                else if 0x0815 < v then
                  if 0x0816 ≤ v ∧ v ≤ 0x0819 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x081A < v then
                if v < 0x0824 then
                  if 0x081B ≤ v ∧ v ≤ 0x0823 then some (LineBreak.combiningMark) else none
                else if 0x0824 < v then
                  if 0x0825 ≤ v ∧ v ≤ 0x0827 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else if 0x0828 < v then
              if v < 0x0859 then
                if v < 0x0830 then
                  if 0x0829 ≤ v ∧ v ≤ 0x082D then some (LineBreak.combiningMark) else none
                else if 0x083E < v then
                  if 0x0840 ≤ v ∧ v ≤ 0x0858 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x085B < v then
                if v < 0x0860 then
                  if v == 0x085E then some (LineBreak.alphabetic) else none
                else if 0x086A < v then
                  if 0x0870 ≤ v ∧ v ≤ 0x0887 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else some (LineBreak.alphabetic)
          else some (LineBreak.combiningMark)
        else if 0x0888 < v then
          if v < 0x093E then
            if v < 0x08E3 then
              if v < 0x08A0 then
                if v < 0x0890 then
                  if 0x0889 ≤ v ∧ v ≤ 0x088F then some (LineBreak.alphabetic) else none
                else if 0x0891 < v then
                  if 0x0897 ≤ v ∧ v ≤ 0x089F then some (LineBreak.combiningMark) else none
                else some (LineBreak.numeric)
              else if 0x08C8 < v then
                if v < 0x08CA then
                  if v == 0x08C9 then some (LineBreak.alphabetic) else none
                else if 0x08E1 < v then
                  if v == 0x08E2 then some (LineBreak.numeric) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.alphabetic)
            else if 0x08FF < v then
              if v < 0x093A then
                if v < 0x0903 then
                  if 0x0900 ≤ v ∧ v ≤ 0x0902 then some (LineBreak.combiningMark) else none
                else if 0x0903 < v then
                  if 0x0904 ≤ v ∧ v ≤ 0x0939 then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else if 0x093A < v then
                if v < 0x093C then
                  if v == 0x093B then some (LineBreak.combiningMark) else none
                else if 0x093C < v then
                  if v == 0x093D then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else some (LineBreak.combiningMark)
          else if 0x0940 < v then
            if v < 0x0962 then
              if v < 0x094E then
                if v < 0x0949 then
                  if 0x0941 ≤ v ∧ v ≤ 0x0948 then some (LineBreak.combiningMark) else none
                else if 0x094C < v then
                  if v == 0x094D then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else if 0x094F < v then
                if v < 0x0951 then
                  if v == 0x0950 then some (LineBreak.alphabetic) else none
                else if 0x0957 < v then
                  if 0x0958 ≤ v ∧ v ≤ 0x0961 then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else if 0x0963 < v then
              if v < 0x0971 then
                if v < 0x0966 then
                  if 0x0964 ≤ v ∧ v ≤ 0x0965 then some (LineBreak.breakAfter) else none
                else if 0x096F < v then
                  if v == 0x0970 then some (LineBreak.alphabetic) else none
                else some (LineBreak.numeric)
              else if 0x0971 < v then
                if v < 0x0980 then
                  if 0x0972 ≤ v ∧ v ≤ 0x097F then some (LineBreak.alphabetic) else none
                else if 0x0980 < v then
                  if v == 0x0981 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else some (LineBreak.combiningMark)
          else some (LineBreak.combiningMark)
        else some (LineBreak.alphabetic)
      else some (LineBreak.alphabetic)
    else some (LineBreak.combiningMark)
  else if 0x0983 < v then
    if v < 0x0C05 then
      if v < 0x0AC9 then
        if v < 0x0A0F then
          if v < 0x09DC then
            if v < 0x09BD then
              if v < 0x09AA then
                if v < 0x098F then
                  if 0x0985 ≤ v ∧ v ≤ 0x098C then some (LineBreak.alphabetic) else none
                else if 0x0990 < v then
                  if 0x0993 ≤ v ∧ v ≤ 0x09A8 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x09B0 < v then
                if v < 0x09B6 then
                  if v == 0x09B2 then some (LineBreak.alphabetic) else none
                else if 0x09B9 < v then
                  if v == 0x09BC then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else if 0x09BD < v then
              if v < 0x09CB then
                if v < 0x09C1 then
                  if 0x09BE ≤ v ∧ v ≤ 0x09C0 then some (LineBreak.combiningMark) else none
                else if 0x09C4 < v then
                  if 0x09C7 ≤ v ∧ v ≤ 0x09C8 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else if 0x09CC < v then
                if v < 0x09CE then
                  if v == 0x09CD then some (LineBreak.combiningMark) else none
                else if 0x09CE < v then
                  if v == 0x09D7 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else some (LineBreak.alphabetic)
          else if 0x09DD < v then
            if v < 0x09FA then
              if v < 0x09F0 then
                if v < 0x09E2 then
                  if 0x09DF ≤ v ∧ v ≤ 0x09E1 then some (LineBreak.alphabetic) else none
                else if 0x09E3 < v then
                  if 0x09E6 ≤ v ∧ v ≤ 0x09EF then some (LineBreak.numeric) else none
                else some (LineBreak.combiningMark)
              else if 0x09F1 < v then
                if v < 0x09F4 then
                  if 0x09F2 ≤ v ∧ v ≤ 0x09F3 then some (LineBreak.postfixNumeric) else none
                else if 0x09F8 < v then
                  if v == 0x09F9 then some (LineBreak.postfixNumeric) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else if 0x09FA < v then
              if v < 0x09FE then
                if v < 0x09FC then
                  if v == 0x09FB then some (LineBreak.prefixNumeric) else none
                else if 0x09FC < v then
                  if v == 0x09FD then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x09FE < v then
                if v < 0x0A03 then
                  if 0x0A01 ≤ v ∧ v ≤ 0x0A02 then some (LineBreak.combiningMark) else none
                else if 0x0A03 < v then
                  if 0x0A05 ≤ v ∧ v ≤ 0x0A0A then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else some (LineBreak.alphabetic)
          else some (LineBreak.alphabetic)
        else if 0x0A10 < v then
          if v < 0x0A72 then
            if v < 0x0A41 then
              if v < 0x0A35 then
                if v < 0x0A2A then
                  if 0x0A13 ≤ v ∧ v ≤ 0x0A28 then some (LineBreak.alphabetic) else none
                else if 0x0A30 < v then
                  if 0x0A32 ≤ v ∧ v ≤ 0x0A33 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x0A36 < v then
                if v < 0x0A3C then
                  if 0x0A38 ≤ v ∧ v ≤ 0x0A39 then some (LineBreak.alphabetic) else none
                else if 0x0A3C < v then
                  if 0x0A3E ≤ v ∧ v ≤ 0x0A40 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.alphabetic)
            else if 0x0A42 < v then
              if v < 0x0A59 then
                if v < 0x0A4B then
                  if 0x0A47 ≤ v ∧ v ≤ 0x0A48 then some (LineBreak.combiningMark) else none
                else if 0x0A4D < v then
                  if v == 0x0A51 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else if 0x0A5C < v then
                if v < 0x0A66 then
                  if v == 0x0A5E then some (LineBreak.alphabetic) else none
                else if 0x0A6F < v then
                  if 0x0A70 ≤ v ∧ v ≤ 0x0A71 then some (LineBreak.combiningMark) else none
                else some (LineBreak.numeric)
              else some (LineBreak.alphabetic)
            else some (LineBreak.combiningMark)
          else if 0x0A74 < v then
            if v < 0x0AAA then
              if v < 0x0A83 then
                if v < 0x0A76 then
                  if v == 0x0A75 then some (LineBreak.combiningMark) else none
                else if 0x0A76 < v then
                  if 0x0A81 ≤ v ∧ v ≤ 0x0A82 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x0A83 < v then
                if v < 0x0A8F then
                  if 0x0A85 ≤ v ∧ v ≤ 0x0A8D then some (LineBreak.alphabetic) else none
                else if 0x0A91 < v then
                  if 0x0A93 ≤ v ∧ v ≤ 0x0AA8 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else if 0x0AB0 < v then
              if v < 0x0ABD then
                if v < 0x0AB5 then
                  if 0x0AB2 ≤ v ∧ v ≤ 0x0AB3 then some (LineBreak.alphabetic) else none
                else if 0x0AB9 < v then
                  if v == 0x0ABC then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x0ABD < v then
                if v < 0x0AC1 then
                  if 0x0ABE ≤ v ∧ v ≤ 0x0AC0 then some (LineBreak.combiningMark) else none
                else if 0x0AC5 < v then
                  if 0x0AC7 ≤ v ∧ v ≤ 0x0AC8 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.alphabetic)
            else some (LineBreak.alphabetic)
          else some (LineBreak.alphabetic)
        else some (LineBreak.alphabetic)
      else if 0x0AC9 < v then
        if v < 0x0B62 then
          if v < 0x0B2A then
            if v < 0x0AF1 then
              if v < 0x0AE0 then
                if v < 0x0ACD then
                  if 0x0ACB ≤ v ∧ v ≤ 0x0ACC then some (LineBreak.combiningMark) else none
                else if 0x0ACD < v then
                  if v == 0x0AD0 then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else if 0x0AE1 < v then
                if v < 0x0AE6 then
                  if 0x0AE2 ≤ v ∧ v ≤ 0x0AE3 then some (LineBreak.combiningMark) else none
                else if 0x0AEF < v then
                  if v == 0x0AF0 then some (LineBreak.alphabetic) else none
                else some (LineBreak.numeric)
              else some (LineBreak.alphabetic)
            else if 0x0AF1 < v then
              if v < 0x0B02 then
                if v < 0x0AFA then
                  if v == 0x0AF9 then some (LineBreak.alphabetic) else none
                else if 0x0AFF < v then
                  if v == 0x0B01 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else if 0x0B03 < v then
                if v < 0x0B0F then
                  if 0x0B05 ≤ v ∧ v ≤ 0x0B0C then some (LineBreak.alphabetic) else none
                else if 0x0B10 < v then
                  if 0x0B13 ≤ v ∧ v ≤ 0x0B28 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else some (LineBreak.prefixNumeric)
          else if 0x0B30 < v then
            if v < 0x0B41 then
              if v < 0x0B3D then
                if v < 0x0B35 then
                  if 0x0B32 ≤ v ∧ v ≤ 0x0B33 then some (LineBreak.alphabetic) else none
                else if 0x0B39 < v then
                  if v == 0x0B3C then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x0B3D < v then
                if v < 0x0B3F then
                  if v == 0x0B3E then some (LineBreak.combiningMark) else none
                else if 0x0B3F < v then
                  if v == 0x0B40 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.alphabetic)
            else if 0x0B44 < v then
              if v < 0x0B55 then
                if v < 0x0B4B then
                  if 0x0B47 ≤ v ∧ v ≤ 0x0B48 then some (LineBreak.combiningMark) else none
                else if 0x0B4C < v then
                  if v == 0x0B4D then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else if 0x0B56 < v then
                if v < 0x0B5C then
                  if v == 0x0B57 then some (LineBreak.combiningMark) else none
                else if 0x0B5D < v then
                  if 0x0B5F ≤ v ∧ v ≤ 0x0B61 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else some (LineBreak.combiningMark)
          else some (LineBreak.alphabetic)
        else if 0x0B63 < v then
          if v < 0x0BBE then
            if v < 0x0B8E then
              if v < 0x0B72 then
                if v < 0x0B70 then
                  if 0x0B66 ≤ v ∧ v ≤ 0x0B6F then some (LineBreak.numeric) else none
                else if 0x0B70 < v then
                  if v == 0x0B71 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x0B77 < v then
                if v < 0x0B83 then
                  if v == 0x0B82 then some (LineBreak.combiningMark) else none
                else if 0x0B83 < v then
                  if 0x0B85 ≤ v ∧ v ≤ 0x0B8A then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else if 0x0B90 < v then
              if v < 0x0B9E then
                if v < 0x0B99 then
                  if 0x0B92 ≤ v ∧ v ≤ 0x0B95 then some (LineBreak.alphabetic) else none
                else if 0x0B9A < v then
                  if v == 0x0B9C then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x0B9F < v then
                if v < 0x0BA8 then
                  if 0x0BA3 ≤ v ∧ v ≤ 0x0BA4 then some (LineBreak.alphabetic) else none
                else if 0x0BAA < v then
                  if 0x0BAE ≤ v ∧ v ≤ 0x0BB9 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.alphabetic)
            else some (LineBreak.alphabetic)
          else if 0x0BBF < v then
            if v < 0x0BE6 then
              if v < 0x0BCA then
                if v < 0x0BC1 then
                  if v == 0x0BC0 then some (LineBreak.combiningMark) else none
                else if 0x0BC2 < v then
                  if 0x0BC6 ≤ v ∧ v ≤ 0x0BC8 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else if 0x0BCC < v then
                if v < 0x0BD0 then
                  if v == 0x0BCD then some (LineBreak.combiningMark) else none
                else if 0x0BD0 < v then
                  if v == 0x0BD7 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else if 0x0BEF < v then
              if v < 0x0BFA then
                if v < 0x0BF3 then
                  if 0x0BF0 ≤ v ∧ v ≤ 0x0BF2 then some (LineBreak.alphabetic) else none
                else if 0x0BF8 < v then
                  if v == 0x0BF9 then some (LineBreak.prefixNumeric) else none
                else some (LineBreak.alphabetic)
              else if 0x0BFA < v then
                if v < 0x0C01 then
                  if v == 0x0C00 then some (LineBreak.combiningMark) else none
                else if 0x0C03 < v then
                  if v == 0x0C04 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.alphabetic)
            else some (LineBreak.numeric)
          else some (LineBreak.combiningMark)
        else some (LineBreak.combiningMark)
      else some (LineBreak.combiningMark)
    else if 0x0C0C < v then
      if v < 0x0D70 then
        if v < 0x0CC0 then
          if v < 0x0C77 then
            if v < 0x0C46 then
              if v < 0x0C3C then
                if v < 0x0C12 then
                  if 0x0C0E ≤ v ∧ v ≤ 0x0C10 then some (LineBreak.alphabetic) else none
                else if 0x0C28 < v then
                  if 0x0C2A ≤ v ∧ v ≤ 0x0C39 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x0C3C < v then
                if v < 0x0C3E then
                  if v == 0x0C3D then some (LineBreak.alphabetic) else none
                else if 0x0C40 < v then
                  if 0x0C41 ≤ v ∧ v ≤ 0x0C44 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else if 0x0C48 < v then
              if v < 0x0C5C then
                if v < 0x0C55 then
                  if 0x0C4A ≤ v ∧ v ≤ 0x0C4D then some (LineBreak.combiningMark) else none
                else if 0x0C56 < v then
                  if 0x0C58 ≤ v ∧ v ≤ 0x0C5A then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else if 0x0C5D < v then
                if v < 0x0C62 then
                  if 0x0C60 ≤ v ∧ v ≤ 0x0C61 then some (LineBreak.alphabetic) else none
                else if 0x0C63 < v then
                  if 0x0C66 ≤ v ∧ v ≤ 0x0C6F then some (LineBreak.numeric) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.alphabetic)
            else some (LineBreak.combiningMark)
          else if 0x0C77 < v then
            if v < 0x0C8E then
              if v < 0x0C81 then
                if v < 0x0C7F then
                  if 0x0C78 ≤ v ∧ v ≤ 0x0C7E then some (LineBreak.alphabetic) else none
                else if 0x0C7F < v then
                  if v == 0x0C80 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x0C81 < v then
                if v < 0x0C84 then
                  if 0x0C82 ≤ v ∧ v ≤ 0x0C83 then some (LineBreak.combiningMark) else none
                else if 0x0C84 < v then
                  if 0x0C85 ≤ v ∧ v ≤ 0x0C8C then some (LineBreak.alphabetic) else none
                else some (LineBreak.breakBefore)
              else some (LineBreak.combiningMark)
            else if 0x0C90 < v then
              if v < 0x0CBC then
                if v < 0x0CAA then
                  if 0x0C92 ≤ v ∧ v ≤ 0x0CA8 then some (LineBreak.alphabetic) else none
                else if 0x0CB3 < v then
                  if 0x0CB5 ≤ v ∧ v ≤ 0x0CB9 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else if 0x0CBC < v then
                if v < 0x0CBE then
                  if v == 0x0CBD then some (LineBreak.alphabetic) else none
                else if 0x0CBE < v then
                  if v == 0x0CBF then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else some (LineBreak.alphabetic)
          else some (LineBreak.breakBefore)
        else if 0x0CC4 < v then
          if v < 0x0D12 then
            if v < 0x0CE2 then
              if v < 0x0CCC then
                if v < 0x0CC7 then
                  if v == 0x0CC6 then some (LineBreak.combiningMark) else none
                else if 0x0CC8 < v then
                  if 0x0CCA ≤ v ∧ v ≤ 0x0CCB then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else if 0x0CCD < v then
                if v < 0x0CDC then
                  if 0x0CD5 ≤ v ∧ v ≤ 0x0CD6 then some (LineBreak.combiningMark) else none
                else if 0x0CDE < v then
                  if 0x0CE0 ≤ v ∧ v ≤ 0x0CE1 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else if 0x0CE3 < v then
              if v < 0x0D00 then
                if v < 0x0CF1 then
                  if 0x0CE6 ≤ v ∧ v ≤ 0x0CEF then some (LineBreak.numeric) else none
                else if 0x0CF2 < v then
                  if v == 0x0CF3 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x0D01 < v then
                if v < 0x0D04 then
                  if 0x0D02 ≤ v ∧ v ≤ 0x0D03 then some (LineBreak.combiningMark) else none
                else if 0x0D0C < v then
                  if 0x0D0E ≤ v ∧ v ≤ 0x0D10 then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else some (LineBreak.combiningMark)
          else if 0x0D3A < v then
            if v < 0x0D4E then
              if v < 0x0D41 then
                if v < 0x0D3D then
                  if 0x0D3B ≤ v ∧ v ≤ 0x0D3C then some (LineBreak.combiningMark) else none
                else if 0x0D3D < v then
                  if 0x0D3E ≤ v ∧ v ≤ 0x0D40 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x0D44 < v then
                if v < 0x0D4A then
                  if 0x0D46 ≤ v ∧ v ≤ 0x0D48 then some (LineBreak.combiningMark) else none
                else if 0x0D4C < v then
                  if v == 0x0D4D then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else if 0x0D4E < v then
              if v < 0x0D58 then
                if v < 0x0D54 then
                  if v == 0x0D4F then some (LineBreak.alphabetic) else none
                else if 0x0D56 < v then
                  if v == 0x0D57 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x0D5E < v then
                if v < 0x0D62 then
                  if 0x0D5F ≤ v ∧ v ≤ 0x0D61 then some (LineBreak.alphabetic) else none
                else if 0x0D63 < v then
                  if 0x0D66 ≤ v ∧ v ≤ 0x0D6F then some (LineBreak.numeric) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.alphabetic)
            else some (LineBreak.alphabetic)
          else some (LineBreak.alphabetic)
        else some (LineBreak.combiningMark)
      else if 0x0D78 < v then
        if v < 0x0E8C then
          if v < 0x0DF2 then
            if v < 0x0DBD then
              if v < 0x0D82 then
                if v < 0x0D7A then
                  if v == 0x0D79 then some (LineBreak.postfixNumeric) else none
                else if 0x0D7F < v then
                  if v == 0x0D81 then some (LineBreak.combiningMark) else none
                else some (LineBreak.alphabetic)
              else if 0x0D83 < v then
                if v < 0x0D9A then
                  if 0x0D85 ≤ v ∧ v ≤ 0x0D96 then some (LineBreak.alphabetic) else none
                else if 0x0DB1 < v then
                  if 0x0DB3 ≤ v ∧ v ≤ 0x0DBB then some (LineBreak.alphabetic) else none
                else some (LineBreak.alphabetic)
              else some (LineBreak.combiningMark)
            else if 0x0DBD < v then
              if v < 0x0DD2 then
                if v < 0x0DCA then
                  if 0x0DC0 ≤ v ∧ v ≤ 0x0DC6 then some (LineBreak.alphabetic) else none
                else if 0x0DCA < v then
                  if 0x0DCF ≤ v ∧ v ≤ 0x0DD1 then some (LineBreak.combiningMark) else none
                else some (LineBreak.combiningMark)
              else if 0x0DD4 < v then
                if v < 0x0DD8 then
                  if v == 0x0DD6 then some (LineBreak.combiningMark) else none
                else if 0x0DDF < v then
                  if 0x0DE6 ≤ v ∧ v ≤ 0x0DEF then some (LineBreak.numeric) else none
                else some (LineBreak.combiningMark)
              else some (LineBreak.combiningMark)
            else some (LineBreak.alphabetic)
          else if 0x0DF3 < v then
            if v < 0x0E46 then
              if v < 0x0E32 then
                if v < 0x0E01 then
                  if v == 0x0DF4 then some (LineBreak.alphabetic) else none
                else if 0x0E30 < v then
                  if v == 0x0E31 then some (LineBreak.complexContext) else none
                else some (LineBreak.complexContext)
              else if 0x0E33 < v then
                if v < 0x0E3F then
                  if 0x0E34 ≤ v ∧ v ≤ 0x0E3A then some (LineBreak.complexContext) else none
                else if 0x0E3F < v then
                  if 0x0E40 ≤ v ∧ v ≤ 0x0E45 then some (LineBreak.complexContext) else none
                else some (LineBreak.prefixNumeric)
              else some (LineBreak.complexContext)
            else if 0x0E46 < v then
              if v < 0x0E5A then
                if v < 0x0E4F then
                  if 0x0E47 ≤ v ∧ v ≤ 0x0E4E then some (LineBreak.complexContext) else none
                else if 0x0E4F < v then
                  if 0x0E50 ≤ v ∧ v ≤ 0x0E59 then some (LineBreak.numeric) else none
                else some (LineBreak.alphabetic)
              else if 0x0E5B < v then
                if v < 0x0E84 then
                  if 0x0E81 ≤ v ∧ v ≤ 0x0E82 then some (LineBreak.complexContext) else none
                else if 0x0E84 < v then
                  if 0x0E86 ≤ v ∧ v ≤ 0x0E8A then some (LineBreak.complexContext) else none
                else some (LineBreak.complexContext)
              else some (LineBreak.breakAfter)
            else some (LineBreak.complexContext)
          else some (LineBreak.combiningMark)
        else if 0x0EA3 < v then
          if v < 0x0F06 then
            if v < 0x0EC6 then
              if v < 0x0EB2 then
                if v < 0x0EA7 then
                  if v == 0x0EA5 then some (LineBreak.complexContext) else none
                else if 0x0EB0 < v then
                  if v == 0x0EB1 then some (LineBreak.complexContext) else none
                else some (LineBreak.complexContext)
              else if 0x0EB3 < v then
                if v < 0x0EBD then
                  if 0x0EB4 ≤ v ∧ v ≤ 0x0EBC then some (LineBreak.complexContext) else none
                else if 0x0EBD < v then
                  if 0x0EC0 ≤ v ∧ v ≤ 0x0EC4 then some (LineBreak.complexContext) else none
                else some (LineBreak.complexContext)
              else some (LineBreak.complexContext)
            else if 0x0EC6 < v then
              if v < 0x0F00 then
                if v < 0x0ED0 then
                  if 0x0EC8 ≤ v ∧ v ≤ 0x0ECE then some (LineBreak.complexContext) else none
                else if 0x0ED9 < v then
                  if 0x0EDC ≤ v ∧ v ≤ 0x0EDF then some (LineBreak.complexContext) else none
                else some (LineBreak.numeric)
              else if 0x0F00 < v then
                if v < 0x0F04 then
                  if 0x0F01 ≤ v ∧ v ≤ 0x0F03 then some (LineBreak.breakBefore) else none
                else if 0x0F04 < v then
                  if v == 0x0F05 then some (LineBreak.alphabetic) else none
                else some (LineBreak.breakBefore)
              else some (LineBreak.alphabetic)
            else some (LineBreak.complexContext)
          else if 0x0F07 < v then
            if v < 0x0F14 then
              if v < 0x0F0C then
                if v < 0x0F09 then
                  if v == 0x0F08 then some (LineBreak.glue) else none
                else if 0x0F0A < v then
                  if v == 0x0F0B then some (LineBreak.breakAfter) else none
                else some (LineBreak.breakBefore)
              else if 0x0F0C < v then
                if v < 0x0F12 then
                  if 0x0F0D ≤ v ∧ v ≤ 0x0F11 then some (LineBreak.exclamation) else none
                else if 0x0F12 < v then
                  if v == 0x0F13 then some (LineBreak.alphabetic) else none
                else some (LineBreak.glue)
              else some (LineBreak.glue)
            else if 0x0F14 < v then
              if v < 0x0F20 then
                if v < 0x0F18 then
                  if 0x0F15 ≤ v ∧ v ≤ 0x0F17 then some (LineBreak.alphabetic) else none
                else if 0x0F19 < v then
                  if 0x0F1A ≤ v ∧ v ≤ 0x0F1F then some (LineBreak.alphabetic) else none
                else some (LineBreak.combiningMark)
              else if 0x0F29 < v then
                if v < 0x0F34 then
                  if 0x0F2A ≤ v ∧ v ≤ 0x0F33 then some (LineBreak.alphabetic) else none
                else if 0x0F34 < v then
                  if v == 0x0F35 then some (LineBreak.combiningMark) else none
                else some (LineBreak.breakAfter)
              else some (LineBreak.numeric)
            else some (LineBreak.exclamation)
          else some (LineBreak.breakBefore)
        else some (LineBreak.complexContext)
      else some (LineBreak.alphabetic)
    else some (LineBreak.alphabetic)
  else some (LineBreak.combiningMark)

end Unicode.TableLookupTables.LineBreak.Chunk0
