/- This file is generated by table-generators/makeTablesForLookup. -/
module

@[expose] public section

namespace Unicode.TableLookupTables.Lowercase

abbrev start : UInt32 := 0x0061

abbrev «end» : UInt32 := 0x1E943

abbrev BetweenOrEqStartEnd (v : UInt32) : Prop := start ≤ v ∧ v ≤ «end»

@[inline_if_reduce, reducible]
def IsInsideSparseRangeTable (v : UInt32) (_h : BetweenOrEqStartEnd v) : Prop :=
  if v < 0x1E73 then
    if v < 0x03ED then
      if v < 0x01B6 then
        if v < 0x014B then
          if v < 0x011F then
            if v < 0x0109 then
              if v < 0x00F8 then
                if v < 0x00B5 then
                  if v < 0x00AA then
                    0x0061 ≤ v ∧ v ≤ 0x007A
                  else if 0x00AA < v then
                    False
                  else True
                else if 0x00B5 < v then
                  if v < 0x00DF then
                    v = 0x00BA
                  else if 0x00F6 < v then
                    False
                  else True
                else True
              else if 0x00FF < v then
                if v < 0x0105 then
                  if v < 0x0103 then
                    v = 0x0101
                  else if 0x0103 < v then
                    False
                  else True
                else if 0x0105 < v then
                  v = 0x0107
                else True
              else True
            else if 0x0109 < v then
              if v < 0x0115 then
                if v < 0x010F then
                  if v < 0x010D then
                    v = 0x010B
                  else if 0x010D < v then
                    False
                  else True
                else if 0x010F < v then
                  if v < 0x0113 then
                    v = 0x0111
                  else if 0x0113 < v then
                    False
                  else True
                else True
              else if 0x0115 < v then
                if v < 0x011B then
                  if v < 0x0119 then
                    v = 0x0117
                  else if 0x0119 < v then
                    False
                  else True
                else if 0x011B < v then
                  v = 0x011D
                else True
              else True
            else True
          else if 0x011F < v then
            if v < 0x0135 then
              if v < 0x012B then
                if v < 0x0125 then
                  if v < 0x0123 then
                    v = 0x0121
                  else if 0x0123 < v then
                    False
                  else True
                else if 0x0125 < v then
                  if v < 0x0129 then
                    v = 0x0127
                  else if 0x0129 < v then
                    False
                  else True
                else True
              else if 0x012B < v then
                if v < 0x0131 then
                  if v < 0x012F then
                    v = 0x012D
                  else if 0x012F < v then
                    False
                  else True
                else if 0x0131 < v then
                  v = 0x0133
                else True
              else True
            else if 0x0135 < v then
              if v < 0x0140 then
                if v < 0x013C then
                  if v < 0x013A then
                    0x0137 ≤ v ∧ v ≤ 0x0138
                  else if 0x013A < v then
                    False
                  else True
                else if 0x013C < v then
                  v = 0x013E
                else True
              else if 0x0140 < v then
                if v < 0x0146 then
                  if v < 0x0144 then
                    v = 0x0142
                  else if 0x0144 < v then
                    False
                  else True
                else if 0x0146 < v then
                  0x0148 ≤ v ∧ v ≤ 0x0149
                else True
              else True
            else True
          else True
        else if 0x014B < v then
          if v < 0x0175 then
            if v < 0x0161 then
              if v < 0x0157 then
                if v < 0x0151 then
                  if v < 0x014F then
                    v = 0x014D
                  else if 0x014F < v then
                    False
                  else True
                else if 0x0151 < v then
                  if v < 0x0155 then
                    v = 0x0153
                  else if 0x0155 < v then
                    False
                  else True
                else True
              else if 0x0157 < v then
                if v < 0x015D then
                  if v < 0x015B then
                    v = 0x0159
                  else if 0x015B < v then
                    False
                  else True
                else if 0x015D < v then
                  v = 0x015F
                else True
              else True
            else if 0x0161 < v then
              if v < 0x016B then
                if v < 0x0167 then
                  if v < 0x0165 then
                    v = 0x0163
                  else if 0x0165 < v then
                    False
                  else True
                else if 0x0167 < v then
                  v = 0x0169
                else True
              else if 0x016B < v then
                if v < 0x0171 then
                  if v < 0x016F then
                    v = 0x016D
                  else if 0x016F < v then
                    False
                  else True
                else if 0x0171 < v then
                  v = 0x0173
                else True
              else True
            else True
          else if 0x0175 < v then
            if v < 0x0199 then
              if v < 0x0185 then
                if v < 0x017C then
                  if v < 0x017A then
                    v = 0x0177
                  else if 0x017A < v then
                    False
                  else True
                else if 0x017C < v then
                  if v < 0x0183 then
                    0x017E ≤ v ∧ v ≤ 0x0180
                  else if 0x0183 < v then
                    False
                  else True
                else True
              else if 0x0185 < v then
                if v < 0x0192 then
                  if v < 0x018C then
                    v = 0x0188
                  else if 0x018D < v then
                    False
                  else True
                else if 0x0192 < v then
                  v = 0x0195
                else True
              else True
            else if 0x019B < v then
              if v < 0x01A8 then
                if v < 0x01A3 then
                  if v < 0x01A1 then
                    v = 0x019E
                  else if 0x01A1 < v then
                    False
                  else True
                else if 0x01A3 < v then
                  v = 0x01A5
                else True
              else if 0x01A8 < v then
                if v < 0x01B0 then
                  if v < 0x01AD then
                    0x01AA ≤ v ∧ v ≤ 0x01AB
                  else if 0x01AD < v then
                    False
                  else True
                else if 0x01B0 < v then
                  v = 0x01B4
                else True
              else True
            else True
          else True
        else True
      else if 0x01B6 < v then
        if v < 0x021D then
          if v < 0x01EF then
            if v < 0x01D8 then
              if v < 0x01CE then
                if v < 0x01C6 then
                  if v < 0x01BD then
                    0x01B9 ≤ v ∧ v ≤ 0x01BA
                  else if 0x01BF < v then
                    False
                  else True
                else if 0x01C6 < v then
                  if v < 0x01CC then
                    v = 0x01C9
                  else if 0x01CC < v then
                    False
                  else True
                else True
              else if 0x01CE < v then
                if v < 0x01D4 then
                  if v < 0x01D2 then
                    v = 0x01D0
                  else if 0x01D2 < v then
                    False
                  else True
                else if 0x01D4 < v then
                  v = 0x01D6
                else True
              else True
            else if 0x01D8 < v then
              if v < 0x01E5 then
                if v < 0x01DF then
                  if v < 0x01DC then
                    v = 0x01DA
                  else if 0x01DD < v then
                    False
                  else True
                else if 0x01DF < v then
                  if v < 0x01E3 then
                    v = 0x01E1
                  else if 0x01E3 < v then
                    False
                  else True
                else True
              else if 0x01E5 < v then
                if v < 0x01EB then
                  if v < 0x01E9 then
                    v = 0x01E7
                  else if 0x01E9 < v then
                    False
                  else True
                else if 0x01EB < v then
                  v = 0x01ED
                else True
              else True
            else True
          else if 0x01F0 < v then
            if v < 0x0209 then
              if v < 0x01FF then
                if v < 0x01F9 then
                  if v < 0x01F5 then
                    v = 0x01F3
                  else if 0x01F5 < v then
                    False
                  else True
                else if 0x01F9 < v then
                  if v < 0x01FD then
                    v = 0x01FB
                  else if 0x01FD < v then
                    False
                  else True
                else True
              else if 0x01FF < v then
                if v < 0x0205 then
                  if v < 0x0203 then
                    v = 0x0201
                  else if 0x0203 < v then
                    False
                  else True
                else if 0x0205 < v then
                  v = 0x0207
                else True
              else True
            else if 0x0209 < v then
              if v < 0x0213 then
                if v < 0x020F then
                  if v < 0x020D then
                    v = 0x020B
                  else if 0x020D < v then
                    False
                  else True
                else if 0x020F < v then
                  v = 0x0211
                else True
              else if 0x0213 < v then
                if v < 0x0219 then
                  if v < 0x0217 then
                    v = 0x0215
                  else if 0x0217 < v then
                    False
                  else True
                else if 0x0219 < v then
                  v = 0x021B
                else True
              else True
            else True
          else True
        else if 0x021D < v then
          if v < 0x02C0 then
            if v < 0x0233 then
              if v < 0x0229 then
                if v < 0x0223 then
                  if v < 0x0221 then
                    v = 0x021F
                  else if 0x0221 < v then
                    False
                  else True
                else if 0x0223 < v then
                  if v < 0x0227 then
                    v = 0x0225
                  else if 0x0227 < v then
                    False
                  else True
                else True
              else if 0x0229 < v then
                if v < 0x022F then
                  if v < 0x022D then
                    v = 0x022B
                  else if 0x022D < v then
                    False
                  else True
                else if 0x022F < v then
                  v = 0x0231
                else True
              else True
            else if 0x0239 < v then
              if v < 0x0249 then
                if v < 0x0242 then
                  if v < 0x023F then
                    v = 0x023C
                  else if 0x0240 < v then
                    False
                  else True
                else if 0x0242 < v then
                  v = 0x0247
                else True
              else if 0x0249 < v then
                if v < 0x024F then
                  if v < 0x024D then
                    v = 0x024B
                  else if 0x024D < v then
                    False
                  else True
                else if 0x0293 < v then
                  0x0296 ≤ v ∧ v ≤ 0x02B8
                else True
              else True
            else True
          else if 0x02C1 < v then
            if v < 0x03D9 then
              if v < 0x037A then
                if v < 0x0371 then
                  if v < 0x0345 then
                    0x02E0 ≤ v ∧ v ≤ 0x02E4
                  else if 0x0345 < v then
                    False
                  else True
                else if 0x0371 < v then
                  if v < 0x0377 then
                    v = 0x0373
                  else if 0x0377 < v then
                    False
                  else True
                else True
              else if 0x037D < v then
                if v < 0x03D0 then
                  if v < 0x03AC then
                    v = 0x0390
                  else if 0x03CE < v then
                    False
                  else True
                else if 0x03D1 < v then
                  0x03D5 ≤ v ∧ v ≤ 0x03D7
                else True
              else True
            else if 0x03D9 < v then
              if v < 0x03E3 then
                if v < 0x03DF then
                  if v < 0x03DD then
                    v = 0x03DB
                  else if 0x03DD < v then
                    False
                  else True
                else if 0x03DF < v then
                  v = 0x03E1
                else True
              else if 0x03E3 < v then
                if v < 0x03E9 then
                  if v < 0x03E7 then
                    v = 0x03E5
                  else if 0x03E7 < v then
                    False
                  else True
                else if 0x03E9 < v then
                  v = 0x03EB
                else True
              else True
            else True
          else True
        else True
      else True
    else if 0x03ED < v then
      if v < 0x0509 then
        if v < 0x04B3 then
          if v < 0x0481 then
            if v < 0x046B then
              if v < 0x0461 then
                if v < 0x03F8 then
                  if v < 0x03F5 then
                    0x03EF ≤ v ∧ v ≤ 0x03F3
                  else if 0x03F5 < v then
                    False
                  else True
                else if 0x03F8 < v then
                  if v < 0x0430 then
                    0x03FB ≤ v ∧ v ≤ 0x03FC
                  else if 0x045F < v then
                    False
                  else True
                else True
              else if 0x0461 < v then
                if v < 0x0467 then
                  if v < 0x0465 then
                    v = 0x0463
                  else if 0x0465 < v then
                    False
                  else True
                else if 0x0467 < v then
                  v = 0x0469
                else True
              else True
            else if 0x046B < v then
              if v < 0x0477 then
                if v < 0x0471 then
                  if v < 0x046F then
                    v = 0x046D
                  else if 0x046F < v then
                    False
                  else True
                else if 0x0471 < v then
                  if v < 0x0475 then
                    v = 0x0473
                  else if 0x0475 < v then
                    False
                  else True
                else True
              else if 0x0477 < v then
                if v < 0x047D then
                  if v < 0x047B then
                    v = 0x0479
                  else if 0x047B < v then
                    False
                  else True
                else if 0x047D < v then
                  v = 0x047F
                else True
              else True
            else True
          else if 0x0481 < v then
            if v < 0x049F then
              if v < 0x0495 then
                if v < 0x048F then
                  if v < 0x048D then
                    v = 0x048B
                  else if 0x048D < v then
                    False
                  else True
                else if 0x048F < v then
                  if v < 0x0493 then
                    v = 0x0491
                  else if 0x0493 < v then
                    False
                  else True
                else True
              else if 0x0495 < v then
                if v < 0x049B then
                  if v < 0x0499 then
                    v = 0x0497
                  else if 0x0499 < v then
                    False
                  else True
                else if 0x049B < v then
                  v = 0x049D
                else True
              else True
            else if 0x049F < v then
              if v < 0x04A9 then
                if v < 0x04A5 then
                  if v < 0x04A3 then
                    v = 0x04A1
                  else if 0x04A3 < v then
                    False
                  else True
                else if 0x04A5 < v then
                  v = 0x04A7
                else True
              else if 0x04A9 < v then
                if v < 0x04AF then
                  if v < 0x04AD then
                    v = 0x04AB
                  else if 0x04AD < v then
                    False
                  else True
                else if 0x04AF < v then
                  v = 0x04B1
                else True
              else True
            else True
          else True
        else if 0x04B3 < v then
          if v < 0x04DF then
            if v < 0x04CA then
              if v < 0x04BF then
                if v < 0x04B9 then
                  if v < 0x04B7 then
                    v = 0x04B5
                  else if 0x04B7 < v then
                    False
                  else True
                else if 0x04B9 < v then
                  if v < 0x04BD then
                    v = 0x04BB
                  else if 0x04BD < v then
                    False
                  else True
                else True
              else if 0x04BF < v then
                if v < 0x04C6 then
                  if v < 0x04C4 then
                    v = 0x04C2
                  else if 0x04C4 < v then
                    False
                  else True
                else if 0x04C6 < v then
                  v = 0x04C8
                else True
              else True
            else if 0x04CA < v then
              if v < 0x04D5 then
                if v < 0x04D1 then
                  if v < 0x04CE then
                    v = 0x04CC
                  else if 0x04CF < v then
                    False
                  else True
                else if 0x04D1 < v then
                  v = 0x04D3
                else True
              else if 0x04D5 < v then
                if v < 0x04DB then
                  if v < 0x04D9 then
                    v = 0x04D7
                  else if 0x04D9 < v then
                    False
                  else True
                else if 0x04DB < v then
                  v = 0x04DD
                else True
              else True
            else True
          else if 0x04DF < v then
            if v < 0x04F5 then
              if v < 0x04EB then
                if v < 0x04E5 then
                  if v < 0x04E3 then
                    v = 0x04E1
                  else if 0x04E3 < v then
                    False
                  else True
                else if 0x04E5 < v then
                  if v < 0x04E9 then
                    v = 0x04E7
                  else if 0x04E9 < v then
                    False
                  else True
                else True
              else if 0x04EB < v then
                if v < 0x04F1 then
                  if v < 0x04EF then
                    v = 0x04ED
                  else if 0x04EF < v then
                    False
                  else True
                else if 0x04F1 < v then
                  v = 0x04F3
                else True
              else True
            else if 0x04F5 < v then
              if v < 0x04FF then
                if v < 0x04FB then
                  if v < 0x04F9 then
                    v = 0x04F7
                  else if 0x04F9 < v then
                    False
                  else True
                else if 0x04FB < v then
                  v = 0x04FD
                else True
              else if 0x04FF < v then
                if v < 0x0505 then
                  if v < 0x0503 then
                    v = 0x0501
                  else if 0x0503 < v then
                    False
                  else True
                else if 0x0505 < v then
                  v = 0x0507
                else True
              else True
            else True
          else True
        else True
      else if 0x0509 < v then
        if v < 0x1E1F then
          if v < 0x10D0 then
            if v < 0x051F then
              if v < 0x0515 then
                if v < 0x050F then
                  if v < 0x050D then
                    v = 0x050B
                  else if 0x050D < v then
                    False
                  else True
                else if 0x050F < v then
                  if v < 0x0513 then
                    v = 0x0511
                  else if 0x0513 < v then
                    False
                  else True
                else True
              else if 0x0515 < v then
                if v < 0x051B then
                  if v < 0x0519 then
                    v = 0x0517
                  else if 0x0519 < v then
                    False
                  else True
                else if 0x051B < v then
                  v = 0x051D
                else True
              else True
            else if 0x051F < v then
              if v < 0x0529 then
                if v < 0x0525 then
                  if v < 0x0523 then
                    v = 0x0521
                  else if 0x0523 < v then
                    False
                  else True
                else if 0x0525 < v then
                  v = 0x0527
                else True
              else if 0x0529 < v then
                if v < 0x052F then
                  if v < 0x052D then
                    v = 0x052B
                  else if 0x052D < v then
                    False
                  else True
                else if 0x052F < v then
                  0x0560 ≤ v ∧ v ≤ 0x0588
                else True
              else True
            else True
          else if 0x10FA < v then
            if v < 0x1E0B then
              if v < 0x1E01 then
                if v < 0x1C80 then
                  if v < 0x13F8 then
                    0x10FC ≤ v ∧ v ≤ 0x10FF
                  else if 0x13FD < v then
                    False
                  else True
                else if 0x1C88 < v then
                  if v < 0x1D00 then
                    v = 0x1C8A
                  else if 0x1DBF < v then
                    False
                  else True
                else True
              else if 0x1E01 < v then
                if v < 0x1E07 then
                  if v < 0x1E05 then
                    v = 0x1E03
                  else if 0x1E05 < v then
                    False
                  else True
                else if 0x1E07 < v then
                  v = 0x1E09
                else True
              else True
            else if 0x1E0B < v then
              if v < 0x1E15 then
                if v < 0x1E11 then
                  if v < 0x1E0F then
                    v = 0x1E0D
                  else if 0x1E0F < v then
                    False
                  else True
                else if 0x1E11 < v then
                  v = 0x1E13
                else True
              else if 0x1E15 < v then
                if v < 0x1E1B then
                  if v < 0x1E19 then
                    v = 0x1E17
                  else if 0x1E19 < v then
                    False
                  else True
                else if 0x1E1B < v then
                  v = 0x1E1D
                else True
              else True
            else True
          else True
        else if 0x1E1F < v then
          if v < 0x1E49 then
            if v < 0x1E35 then
              if v < 0x1E2B then
                if v < 0x1E25 then
                  if v < 0x1E23 then
                    v = 0x1E21
                  else if 0x1E23 < v then
                    False
                  else True
                else if 0x1E25 < v then
                  if v < 0x1E29 then
                    v = 0x1E27
                  else if 0x1E29 < v then
                    False
                  else True
                else True
              else if 0x1E2B < v then
                if v < 0x1E31 then
                  if v < 0x1E2F then
                    v = 0x1E2D
                  else if 0x1E2F < v then
                    False
                  else True
                else if 0x1E31 < v then
                  v = 0x1E33
                else True
              else True
            else if 0x1E35 < v then
              if v < 0x1E3F then
                if v < 0x1E3B then
                  if v < 0x1E39 then
                    v = 0x1E37
                  else if 0x1E39 < v then
                    False
                  else True
                else if 0x1E3B < v then
                  v = 0x1E3D
                else True
              else if 0x1E3F < v then
                if v < 0x1E45 then
                  if v < 0x1E43 then
                    v = 0x1E41
                  else if 0x1E43 < v then
                    False
                  else True
                else if 0x1E45 < v then
                  v = 0x1E47
                else True
              else True
            else True
          else if 0x1E49 < v then
            if v < 0x1E5F then
              if v < 0x1E55 then
                if v < 0x1E4F then
                  if v < 0x1E4D then
                    v = 0x1E4B
                  else if 0x1E4D < v then
                    False
                  else True
                else if 0x1E4F < v then
                  if v < 0x1E53 then
                    v = 0x1E51
                  else if 0x1E53 < v then
                    False
                  else True
                else True
              else if 0x1E55 < v then
                if v < 0x1E5B then
                  if v < 0x1E59 then
                    v = 0x1E57
                  else if 0x1E59 < v then
                    False
                  else True
                else if 0x1E5B < v then
                  v = 0x1E5D
                else True
              else True
            else if 0x1E5F < v then
              if v < 0x1E69 then
                if v < 0x1E65 then
                  if v < 0x1E63 then
                    v = 0x1E61
                  else if 0x1E63 < v then
                    False
                  else True
                else if 0x1E65 < v then
                  v = 0x1E67
                else True
              else if 0x1E69 < v then
                if v < 0x1E6F then
                  if v < 0x1E6D then
                    v = 0x1E6B
                  else if 0x1E6D < v then
                    False
                  else True
                else if 0x1E6F < v then
                  v = 0x1E71
                else True
              else True
            else True
          else True
        else True
      else True
    else True
  else if 0x1E73 < v then
    if v < 0xA647 then
      if v < 0x1FF2 then
        if v < 0x1ED1 then
          if v < 0x1EA7 then
            if v < 0x1E89 then
              if v < 0x1E7F then
                if v < 0x1E79 then
                  if v < 0x1E77 then
                    v = 0x1E75
                  else if 0x1E77 < v then
                    False
                  else True
                else if 0x1E79 < v then
                  if v < 0x1E7D then
                    v = 0x1E7B
                  else if 0x1E7D < v then
                    False
                  else True
                else True
              else if 0x1E7F < v then
                if v < 0x1E85 then
                  if v < 0x1E83 then
                    v = 0x1E81
                  else if 0x1E83 < v then
                    False
                  else True
                else if 0x1E85 < v then
                  v = 0x1E87
                else True
              else True
            else if 0x1E89 < v then
              if v < 0x1E95 then
                if v < 0x1E8F then
                  if v < 0x1E8D then
                    v = 0x1E8B
                  else if 0x1E8D < v then
                    False
                  else True
                else if 0x1E8F < v then
                  if v < 0x1E93 then
                    v = 0x1E91
                  else if 0x1E93 < v then
                    False
                  else True
                else True
              else if 0x1E9D < v then
                if v < 0x1EA3 then
                  if v < 0x1EA1 then
                    v = 0x1E9F
                  else if 0x1EA1 < v then
                    False
                  else True
                else if 0x1EA3 < v then
                  v = 0x1EA5
                else True
              else True
            else True
          else if 0x1EA7 < v then
            if v < 0x1EBD then
              if v < 0x1EB3 then
                if v < 0x1EAD then
                  if v < 0x1EAB then
                    v = 0x1EA9
                  else if 0x1EAB < v then
                    False
                  else True
                else if 0x1EAD < v then
                  if v < 0x1EB1 then
                    v = 0x1EAF
                  else if 0x1EB1 < v then
                    False
                  else True
                else True
              else if 0x1EB3 < v then
                if v < 0x1EB9 then
                  if v < 0x1EB7 then
                    v = 0x1EB5
                  else if 0x1EB7 < v then
                    False
                  else True
                else if 0x1EB9 < v then
                  v = 0x1EBB
                else True
              else True
            else if 0x1EBD < v then
              if v < 0x1EC7 then
                if v < 0x1EC3 then
                  if v < 0x1EC1 then
                    v = 0x1EBF
                  else if 0x1EC1 < v then
                    False
                  else True
                else if 0x1EC3 < v then
                  v = 0x1EC5
                else True
              else if 0x1EC7 < v then
                if v < 0x1ECD then
                  if v < 0x1ECB then
                    v = 0x1EC9
                  else if 0x1ECB < v then
                    False
                  else True
                else if 0x1ECD < v then
                  v = 0x1ECF
                else True
              else True
            else True
          else True
        else if 0x1ED1 < v then
          if v < 0x1EFB then
            if v < 0x1EE7 then
              if v < 0x1EDD then
                if v < 0x1ED7 then
                  if v < 0x1ED5 then
                    v = 0x1ED3
                  else if 0x1ED5 < v then
                    False
                  else True
                else if 0x1ED7 < v then
                  if v < 0x1EDB then
                    v = 0x1ED9
                  else if 0x1EDB < v then
                    False
                  else True
                else True
              else if 0x1EDD < v then
                if v < 0x1EE3 then
                  if v < 0x1EE1 then
                    v = 0x1EDF
                  else if 0x1EE1 < v then
                    False
                  else True
                else if 0x1EE3 < v then
                  v = 0x1EE5
                else True
              else True
            else if 0x1EE7 < v then
              if v < 0x1EF1 then
                if v < 0x1EED then
                  if v < 0x1EEB then
                    v = 0x1EE9
                  else if 0x1EEB < v then
                    False
                  else True
                else if 0x1EED < v then
                  v = 0x1EEF
                else True
              else if 0x1EF1 < v then
                if v < 0x1EF7 then
                  if v < 0x1EF5 then
                    v = 0x1EF3
                  else if 0x1EF5 < v then
                    False
                  else True
                else if 0x1EF7 < v then
                  v = 0x1EF9
                else True
              else True
            else True
          else if 0x1EFB < v then
            if v < 0x1F90 then
              if v < 0x1F40 then
                if v < 0x1F10 then
                  if v < 0x1EFF then
                    v = 0x1EFD
                  else if 0x1F07 < v then
                    False
                  else True
                else if 0x1F15 < v then
                  if v < 0x1F30 then
                    0x1F20 ≤ v ∧ v ≤ 0x1F27
                  else if 0x1F37 < v then
                    False
                  else True
                else True
              else if 0x1F45 < v then
                if v < 0x1F70 then
                  if v < 0x1F60 then
                    0x1F50 ≤ v ∧ v ≤ 0x1F57
                  else if 0x1F67 < v then
                    False
                  else True
                else if 0x1F7D < v then
                  0x1F80 ≤ v ∧ v ≤ 0x1F87
                else True
              else True
            else if 0x1F97 < v then
              if v < 0x1FC2 then
                if v < 0x1FB6 then
                  if v < 0x1FB0 then
                    0x1FA0 ≤ v ∧ v ≤ 0x1FA7
                  else if 0x1FB4 < v then
                    False
                  else True
                else if 0x1FB7 < v then
                  v = 0x1FBE
                else True
              else if 0x1FC4 < v then
                if v < 0x1FD6 then
                  if v < 0x1FD0 then
                    0x1FC6 ≤ v ∧ v ≤ 0x1FC7
                  else if 0x1FD3 < v then
                    False
                  else True
                else if 0x1FD7 < v then
                  0x1FE0 ≤ v ∧ v ≤ 0x1FE7
                else True
              else True
            else True
          else True
        else True
      else if 0x1FF4 < v then
        if v < 0x2CA3 then
          if v < 0x2C6C then
            if v < 0x213C then
              if v < 0x210E then
                if v < 0x207F then
                  if v < 0x2071 then
                    0x1FF6 ≤ v ∧ v ≤ 0x1FF7
                  else if 0x2071 < v then
                    False
                  else True
                else if 0x207F < v then
                  if v < 0x210A then
                    0x2090 ≤ v ∧ v ≤ 0x209C
                  else if 0x210A < v then
                    False
                  else True
                else True
              else if 0x210F < v then
                if v < 0x2134 then
                  if v < 0x212F then
                    v = 0x2113
                  else if 0x212F < v then
                    False
                  else True
                else if 0x2134 < v then
                  v = 0x2139
                else True
              else True
            else if 0x213D < v then
              if v < 0x2C30 then
                if v < 0x2170 then
                  if v < 0x214E then
                    0x2146 ≤ v ∧ v ≤ 0x2149
                  else if 0x214E < v then
                    False
                  else True
                else if 0x217F < v then
                  if v < 0x24D0 then
                    v = 0x2184
                  else if 0x24E9 < v then
                    False
                  else True
                else True
              else if 0x2C5F < v then
                if v < 0x2C68 then
                  if v < 0x2C65 then
                    v = 0x2C61
                  else if 0x2C66 < v then
                    False
                  else True
                else if 0x2C68 < v then
                  v = 0x2C6A
                else True
              else True
            else True
          else if 0x2C6C < v then
            if v < 0x2C8F then
              if v < 0x2C85 then
                if v < 0x2C76 then
                  if v < 0x2C73 then
                    v = 0x2C71
                  else if 0x2C74 < v then
                    False
                  else True
                else if 0x2C7D < v then
                  if v < 0x2C83 then
                    v = 0x2C81
                  else if 0x2C83 < v then
                    False
                  else True
                else True
              else if 0x2C85 < v then
                if v < 0x2C8B then
                  if v < 0x2C89 then
                    v = 0x2C87
                  else if 0x2C89 < v then
                    False
                  else True
                else if 0x2C8B < v then
                  v = 0x2C8D
                else True
              else True
            else if 0x2C8F < v then
              if v < 0x2C99 then
                if v < 0x2C95 then
                  if v < 0x2C93 then
                    v = 0x2C91
                  else if 0x2C93 < v then
                    False
                  else True
                else if 0x2C95 < v then
                  v = 0x2C97
                else True
              else if 0x2C99 < v then
                if v < 0x2C9F then
                  if v < 0x2C9D then
                    v = 0x2C9B
                  else if 0x2C9D < v then
                    False
                  else True
                else if 0x2C9F < v then
                  v = 0x2CA1
                else True
              else True
            else True
          else True
        else if 0x2CA3 < v then
          if v < 0x2CCD then
            if v < 0x2CB9 then
              if v < 0x2CAF then
                if v < 0x2CA9 then
                  if v < 0x2CA7 then
                    v = 0x2CA5
                  else if 0x2CA7 < v then
                    False
                  else True
                else if 0x2CA9 < v then
                  if v < 0x2CAD then
                    v = 0x2CAB
                  else if 0x2CAD < v then
                    False
                  else True
                else True
              else if 0x2CAF < v then
                if v < 0x2CB5 then
                  if v < 0x2CB3 then
                    v = 0x2CB1
                  else if 0x2CB3 < v then
                    False
                  else True
                else if 0x2CB5 < v then
                  v = 0x2CB7
                else True
              else True
            else if 0x2CB9 < v then
              if v < 0x2CC3 then
                if v < 0x2CBF then
                  if v < 0x2CBD then
                    v = 0x2CBB
                  else if 0x2CBD < v then
                    False
                  else True
                else if 0x2CBF < v then
                  v = 0x2CC1
                else True
              else if 0x2CC3 < v then
                if v < 0x2CC9 then
                  if v < 0x2CC7 then
                    v = 0x2CC5
                  else if 0x2CC7 < v then
                    False
                  else True
                else if 0x2CC9 < v then
                  v = 0x2CCB
                else True
              else True
            else True
          else if 0x2CCD < v then
            if v < 0x2CE3 then
              if v < 0x2CD9 then
                if v < 0x2CD3 then
                  if v < 0x2CD1 then
                    v = 0x2CCF
                  else if 0x2CD1 < v then
                    False
                  else True
                else if 0x2CD3 < v then
                  if v < 0x2CD7 then
                    v = 0x2CD5
                  else if 0x2CD7 < v then
                    False
                  else True
                else True
              else if 0x2CD9 < v then
                if v < 0x2CDF then
                  if v < 0x2CDD then
                    v = 0x2CDB
                  else if 0x2CDD < v then
                    False
                  else True
                else if 0x2CDF < v then
                  v = 0x2CE1
                else True
              else True
            else if 0x2CE4 < v then
              if v < 0x2D27 then
                if v < 0x2CF3 then
                  if v < 0x2CEE then
                    v = 0x2CEC
                  else if 0x2CEE < v then
                    False
                  else True
                else if 0x2CF3 < v then
                  0x2D00 ≤ v ∧ v ≤ 0x2D25
                else True
              else if 0x2D27 < v then
                if v < 0xA643 then
                  if v < 0xA641 then
                    v = 0x2D2D
                  else if 0xA641 < v then
                    False
                  else True
                else if 0xA643 < v then
                  v = 0xA645
                else True
              else True
            else True
          else True
        else True
      else True
    else if 0xA647 < v then
      if v < 0xA79B then
        if v < 0xA737 then
          if v < 0xA685 then
            if v < 0xA65D then
              if v < 0xA653 then
                if v < 0xA64D then
                  if v < 0xA64B then
                    v = 0xA649
                  else if 0xA64B < v then
                    False
                  else True
                else if 0xA64D < v then
                  if v < 0xA651 then
                    v = 0xA64F
                  else if 0xA651 < v then
                    False
                  else True
                else True
              else if 0xA653 < v then
                if v < 0xA659 then
                  if v < 0xA657 then
                    v = 0xA655
                  else if 0xA657 < v then
                    False
                  else True
                else if 0xA659 < v then
                  v = 0xA65B
                else True
              else True
            else if 0xA65D < v then
              if v < 0xA669 then
                if v < 0xA663 then
                  if v < 0xA661 then
                    v = 0xA65F
                  else if 0xA661 < v then
                    False
                  else True
                else if 0xA663 < v then
                  if v < 0xA667 then
                    v = 0xA665
                  else if 0xA667 < v then
                    False
                  else True
                else True
              else if 0xA669 < v then
                if v < 0xA681 then
                  if v < 0xA66D then
                    v = 0xA66B
                  else if 0xA66D < v then
                    False
                  else True
                else if 0xA681 < v then
                  v = 0xA683
                else True
              else True
            else True
          else if 0xA685 < v then
            if v < 0xA69B then
              if v < 0xA691 then
                if v < 0xA68B then
                  if v < 0xA689 then
                    v = 0xA687
                  else if 0xA689 < v then
                    False
                  else True
                else if 0xA68B < v then
                  if v < 0xA68F then
                    v = 0xA68D
                  else if 0xA68F < v then
                    False
                  else True
                else True
              else if 0xA691 < v then
                if v < 0xA697 then
                  if v < 0xA695 then
                    v = 0xA693
                  else if 0xA695 < v then
                    False
                  else True
                else if 0xA697 < v then
                  v = 0xA699
                else True
              else True
            else if 0xA69D < v then
              if v < 0xA72B then
                if v < 0xA727 then
                  if v < 0xA725 then
                    v = 0xA723
                  else if 0xA725 < v then
                    False
                  else True
                else if 0xA727 < v then
                  v = 0xA729
                else True
              else if 0xA72B < v then
                if v < 0xA733 then
                  if v < 0xA72F then
                    v = 0xA72D
                  else if 0xA731 < v then
                    False
                  else True
                else if 0xA733 < v then
                  v = 0xA735
                else True
              else True
            else True
          else True
        else if 0xA737 < v then
          if v < 0xA761 then
            if v < 0xA74D then
              if v < 0xA743 then
                if v < 0xA73D then
                  if v < 0xA73B then
                    v = 0xA739
                  else if 0xA73B < v then
                    False
                  else True
                else if 0xA73D < v then
                  if v < 0xA741 then
                    v = 0xA73F
                  else if 0xA741 < v then
                    False
                  else True
                else True
              else if 0xA743 < v then
                if v < 0xA749 then
                  if v < 0xA747 then
                    v = 0xA745
                  else if 0xA747 < v then
                    False
                  else True
                else if 0xA749 < v then
                  v = 0xA74B
                else True
              else True
            else if 0xA74D < v then
              if v < 0xA757 then
                if v < 0xA753 then
                  if v < 0xA751 then
                    v = 0xA74F
                  else if 0xA751 < v then
                    False
                  else True
                else if 0xA753 < v then
                  v = 0xA755
                else True
              else if 0xA757 < v then
                if v < 0xA75D then
                  if v < 0xA75B then
                    v = 0xA759
                  else if 0xA75B < v then
                    False
                  else True
                else if 0xA75D < v then
                  v = 0xA75F
                else True
              else True
            else True
          else if 0xA761 < v then
            if v < 0xA781 then
              if v < 0xA76D then
                if v < 0xA767 then
                  if v < 0xA765 then
                    v = 0xA763
                  else if 0xA765 < v then
                    False
                  else True
                else if 0xA767 < v then
                  if v < 0xA76B then
                    v = 0xA769
                  else if 0xA76B < v then
                    False
                  else True
                else True
              else if 0xA76D < v then
                if v < 0xA77C then
                  if v < 0xA77A then
                    0xA76F ≤ v ∧ v ≤ 0xA778
                  else if 0xA77A < v then
                    False
                  else True
                else if 0xA77C < v then
                  v = 0xA77F
                else True
              else True
            else if 0xA781 < v then
              if v < 0xA78E then
                if v < 0xA787 then
                  if v < 0xA785 then
                    v = 0xA783
                  else if 0xA785 < v then
                    False
                  else True
                else if 0xA787 < v then
                  v = 0xA78C
                else True
              else if 0xA78E < v then
                if v < 0xA797 then
                  if v < 0xA793 then
                    v = 0xA791
                  else if 0xA795 < v then
                    False
                  else True
                else if 0xA797 < v then
                  v = 0xA799
                else True
              else True
            else True
          else True
        else True
      else if 0xA79B < v then
        if v < 0x10780 then
          if v < 0xA7D1 then
            if v < 0xA7B9 then
              if v < 0xA7A7 then
                if v < 0xA7A1 then
                  if v < 0xA79F then
                    v = 0xA79D
                  else if 0xA79F < v then
                    False
                  else True
                else if 0xA7A1 < v then
                  if v < 0xA7A5 then
                    v = 0xA7A3
                  else if 0xA7A5 < v then
                    False
                  else True
                else True
              else if 0xA7A7 < v then
                if v < 0xA7B5 then
                  if v < 0xA7AF then
                    v = 0xA7A9
                  else if 0xA7AF < v then
                    False
                  else True
                else if 0xA7B5 < v then
                  v = 0xA7B7
                else True
              else True
            else if 0xA7B9 < v then
              if v < 0xA7C3 then
                if v < 0xA7BF then
                  if v < 0xA7BD then
                    v = 0xA7BB
                  else if 0xA7BD < v then
                    False
                  else True
                else if 0xA7BF < v then
                  v = 0xA7C1
                else True
              else if 0xA7C3 < v then
                if v < 0xA7CD then
                  if v < 0xA7CA then
                    v = 0xA7C8
                  else if 0xA7CA < v then
                    False
                  else True
                else if 0xA7CD < v then
                  v = 0xA7CF
                else True
              else True
            else True
          else if 0xA7D1 < v then
            if v < 0xAB70 then
              if v < 0xA7F1 then
                if v < 0xA7D7 then
                  if v < 0xA7D5 then
                    v = 0xA7D3
                  else if 0xA7D5 < v then
                    False
                  else True
                else if 0xA7D7 < v then
                  if v < 0xA7DB then
                    v = 0xA7D9
                  else if 0xA7DB < v then
                    False
                  else True
                else True
              else if 0xA7F4 < v then
                if v < 0xAB30 then
                  if v < 0xA7F8 then
                    v = 0xA7F6
                  else if 0xA7FA < v then
                    False
                  else True
                else if 0xAB5A < v then
                  0xAB5C ≤ v ∧ v ≤ 0xAB69
                else True
              else True
            else if 0xABBF < v then
              if v < 0x104D8 then
                if v < 0xFF41 then
                  if v < 0xFB13 then
                    0xFB00 ≤ v ∧ v ≤ 0xFB06
                  else if 0xFB17 < v then
                    False
                  else True
                else if 0xFF5A < v then
                  0x10428 ≤ v ∧ v ≤ 0x1044F
                else True
              else if 0x104FB < v then
                if v < 0x105B3 then
                  if v < 0x105A3 then
                    0x10597 ≤ v ∧ v ≤ 0x105A1
                  else if 0x105B1 < v then
                    False
                  else True
                else if 0x105B9 < v then
                  0x105BB ≤ v ∧ v ≤ 0x105BC
                else True
              else True
            else True
          else True
        else if 0x10780 < v then
          if v < 0x1D5BA then
            if v < 0x1D456 then
              if v < 0x118C0 then
                if v < 0x107B2 then
                  if v < 0x10787 then
                    0x10783 ≤ v ∧ v ≤ 0x10785
                  else if 0x107B0 < v then
                    False
                  else True
                else if 0x107BA < v then
                  if v < 0x10D70 then
                    0x10CC0 ≤ v ∧ v ≤ 0x10CF2
                  else if 0x10D85 < v then
                    False
                  else True
                else True
              else if 0x118DF < v then
                if v < 0x1D41A then
                  if v < 0x16EBB then
                    0x16E60 ≤ v ∧ v ≤ 0x16E7F
                  else if 0x16ED3 < v then
                    False
                  else True
                else if 0x1D433 < v then
                  0x1D44E ≤ v ∧ v ≤ 0x1D454
                else True
              else True
            else if 0x1D467 < v then
              if v < 0x1D4C5 then
                if v < 0x1D4BB then
                  if v < 0x1D4B6 then
                    0x1D482 ≤ v ∧ v ≤ 0x1D49B
                  else if 0x1D4B9 < v then
                    False
                  else True
                else if 0x1D4BB < v then
                  0x1D4BD ≤ v ∧ v ≤ 0x1D4C3
                else True
              else if 0x1D4CF < v then
                if v < 0x1D552 then
                  if v < 0x1D51E then
                    0x1D4EA ≤ v ∧ v ≤ 0x1D503
                  else if 0x1D537 < v then
                    False
                  else True
                else if 0x1D56B < v then
                  0x1D586 ≤ v ∧ v ≤ 0x1D59F
                else True
              else True
            else True
          else if 0x1D5D3 < v then
            if v < 0x1D770 then
              if v < 0x1D6DC then
                if v < 0x1D656 then
                  if v < 0x1D622 then
                    0x1D5EE ≤ v ∧ v ≤ 0x1D607
                  else if 0x1D63B < v then
                    False
                  else True
                else if 0x1D66F < v then
                  if v < 0x1D6C2 then
                    0x1D68A ≤ v ∧ v ≤ 0x1D6A5
                  else if 0x1D6DA < v then
                    False
                  else True
                else True
              else if 0x1D6E1 < v then
                if v < 0x1D736 then
                  if v < 0x1D716 then
                    0x1D6FC ≤ v ∧ v ≤ 0x1D714
                  else if 0x1D71B < v then
                    False
                  else True
                else if 0x1D74E < v then
                  0x1D750 ≤ v ∧ v ≤ 0x1D755
                else True
              else True
            else if 0x1D788 < v then
              if v < 0x1DF00 then
                if v < 0x1D7C4 then
                  if v < 0x1D7AA then
                    0x1D78A ≤ v ∧ v ≤ 0x1D78F
                  else if 0x1D7C2 < v then
                    False
                  else True
                else if 0x1D7C9 < v then
                  v = 0x1D7CB
                else True
              else if 0x1DF09 < v then
                if v < 0x1E030 then
                  if v < 0x1DF25 then
                    0x1DF0B ≤ v ∧ v ≤ 0x1DF1E
                  else if 0x1DF2A < v then
                    False
                  else True
                else if 0x1E06D < v then
                  0x1E922 ≤ v ∧ v ≤ 0x1E943
                else True
              else True
            else True
          else True
        else True
      else True
    else True
  else True

set_option synthInstance.maxSize 4096 in
instance (v : UInt32) (h : BetweenOrEqStartEnd v) : Decidable (IsInsideSparseRangeTable v h) := by
  unfold IsInsideSparseRangeTable; infer_instance

end Unicode.TableLookupTables.Lowercase
