/- This file is generated by table-generators/makeTablesForLookup. -/
module

@[expose] public section

namespace Unicode.TableLookupTables.QuotationMark

abbrev start : UInt32 := 0x0022

abbrev «end» : UInt32 := 0xFF63

abbrev BetweenOrEqStartEnd (v : UInt32) : Prop := start ≤ v ∧ v ≤ «end»

@[inline_if_reduce, reducible]
def IsInsideSparseRangeTable (v : UInt32) (_h : BetweenOrEqStartEnd v) : Prop :=
  if v < 0x300C then
    if v < 0x201B then
      if v < 0x00BB then
        if v < 0x0027 then
          v = 0x0022
        else if 0x0027 < v then
          v = 0x00AB
        else True
      else if 0x00BB < v then
        if v < 0x2019 then
          v = 0x2018
        else if 0x2019 < v then
          v = 0x201A
        else True
      else True
    else if 0x201C < v then
      if v < 0x2039 then
        if v < 0x201E then
          v = 0x201D
        else if 0x201E < v then
          v = 0x201F
        else True
      else if 0x2039 < v then
        if v < 0x2E42 then
          v = 0x203A
        else if 0x2E42 < v then
          False
        else True
      else True
    else True
  else if 0x300C < v then
    if v < 0xFE42 then
      if v < 0x301D then
        if v < 0x300E then
          v = 0x300D
        else if 0x300E < v then
          v = 0x300F
        else True
      else if 0x301D < v then
        if v < 0xFE41 then
          0x301E ≤ v ∧ v ≤ 0x301F
        else if 0xFE41 < v then
          False
        else True
      else True
    else if 0xFE42 < v then
      if v < 0xFF07 then
        if v < 0xFE44 then
          v = 0xFE43
        else if 0xFE44 < v then
          v = 0xFF02
        else True
      else if 0xFF07 < v then
        if v < 0xFF63 then
          v = 0xFF62
        else if 0xFF63 < v then
          False
        else True
      else True
    else True
  else True

set_option synthInstance.maxSize 4096 in
instance (v : UInt32) (h : BetweenOrEqStartEnd v) : Decidable (IsInsideSparseRangeTable v h) := by
  unfold IsInsideSparseRangeTable; infer_instance

end Unicode.TableLookupTables.QuotationMark
