/- This file is generated by table-generators/makeTablesForLookup. -/
module

@[expose] public section

namespace Unicode.TableLookupTables.Uppercase

abbrev start : UInt32 := 0x0041

abbrev «end» : UInt32 := 0x1F189

abbrev BetweenOrEqStartEnd (v : UInt32) : Prop := start ≤ v ∧ v ≤ «end»

@[inline_if_reduce, reducible]
def IsInsideSparseRangeTable (v : UInt32) (_h : BetweenOrEqStartEnd v) : Prop :=
  if v < 0x1E66 then
    if v < 0x03EA then
      if v < 0x01B7 then
        if v < 0x014E then
          if v < 0x0122 then
            if v < 0x010E then
              if v < 0x0104 then
                if v < 0x00D8 then
                  if v < 0x00C0 then
                    0x0041 ≤ v ∧ v ≤ 0x005A
                  else if 0x00D6 < v then
                    False
                  else True
                else if 0x00DE < v then
                  if v < 0x0102 then
                    v = 0x0100
                  else if 0x0102 < v then
                    False
                  else True
                else True
              else if 0x0104 < v then
                if v < 0x010A then
                  if v < 0x0108 then
                    v = 0x0106
                  else if 0x0108 < v then
                    False
                  else True
                else if 0x010A < v then
                  v = 0x010C
                else True
              else True
            else if 0x010E < v then
              if v < 0x0118 then
                if v < 0x0114 then
                  if v < 0x0112 then
                    v = 0x0110
                  else if 0x0112 < v then
                    False
                  else True
                else if 0x0114 < v then
                  v = 0x0116
                else True
              else if 0x0118 < v then
                if v < 0x011E then
                  if v < 0x011C then
                    v = 0x011A
                  else if 0x011C < v then
                    False
                  else True
                else if 0x011E < v then
                  v = 0x0120
                else True
              else True
            else True
          else if 0x0122 < v then
            if v < 0x0139 then
              if v < 0x012E then
                if v < 0x0128 then
                  if v < 0x0126 then
                    v = 0x0124
                  else if 0x0126 < v then
                    False
                  else True
                else if 0x0128 < v then
                  if v < 0x012C then
                    v = 0x012A
                  else if 0x012C < v then
                    False
                  else True
                else True
              else if 0x012E < v then
                if v < 0x0134 then
                  if v < 0x0132 then
                    v = 0x0130
                  else if 0x0132 < v then
                    False
                  else True
                else if 0x0134 < v then
                  v = 0x0136
                else True
              else True
            else if 0x0139 < v then
              if v < 0x0143 then
                if v < 0x013F then
                  if v < 0x013D then
                    v = 0x013B
                  else if 0x013D < v then
                    False
                  else True
                else if 0x013F < v then
                  v = 0x0141
                else True
              else if 0x0143 < v then
                if v < 0x014A then
                  if v < 0x0147 then
                    v = 0x0145
                  else if 0x0147 < v then
                    False
                  else True
                else if 0x014A < v then
                  v = 0x014C
                else True
              else True
            else True
          else True
        else if 0x014E < v then
          if v < 0x0178 then
            if v < 0x0164 then
              if v < 0x015A then
                if v < 0x0154 then
                  if v < 0x0152 then
                    v = 0x0150
                  else if 0x0152 < v then
                    False
                  else True
                else if 0x0154 < v then
                  if v < 0x0158 then
                    v = 0x0156
                  else if 0x0158 < v then
                    False
                  else True
                else True
              else if 0x015A < v then
                if v < 0x0160 then
                  if v < 0x015E then
                    v = 0x015C
                  else if 0x015E < v then
                    False
                  else True
                else if 0x0160 < v then
                  v = 0x0162
                else True
              else True
            else if 0x0164 < v then
              if v < 0x016E then
                if v < 0x016A then
                  if v < 0x0168 then
                    v = 0x0166
                  else if 0x0168 < v then
                    False
                  else True
                else if 0x016A < v then
                  v = 0x016C
                else True
              else if 0x016E < v then
                if v < 0x0174 then
                  if v < 0x0172 then
                    v = 0x0170
                  else if 0x0172 < v then
                    False
                  else True
                else if 0x0174 < v then
                  v = 0x0176
                else True
              else True
            else True
          else if 0x0179 < v then
            if v < 0x019C then
              if v < 0x0186 then
                if v < 0x0181 then
                  if v < 0x017D then
                    v = 0x017B
                  else if 0x017D < v then
                    False
                  else True
                else if 0x0182 < v then
                  v = 0x0184
                else True
              else if 0x0187 < v then
                if v < 0x0193 then
                  if v < 0x018E then
                    0x0189 ≤ v ∧ v ≤ 0x018B
                  else if 0x0191 < v then
                    False
                  else True
                else if 0x0194 < v then
                  0x0196 ≤ v ∧ v ≤ 0x0198
                else True
              else True
            else if 0x019D < v then
              if v < 0x01A9 then
                if v < 0x01A4 then
                  if v < 0x01A2 then
                    0x019F ≤ v ∧ v ≤ 0x01A0
                  else if 0x01A2 < v then
                    False
                  else True
                else if 0x01A4 < v then
                  0x01A6 ≤ v ∧ v ≤ 0x01A7
                else True
              else if 0x01A9 < v then
                if v < 0x01B1 then
                  if v < 0x01AE then
                    v = 0x01AC
                  else if 0x01AF < v then
                    False
                  else True
                else if 0x01B3 < v then
                  v = 0x01B5
                else True
              else True
            else True
          else True
        else True
      else if 0x01B8 < v then
        if v < 0x021C then
          if v < 0x01EE then
            if v < 0x01D9 then
              if v < 0x01CF then
                if v < 0x01C7 then
                  if v < 0x01C4 then
                    v = 0x01BC
                  else if 0x01C4 < v then
                    False
                  else True
                else if 0x01C7 < v then
                  if v < 0x01CD then
                    v = 0x01CA
                  else if 0x01CD < v then
                    False
                  else True
                else True
              else if 0x01CF < v then
                if v < 0x01D5 then
                  if v < 0x01D3 then
                    v = 0x01D1
                  else if 0x01D3 < v then
                    False
                  else True
                else if 0x01D5 < v then
                  v = 0x01D7
                else True
              else True
            else if 0x01D9 < v then
              if v < 0x01E4 then
                if v < 0x01E0 then
                  if v < 0x01DE then
                    v = 0x01DB
                  else if 0x01DE < v then
                    False
                  else True
                else if 0x01E0 < v then
                  v = 0x01E2
                else True
              else if 0x01E4 < v then
                if v < 0x01EA then
                  if v < 0x01E8 then
                    v = 0x01E6
                  else if 0x01E8 < v then
                    False
                  else True
                else if 0x01EA < v then
                  v = 0x01EC
                else True
              else True
            else True
          else if 0x01EE < v then
            if v < 0x0208 then
              if v < 0x01FE then
                if v < 0x01F6 then
                  if v < 0x01F4 then
                    v = 0x01F1
                  else if 0x01F4 < v then
                    False
                  else True
                else if 0x01F8 < v then
                  if v < 0x01FC then
                    v = 0x01FA
                  else if 0x01FC < v then
                    False
                  else True
                else True
              else if 0x01FE < v then
                if v < 0x0204 then
                  if v < 0x0202 then
                    v = 0x0200
                  else if 0x0202 < v then
                    False
                  else True
                else if 0x0204 < v then
                  v = 0x0206
                else True
              else True
            else if 0x0208 < v then
              if v < 0x0212 then
                if v < 0x020E then
                  if v < 0x020C then
                    v = 0x020A
                  else if 0x020C < v then
                    False
                  else True
                else if 0x020E < v then
                  v = 0x0210
                else True
              else if 0x0212 < v then
                if v < 0x0218 then
                  if v < 0x0216 then
                    v = 0x0214
                  else if 0x0216 < v then
                    False
                  else True
                else if 0x0218 < v then
                  v = 0x021A
                else True
              else True
            else True
          else True
        else if 0x021C < v then
          if v < 0x0372 then
            if v < 0x0232 then
              if v < 0x0228 then
                if v < 0x0222 then
                  if v < 0x0220 then
                    v = 0x021E
                  else if 0x0220 < v then
                    False
                  else True
                else if 0x0222 < v then
                  if v < 0x0226 then
                    v = 0x0224
                  else if 0x0226 < v then
                    False
                  else True
                else True
              else if 0x0228 < v then
                if v < 0x022E then
                  if v < 0x022C then
                    v = 0x022A
                  else if 0x022C < v then
                    False
                  else True
                else if 0x022E < v then
                  v = 0x0230
                else True
              else True
            else if 0x0232 < v then
              if v < 0x0248 then
                if v < 0x0241 then
                  if v < 0x023D then
                    0x023A ≤ v ∧ v ≤ 0x023B
                  else if 0x023E < v then
                    False
                  else True
                else if 0x0241 < v then
                  0x0243 ≤ v ∧ v ≤ 0x0246
                else True
              else if 0x0248 < v then
                if v < 0x024E then
                  if v < 0x024C then
                    v = 0x024A
                  else if 0x024C < v then
                    False
                  else True
                else if 0x024E < v then
                  v = 0x0370
                else True
              else True
            else True
          else if 0x0372 < v then
            if v < 0x03D2 then
              if v < 0x038C then
                if v < 0x0386 then
                  if v < 0x037F then
                    v = 0x0376
                  else if 0x037F < v then
                    False
                  else True
                else if 0x0386 < v then
                  0x0388 ≤ v ∧ v ≤ 0x038A
                else True
              else if 0x038C < v then
                if v < 0x03A3 then
                  if v < 0x0391 then
                    0x038E ≤ v ∧ v ≤ 0x038F
                  else if 0x03A1 < v then
                    False
                  else True
                else if 0x03AB < v then
                  v = 0x03CF
                else True
              else True
            else if 0x03D4 < v then
              if v < 0x03E0 then
                if v < 0x03DC then
                  if v < 0x03DA then
                    v = 0x03D8
                  else if 0x03DA < v then
                    False
                  else True
                else if 0x03DC < v then
                  v = 0x03DE
                else True
              else if 0x03E0 < v then
                if v < 0x03E6 then
                  if v < 0x03E4 then
                    v = 0x03E2
                  else if 0x03E4 < v then
                    False
                  else True
                else if 0x03E6 < v then
                  v = 0x03E8
                else True
              else True
            else True
          else True
        else True
      else True
    else if 0x03EA < v then
      if v < 0x0502 then
        if v < 0x04AE then
          if v < 0x047C then
            if v < 0x0468 then
              if v < 0x03FD then
                if v < 0x03F4 then
                  if v < 0x03EE then
                    v = 0x03EC
                  else if 0x03EE < v then
                    False
                  else True
                else if 0x03F4 < v then
                  if v < 0x03F9 then
                    v = 0x03F7
                  else if 0x03FA < v then
                    False
                  else True
                else True
              else if 0x042F < v then
                if v < 0x0464 then
                  if v < 0x0462 then
                    v = 0x0460
                  else if 0x0462 < v then
                    False
                  else True
                else if 0x0464 < v then
                  v = 0x0466
                else True
              else True
            else if 0x0468 < v then
              if v < 0x0472 then
                if v < 0x046E then
                  if v < 0x046C then
                    v = 0x046A
                  else if 0x046C < v then
                    False
                  else True
                else if 0x046E < v then
                  v = 0x0470
                else True
              else if 0x0472 < v then
                if v < 0x0478 then
                  if v < 0x0476 then
                    v = 0x0474
                  else if 0x0476 < v then
                    False
                  else True
                else if 0x0478 < v then
                  v = 0x047A
                else True
              else True
            else True
          else if 0x047C < v then
            if v < 0x049A then
              if v < 0x0490 then
                if v < 0x048A then
                  if v < 0x0480 then
                    v = 0x047E
                  else if 0x0480 < v then
                    False
                  else True
                else if 0x048A < v then
                  if v < 0x048E then
                    v = 0x048C
                  else if 0x048E < v then
                    False
                  else True
                else True
              else if 0x0490 < v then
                if v < 0x0496 then
                  if v < 0x0494 then
                    v = 0x0492
                  else if 0x0494 < v then
                    False
                  else True
                else if 0x0496 < v then
                  v = 0x0498
                else True
              else True
            else if 0x049A < v then
              if v < 0x04A4 then
                if v < 0x04A0 then
                  if v < 0x049E then
                    v = 0x049C
                  else if 0x049E < v then
                    False
                  else True
                else if 0x04A0 < v then
                  v = 0x04A2
                else True
              else if 0x04A4 < v then
                if v < 0x04AA then
                  if v < 0x04A8 then
                    v = 0x04A6
                  else if 0x04A8 < v then
                    False
                  else True
                else if 0x04AA < v then
                  v = 0x04AC
                else True
              else True
            else True
          else True
        else if 0x04AE < v then
          if v < 0x04DA then
            if v < 0x04C5 then
              if v < 0x04BA then
                if v < 0x04B4 then
                  if v < 0x04B2 then
                    v = 0x04B0
                  else if 0x04B2 < v then
                    False
                  else True
                else if 0x04B4 < v then
                  if v < 0x04B8 then
                    v = 0x04B6
                  else if 0x04B8 < v then
                    False
                  else True
                else True
              else if 0x04BA < v then
                if v < 0x04C0 then
                  if v < 0x04BE then
                    v = 0x04BC
                  else if 0x04BE < v then
                    False
                  else True
                else if 0x04C1 < v then
                  v = 0x04C3
                else True
              else True
            else if 0x04C5 < v then
              if v < 0x04D0 then
                if v < 0x04CB then
                  if v < 0x04C9 then
                    v = 0x04C7
                  else if 0x04C9 < v then
                    False
                  else True
                else if 0x04CB < v then
                  v = 0x04CD
                else True
              else if 0x04D0 < v then
                if v < 0x04D6 then
                  if v < 0x04D4 then
                    v = 0x04D2
                  else if 0x04D4 < v then
                    False
                  else True
                else if 0x04D6 < v then
                  v = 0x04D8
                else True
              else True
            else True
          else if 0x04DA < v then
            if v < 0x04EE then
              if v < 0x04E4 then
                if v < 0x04E0 then
                  if v < 0x04DE then
                    v = 0x04DC
                  else if 0x04DE < v then
                    False
                  else True
                else if 0x04E0 < v then
                  v = 0x04E2
                else True
              else if 0x04E4 < v then
                if v < 0x04EA then
                  if v < 0x04E8 then
                    v = 0x04E6
                  else if 0x04E8 < v then
                    False
                  else True
                else if 0x04EA < v then
                  v = 0x04EC
                else True
              else True
            else if 0x04EE < v then
              if v < 0x04F8 then
                if v < 0x04F4 then
                  if v < 0x04F2 then
                    v = 0x04F0
                  else if 0x04F2 < v then
                    False
                  else True
                else if 0x04F4 < v then
                  v = 0x04F6
                else True
              else if 0x04F8 < v then
                if v < 0x04FE then
                  if v < 0x04FC then
                    v = 0x04FA
                  else if 0x04FC < v then
                    False
                  else True
                else if 0x04FE < v then
                  v = 0x0500
                else True
              else True
            else True
          else True
        else True
      else if 0x0502 < v then
        if v < 0x1E14 then
          if v < 0x052C then
            if v < 0x0518 then
              if v < 0x050E then
                if v < 0x0508 then
                  if v < 0x0506 then
                    v = 0x0504
                  else if 0x0506 < v then
                    False
                  else True
                else if 0x0508 < v then
                  if v < 0x050C then
                    v = 0x050A
                  else if 0x050C < v then
                    False
                  else True
                else True
              else if 0x050E < v then
                if v < 0x0514 then
                  if v < 0x0512 then
                    v = 0x0510
                  else if 0x0512 < v then
                    False
                  else True
                else if 0x0514 < v then
                  v = 0x0516
                else True
              else True
            else if 0x0518 < v then
              if v < 0x0522 then
                if v < 0x051E then
                  if v < 0x051C then
                    v = 0x051A
                  else if 0x051C < v then
                    False
                  else True
                else if 0x051E < v then
                  v = 0x0520
                else True
              else if 0x0522 < v then
                if v < 0x0528 then
                  if v < 0x0526 then
                    v = 0x0524
                  else if 0x0526 < v then
                    False
                  else True
                else if 0x0528 < v then
                  v = 0x052A
                else True
              else True
            else True
          else if 0x052C < v then
            if v < 0x1E00 then
              if v < 0x10CD then
                if v < 0x10A0 then
                  if v < 0x0531 then
                    v = 0x052E
                  else if 0x0556 < v then
                    False
                  else True
                else if 0x10C5 < v then
                  v = 0x10C7
                else True
              else if 0x10CD < v then
                if v < 0x1C90 then
                  if v < 0x1C89 then
                    0x13A0 ≤ v ∧ v ≤ 0x13F5
                  else if 0x1C89 < v then
                    False
                  else True
                else if 0x1CBA < v then
                  0x1CBD ≤ v ∧ v ≤ 0x1CBF
                else True
              else True
            else if 0x1E00 < v then
              if v < 0x1E0A then
                if v < 0x1E06 then
                  if v < 0x1E04 then
                    v = 0x1E02
                  else if 0x1E04 < v then
                    False
                  else True
                else if 0x1E06 < v then
                  v = 0x1E08
                else True
              else if 0x1E0A < v then
                if v < 0x1E10 then
                  if v < 0x1E0E then
                    v = 0x1E0C
                  else if 0x1E0E < v then
                    False
                  else True
                else if 0x1E10 < v then
                  v = 0x1E12
                else True
              else True
            else True
          else True
        else if 0x1E14 < v then
          if v < 0x1E3E then
            if v < 0x1E2A then
              if v < 0x1E20 then
                if v < 0x1E1A then
                  if v < 0x1E18 then
                    v = 0x1E16
                  else if 0x1E18 < v then
                    False
                  else True
                else if 0x1E1A < v then
                  if v < 0x1E1E then
                    v = 0x1E1C
                  else if 0x1E1E < v then
                    False
                  else True
                else True
              else if 0x1E20 < v then
                if v < 0x1E26 then
                  if v < 0x1E24 then
                    v = 0x1E22
                  else if 0x1E24 < v then
                    False
                  else True
                else if 0x1E26 < v then
                  v = 0x1E28
                else True
              else True
            else if 0x1E2A < v then
              if v < 0x1E34 then
                if v < 0x1E30 then
                  if v < 0x1E2E then
                    v = 0x1E2C
                  else if 0x1E2E < v then
                    False
                  else True
                else if 0x1E30 < v then
                  v = 0x1E32
                else True
              else if 0x1E34 < v then
                if v < 0x1E3A then
                  if v < 0x1E38 then
                    v = 0x1E36
                  else if 0x1E38 < v then
                    False
                  else True
                else if 0x1E3A < v then
                  v = 0x1E3C
                else True
              else True
            else True
          else if 0x1E3E < v then
            if v < 0x1E52 then
              if v < 0x1E48 then
                if v < 0x1E44 then
                  if v < 0x1E42 then
                    v = 0x1E40
                  else if 0x1E42 < v then
                    False
                  else True
                else if 0x1E44 < v then
                  v = 0x1E46
                else True
              else if 0x1E48 < v then
                if v < 0x1E4E then
                  if v < 0x1E4C then
                    v = 0x1E4A
                  else if 0x1E4C < v then
                    False
                  else True
                else if 0x1E4E < v then
                  v = 0x1E50
                else True
              else True
            else if 0x1E52 < v then
              if v < 0x1E5C then
                if v < 0x1E58 then
                  if v < 0x1E56 then
                    v = 0x1E54
                  else if 0x1E56 < v then
                    False
                  else True
                else if 0x1E58 < v then
                  v = 0x1E5A
                else True
              else if 0x1E5C < v then
                if v < 0x1E62 then
                  if v < 0x1E60 then
                    v = 0x1E5E
                  else if 0x1E60 < v then
                    False
                  else True
                else if 0x1E62 < v then
                  v = 0x1E64
                else True
              else True
            else True
          else True
        else True
      else True
    else True
  else if 0x1E66 < v then
    if v < 0x2CF2 then
      if v < 0x1FB8 then
        if v < 0x1EC2 then
          if v < 0x1E90 then
            if v < 0x1E7C then
              if v < 0x1E72 then
                if v < 0x1E6C then
                  if v < 0x1E6A then
                    v = 0x1E68
                  else if 0x1E6A < v then
                    False
                  else True
                else if 0x1E6C < v then
                  if v < 0x1E70 then
                    v = 0x1E6E
                  else if 0x1E70 < v then
                    False
                  else True
                else True
              else if 0x1E72 < v then
                if v < 0x1E78 then
                  if v < 0x1E76 then
                    v = 0x1E74
                  else if 0x1E76 < v then
                    False
                  else True
                else if 0x1E78 < v then
                  v = 0x1E7A
                else True
              else True
            else if 0x1E7C < v then
              if v < 0x1E86 then
                if v < 0x1E82 then
                  if v < 0x1E80 then
                    v = 0x1E7E
                  else if 0x1E80 < v then
                    False
                  else True
                else if 0x1E82 < v then
                  v = 0x1E84
                else True
              else if 0x1E86 < v then
                if v < 0x1E8C then
                  if v < 0x1E8A then
                    v = 0x1E88
                  else if 0x1E8A < v then
                    False
                  else True
                else if 0x1E8C < v then
                  v = 0x1E8E
                else True
              else True
            else True
          else if 0x1E90 < v then
            if v < 0x1EAE then
              if v < 0x1EA4 then
                if v < 0x1E9E then
                  if v < 0x1E94 then
                    v = 0x1E92
                  else if 0x1E94 < v then
                    False
                  else True
                else if 0x1E9E < v then
                  if v < 0x1EA2 then
                    v = 0x1EA0
                  else if 0x1EA2 < v then
                    False
                  else True
                else True
              else if 0x1EA4 < v then
                if v < 0x1EAA then
                  if v < 0x1EA8 then
                    v = 0x1EA6
                  else if 0x1EA8 < v then
                    False
                  else True
                else if 0x1EAA < v then
                  v = 0x1EAC
                else True
              else True
            else if 0x1EAE < v then
              if v < 0x1EB8 then
                if v < 0x1EB4 then
                  if v < 0x1EB2 then
                    v = 0x1EB0
                  else if 0x1EB2 < v then
                    False
                  else True
                else if 0x1EB4 < v then
                  v = 0x1EB6
                else True
              else if 0x1EB8 < v then
                if v < 0x1EBE then
                  if v < 0x1EBC then
                    v = 0x1EBA
                  else if 0x1EBC < v then
                    False
                  else True
                else if 0x1EBE < v then
                  v = 0x1EC0
                else True
              else True
            else True
          else True
        else if 0x1EC2 < v then
          if v < 0x1EEC then
            if v < 0x1ED8 then
              if v < 0x1ECE then
                if v < 0x1EC8 then
                  if v < 0x1EC6 then
                    v = 0x1EC4
                  else if 0x1EC6 < v then
                    False
                  else True
                else if 0x1EC8 < v then
                  if v < 0x1ECC then
                    v = 0x1ECA
                  else if 0x1ECC < v then
                    False
                  else True
                else True
              else if 0x1ECE < v then
                if v < 0x1ED4 then
                  if v < 0x1ED2 then
                    v = 0x1ED0
                  else if 0x1ED2 < v then
                    False
                  else True
                else if 0x1ED4 < v then
                  v = 0x1ED6
                else True
              else True
            else if 0x1ED8 < v then
              if v < 0x1EE2 then
                if v < 0x1EDE then
                  if v < 0x1EDC then
                    v = 0x1EDA
                  else if 0x1EDC < v then
                    False
                  else True
                else if 0x1EDE < v then
                  v = 0x1EE0
                else True
              else if 0x1EE2 < v then
                if v < 0x1EE8 then
                  if v < 0x1EE6 then
                    v = 0x1EE4
                  else if 0x1EE6 < v then
                    False
                  else True
                else if 0x1EE8 < v then
                  v = 0x1EEA
                else True
              else True
            else True
          else if 0x1EEC < v then
            if v < 0x1F08 then
              if v < 0x1EF6 then
                if v < 0x1EF2 then
                  if v < 0x1EF0 then
                    v = 0x1EEE
                  else if 0x1EF0 < v then
                    False
                  else True
                else if 0x1EF2 < v then
                  v = 0x1EF4
                else True
              else if 0x1EF6 < v then
                if v < 0x1EFC then
                  if v < 0x1EFA then
                    v = 0x1EF8
                  else if 0x1EFA < v then
                    False
                  else True
                else if 0x1EFC < v then
                  v = 0x1EFE
                else True
              else True
            else if 0x1F0F < v then
              if v < 0x1F59 then
                if v < 0x1F38 then
                  if v < 0x1F28 then
                    0x1F18 ≤ v ∧ v ≤ 0x1F1D
                  else if 0x1F2F < v then
                    False
                  else True
                else if 0x1F3F < v then
                  0x1F48 ≤ v ∧ v ≤ 0x1F4D
                else True
              else if 0x1F59 < v then
                if v < 0x1F5F then
                  if v < 0x1F5D then
                    v = 0x1F5B
                  else if 0x1F5D < v then
                    False
                  else True
                else if 0x1F5F < v then
                  0x1F68 ≤ v ∧ v ≤ 0x1F6F
                else True
              else True
            else True
          else True
        else True
      else if 0x1FBB < v then
        if v < 0x2C96 then
          if v < 0x2C00 then
            if v < 0x2124 then
              if v < 0x2107 then
                if v < 0x1FE8 then
                  if v < 0x1FD8 then
                    0x1FC8 ≤ v ∧ v ≤ 0x1FCB
                  else if 0x1FDB < v then
                    False
                  else True
                else if 0x1FEC < v then
                  if v < 0x2102 then
                    0x1FF8 ≤ v ∧ v ≤ 0x1FFB
                  else if 0x2102 < v then
                    False
                  else True
                else True
              else if 0x2107 < v then
                if v < 0x2115 then
                  if v < 0x2110 then
                    0x210B ≤ v ∧ v ≤ 0x210D
                  else if 0x2112 < v then
                    False
                  else True
                else if 0x2115 < v then
                  0x2119 ≤ v ∧ v ≤ 0x211D
                else True
              else True
            else if 0x2124 < v then
              if v < 0x213E then
                if v < 0x212A then
                  if v < 0x2128 then
                    v = 0x2126
                  else if 0x2128 < v then
                    False
                  else True
                else if 0x212D < v then
                  0x2130 ≤ v ∧ v ≤ 0x2133
                else True
              else if 0x213F < v then
                if v < 0x2183 then
                  if v < 0x2160 then
                    v = 0x2145
                  else if 0x216F < v then
                    False
                  else True
                else if 0x2183 < v then
                  0x24B6 ≤ v ∧ v ≤ 0x24CF
                else True
              else True
            else True
          else if 0x2C2F < v then
            if v < 0x2C82 then
              if v < 0x2C6B then
                if v < 0x2C67 then
                  if v < 0x2C62 then
                    v = 0x2C60
                  else if 0x2C64 < v then
                    False
                  else True
                else if 0x2C67 < v then
                  v = 0x2C69
                else True
              else if 0x2C6B < v then
                if v < 0x2C75 then
                  if v < 0x2C72 then
                    0x2C6D ≤ v ∧ v ≤ 0x2C70
                  else if 0x2C72 < v then
                    False
                  else True
                else if 0x2C75 < v then
                  0x2C7E ≤ v ∧ v ≤ 0x2C80
                else True
              else True
            else if 0x2C82 < v then
              if v < 0x2C8C then
                if v < 0x2C88 then
                  if v < 0x2C86 then
                    v = 0x2C84
                  else if 0x2C86 < v then
                    False
                  else True
                else if 0x2C88 < v then
                  v = 0x2C8A
                else True
              else if 0x2C8C < v then
                if v < 0x2C92 then
                  if v < 0x2C90 then
                    v = 0x2C8E
                  else if 0x2C90 < v then
                    False
                  else True
                else if 0x2C92 < v then
                  v = 0x2C94
                else True
              else True
            else True
          else True
        else if 0x2C96 < v then
          if v < 0x2CC0 then
            if v < 0x2CAC then
              if v < 0x2CA2 then
                if v < 0x2C9C then
                  if v < 0x2C9A then
                    v = 0x2C98
                  else if 0x2C9A < v then
                    False
                  else True
                else if 0x2C9C < v then
                  if v < 0x2CA0 then
                    v = 0x2C9E
                  else if 0x2CA0 < v then
                    False
                  else True
                else True
              else if 0x2CA2 < v then
                if v < 0x2CA8 then
                  if v < 0x2CA6 then
                    v = 0x2CA4
                  else if 0x2CA6 < v then
                    False
                  else True
                else if 0x2CA8 < v then
                  v = 0x2CAA
                else True
              else True
            else if 0x2CAC < v then
              if v < 0x2CB6 then
                if v < 0x2CB2 then
                  if v < 0x2CB0 then
                    v = 0x2CAE
                  else if 0x2CB0 < v then
                    False
                  else True
                else if 0x2CB2 < v then
                  v = 0x2CB4
                else True
              else if 0x2CB6 < v then
                if v < 0x2CBC then
                  if v < 0x2CBA then
                    v = 0x2CB8
                  else if 0x2CBA < v then
                    False
                  else True
                else if 0x2CBC < v then
                  v = 0x2CBE
                else True
              else True
            else True
          else if 0x2CC0 < v then
            if v < 0x2CD4 then
              if v < 0x2CCA then
                if v < 0x2CC6 then
                  if v < 0x2CC4 then
                    v = 0x2CC2
                  else if 0x2CC4 < v then
                    False
                  else True
                else if 0x2CC6 < v then
                  v = 0x2CC8
                else True
              else if 0x2CCA < v then
                if v < 0x2CD0 then
                  if v < 0x2CCE then
                    v = 0x2CCC
                  else if 0x2CCE < v then
                    False
                  else True
                else if 0x2CD0 < v then
                  v = 0x2CD2
                else True
              else True
            else if 0x2CD4 < v then
              if v < 0x2CDE then
                if v < 0x2CDA then
                  if v < 0x2CD8 then
                    v = 0x2CD6
                  else if 0x2CD8 < v then
                    False
                  else True
                else if 0x2CDA < v then
                  v = 0x2CDC
                else True
              else if 0x2CDE < v then
                if v < 0x2CEB then
                  if v < 0x2CE2 then
                    v = 0x2CE0
                  else if 0x2CE2 < v then
                    False
                  else True
                else if 0x2CEB < v then
                  v = 0x2CED
                else True
              else True
            else True
          else True
        else True
      else True
    else if 0x2CF2 < v then
      if v < 0xA78B then
        if v < 0xA72A then
          if v < 0xA668 then
            if v < 0xA654 then
              if v < 0xA64A then
                if v < 0xA644 then
                  if v < 0xA642 then
                    v = 0xA640
                  else if 0xA642 < v then
                    False
                  else True
                else if 0xA644 < v then
                  if v < 0xA648 then
                    v = 0xA646
                  else if 0xA648 < v then
                    False
                  else True
                else True
              else if 0xA64A < v then
                if v < 0xA650 then
                  if v < 0xA64E then
                    v = 0xA64C
                  else if 0xA64E < v then
                    False
                  else True
                else if 0xA650 < v then
                  v = 0xA652
                else True
              else True
            else if 0xA654 < v then
              if v < 0xA65E then
                if v < 0xA65A then
                  if v < 0xA658 then
                    v = 0xA656
                  else if 0xA658 < v then
                    False
                  else True
                else if 0xA65A < v then
                  v = 0xA65C
                else True
              else if 0xA65E < v then
                if v < 0xA664 then
                  if v < 0xA662 then
                    v = 0xA660
                  else if 0xA662 < v then
                    False
                  else True
                else if 0xA664 < v then
                  v = 0xA666
                else True
              else True
            else True
          else if 0xA668 < v then
            if v < 0xA690 then
              if v < 0xA686 then
                if v < 0xA680 then
                  if v < 0xA66C then
                    v = 0xA66A
                  else if 0xA66C < v then
                    False
                  else True
                else if 0xA680 < v then
                  if v < 0xA684 then
                    v = 0xA682
                  else if 0xA684 < v then
                    False
                  else True
                else True
              else if 0xA686 < v then
                if v < 0xA68C then
                  if v < 0xA68A then
                    v = 0xA688
                  else if 0xA68A < v then
                    False
                  else True
                else if 0xA68C < v then
                  v = 0xA68E
                else True
              else True
            else if 0xA690 < v then
              if v < 0xA69A then
                if v < 0xA696 then
                  if v < 0xA694 then
                    v = 0xA692
                  else if 0xA694 < v then
                    False
                  else True
                else if 0xA696 < v then
                  v = 0xA698
                else True
              else if 0xA69A < v then
                if v < 0xA726 then
                  if v < 0xA724 then
                    v = 0xA722
                  else if 0xA724 < v then
                    False
                  else True
                else if 0xA726 < v then
                  v = 0xA728
                else True
              else True
            else True
          else True
        else if 0xA72A < v then
          if v < 0xA756 then
            if v < 0xA742 then
              if v < 0xA738 then
                if v < 0xA732 then
                  if v < 0xA72E then
                    v = 0xA72C
                  else if 0xA72E < v then
                    False
                  else True
                else if 0xA732 < v then
                  if v < 0xA736 then
                    v = 0xA734
                  else if 0xA736 < v then
                    False
                  else True
                else True
              else if 0xA738 < v then
                if v < 0xA73E then
                  if v < 0xA73C then
                    v = 0xA73A
                  else if 0xA73C < v then
                    False
                  else True
                else if 0xA73E < v then
                  v = 0xA740
                else True
              else True
            else if 0xA742 < v then
              if v < 0xA74C then
                if v < 0xA748 then
                  if v < 0xA746 then
                    v = 0xA744
                  else if 0xA746 < v then
                    False
                  else True
                else if 0xA748 < v then
                  v = 0xA74A
                else True
              else if 0xA74C < v then
                if v < 0xA752 then
                  if v < 0xA750 then
                    v = 0xA74E
                  else if 0xA750 < v then
                    False
                  else True
                else if 0xA752 < v then
                  v = 0xA754
                else True
              else True
            else True
          else if 0xA756 < v then
            if v < 0xA76A then
              if v < 0xA760 then
                if v < 0xA75C then
                  if v < 0xA75A then
                    v = 0xA758
                  else if 0xA75A < v then
                    False
                  else True
                else if 0xA75C < v then
                  v = 0xA75E
                else True
              else if 0xA760 < v then
                if v < 0xA766 then
                  if v < 0xA764 then
                    v = 0xA762
                  else if 0xA764 < v then
                    False
                  else True
                else if 0xA766 < v then
                  v = 0xA768
                else True
              else True
            else if 0xA76A < v then
              if v < 0xA77D then
                if v < 0xA779 then
                  if v < 0xA76E then
                    v = 0xA76C
                  else if 0xA76E < v then
                    False
                  else True
                else if 0xA779 < v then
                  v = 0xA77B
                else True
              else if 0xA77E < v then
                if v < 0xA784 then
                  if v < 0xA782 then
                    v = 0xA780
                  else if 0xA782 < v then
                    False
                  else True
                else if 0xA784 < v then
                  v = 0xA786
                else True
              else True
            else True
          else True
        else True
      else if 0xA78B < v then
        if v < 0x10594 then
          if v < 0xA7C0 then
            if v < 0xA7A4 then
              if v < 0xA79A then
                if v < 0xA792 then
                  if v < 0xA790 then
                    v = 0xA78D
                  else if 0xA790 < v then
                    False
                  else True
                else if 0xA792 < v then
                  if v < 0xA798 then
                    v = 0xA796
                  else if 0xA798 < v then
                    False
                  else True
                else True
              else if 0xA79A < v then
                if v < 0xA7A0 then
                  if v < 0xA79E then
                    v = 0xA79C
                  else if 0xA79E < v then
                    False
                  else True
                else if 0xA7A0 < v then
                  v = 0xA7A2
                else True
              else True
            else if 0xA7A4 < v then
              if v < 0xA7B6 then
                if v < 0xA7AA then
                  if v < 0xA7A8 then
                    v = 0xA7A6
                  else if 0xA7A8 < v then
                    False
                  else True
                else if 0xA7AE < v then
                  0xA7B0 ≤ v ∧ v ≤ 0xA7B4
                else True
              else if 0xA7B6 < v then
                if v < 0xA7BC then
                  if v < 0xA7BA then
                    v = 0xA7B8
                  else if 0xA7BA < v then
                    False
                  else True
                else if 0xA7BC < v then
                  v = 0xA7BE
                else True
              else True
            else True
          else if 0xA7C0 < v then
            if v < 0xA7D8 then
              if v < 0xA7CE then
                if v < 0xA7C9 then
                  if v < 0xA7C4 then
                    v = 0xA7C2
                  else if 0xA7C7 < v then
                    False
                  else True
                else if 0xA7C9 < v then
                  0xA7CB ≤ v ∧ v ≤ 0xA7CC
                else True
              else if 0xA7CE < v then
                if v < 0xA7D4 then
                  if v < 0xA7D2 then
                    v = 0xA7D0
                  else if 0xA7D2 < v then
                    False
                  else True
                else if 0xA7D4 < v then
                  v = 0xA7D6
                else True
              else True
            else if 0xA7D8 < v then
              if v < 0x10400 then
                if v < 0xA7F5 then
                  if v < 0xA7DC then
                    v = 0xA7DA
                  else if 0xA7DC < v then
                    False
                  else True
                else if 0xA7F5 < v then
                  0xFF21 ≤ v ∧ v ≤ 0xFF3A
                else True
              else if 0x10427 < v then
                if v < 0x1057C then
                  if v < 0x10570 then
                    0x104B0 ≤ v ∧ v ≤ 0x104D3
                  else if 0x1057A < v then
                    False
                  else True
                else if 0x1058A < v then
                  0x1058C ≤ v ∧ v ≤ 0x10592
                else True
              else True
            else True
          else True
        else if 0x10595 < v then
          if v < 0x1D53B then
            if v < 0x1D4A2 then
              if v < 0x1D400 then
                if v < 0x118A0 then
                  if v < 0x10D50 then
                    0x10C80 ≤ v ∧ v ≤ 0x10CB2
                  else if 0x10D65 < v then
                    False
                  else True
                else if 0x118BF < v then
                  if v < 0x16EA0 then
                    0x16E40 ≤ v ∧ v ≤ 0x16E5F
                  else if 0x16EB8 < v then
                    False
                  else True
                else True
              else if 0x1D419 < v then
                if v < 0x1D49C then
                  if v < 0x1D468 then
                    0x1D434 ≤ v ∧ v ≤ 0x1D44D
                  else if 0x1D481 < v then
                    False
                  else True
                else if 0x1D49C < v then
                  0x1D49E ≤ v ∧ v ≤ 0x1D49F
                else True
              else True
            else if 0x1D4A2 < v then
              if v < 0x1D504 then
                if v < 0x1D4AE then
                  if v < 0x1D4A9 then
                    0x1D4A5 ≤ v ∧ v ≤ 0x1D4A6
                  else if 0x1D4AC < v then
                    False
                  else True
                else if 0x1D4B5 < v then
                  0x1D4D0 ≤ v ∧ v ≤ 0x1D4E9
                else True
              else if 0x1D505 < v then
                if v < 0x1D516 then
                  if v < 0x1D50D then
                    0x1D507 ≤ v ∧ v ≤ 0x1D50A
                  else if 0x1D514 < v then
                    False
                  else True
                else if 0x1D51C < v then
                  0x1D538 ≤ v ∧ v ≤ 0x1D539
                else True
              else True
            else True
          else if 0x1D53E < v then
            if v < 0x1D6A8 then
              if v < 0x1D5A0 then
                if v < 0x1D54A then
                  if v < 0x1D546 then
                    0x1D540 ≤ v ∧ v ≤ 0x1D544
                  else if 0x1D546 < v then
                    False
                  else True
                else if 0x1D550 < v then
                  0x1D56C ≤ v ∧ v ≤ 0x1D585
                else True
              else if 0x1D5B9 < v then
                if v < 0x1D63C then
                  if v < 0x1D608 then
                    0x1D5D4 ≤ v ∧ v ≤ 0x1D5ED
                  else if 0x1D621 < v then
                    False
                  else True
                else if 0x1D655 < v then
                  0x1D670 ≤ v ∧ v ≤ 0x1D689
                else True
              else True
            else if 0x1D6C0 < v then
              if v < 0x1D7CA then
                if v < 0x1D756 then
                  if v < 0x1D71C then
                    0x1D6E2 ≤ v ∧ v ≤ 0x1D6FA
                  else if 0x1D734 < v then
                    False
                  else True
                else if 0x1D76E < v then
                  0x1D790 ≤ v ∧ v ≤ 0x1D7A8
                else True
              else if 0x1D7CA < v then
                if v < 0x1F150 then
                  if v < 0x1F130 then
                    0x1E900 ≤ v ∧ v ≤ 0x1E921
                  else if 0x1F149 < v then
                    False
                  else True
                else if 0x1F169 < v then
                  0x1F170 ≤ v ∧ v ≤ 0x1F189
                else True
              else True
            else True
          else True
        else True
      else True
    else True
  else True

set_option synthInstance.maxSize 4096 in
instance (v : UInt32) (h : BetweenOrEqStartEnd v) : Decidable (IsInsideSparseRangeTable v h) := by
  unfold IsInsideSparseRangeTable; infer_instance

end Unicode.TableLookupTables.Uppercase
