/- This file is generated by scripts/generate_script_types.ts. -/
module
prelude
public import Init

public import UnicodeBasic.Types.ScriptName.Basic

@[expose] public section

namespace Unicode

namespace ScriptName

public def ofFullName? : String → Option ScriptName
  | "Adlam" => some adlam
  | "Ahom" => some ahom
  | "Anatolian_Hieroglyphs" => some anatolianHieroglyphs
  | "Arabic" => some arabic
  | "Armenian" => some armenian
  | "Avestan" => some avestan
  | "Balinese" => some balinese
  | "Bamum" => some bamum
  | "Bassa_Vah" => some bassaVah
  | "Batak" => some batak
  | "Bengali" => some bengali
  | "Beria_Erfe" => some beriaErfe
  | "Bhaiksuki" => some bhaiksuki
  | "Bopomofo" => some bopomofo
  | "Brahmi" => some brahmi
  | "Braille" => some braille
  | "Buginese" => some buginese
  | "Buhid" => some buhid
  | "Canadian_Aboriginal" => some canadianAboriginal
  | "Carian" => some carian
  | "Caucasian_Albanian" => some caucasianAlbanian
  | "Chakma" => some chakma
  | "Cham" => some cham
  | "Cherokee" => some cherokee
  | "Chorasmian" => some chorasmian
  | "Common" => some common
  | "Coptic" => some coptic
  | "Cuneiform" => some cuneiform
  | "Cypriot" => some cypriot
  | "Cypro_Minoan" => some cyproMinoan
  | "Cyrillic" => some cyrillic
  | "Deseret" => some deseret
  | "Devanagari" => some devanagari
  | "Dives_Akuru" => some divesAkuru
  | "Dogra" => some dogra
  | "Duployan" => some duployan
  | "Egyptian_Hieroglyphs" => some egyptianHieroglyphs
  | "Elbasan" => some elbasan
  | "Elymaic" => some elymaic
  | "Ethiopic" => some ethiopic
  | "Garay" => some garay
  | "Georgian" => some georgian
  | "Glagolitic" => some glagolitic
  | "Gothic" => some gothic
  | "Grantha" => some grantha
  | "Greek" => some greek
  | "Gujarati" => some gujarati
  | "Gunjala_Gondi" => some gunjalaGondi
  | "Gurmukhi" => some gurmukhi
  | "Gurung_Khema" => some gurungKhema
  | "Han" => some han
  | "Hangul" => some hangul
  | "Hanifi_Rohingya" => some hanifiRohingya
  | "Hanunoo" => some hanunoo
  | "Hatran" => some hatran
  | "Hebrew" => some hebrew
  | "Hiragana" => some hiragana
  | "Imperial_Aramaic" => some imperialAramaic
  | "Inherited" => some inherited
  | "Inscriptional_Pahlavi" => some inscriptionalPahlavi
  | "Inscriptional_Parthian" => some inscriptionalParthian
  | "Javanese" => some javanese
  | "Kaithi" => some kaithi
  | "Kannada" => some kannada
  | "Katakana" => some katakana
  | "Katakana_Or_Hiragana" => some katakanaOrHiragana
  | "Kawi" => some kawi
  | "Kayah_Li" => some kayahLi
  | "Kharoshthi" => some kharoshthi
  | "Khitan_Small_Script" => some khitanSmallScript
  | "Khmer" => some khmer
  | "Khojki" => some khojki
  | "Khudawadi" => some khudawadi
  | "Kirat_Rai" => some kiratRai
  | "Lao" => some lao
  | "Latin" => some latin
  | "Lepcha" => some lepcha
  | "Limbu" => some limbu
  | "Linear_A" => some linearA
  | "Linear_B" => some linearB
  | "Lisu" => some lisu
  | "Lycian" => some lycian
  | "Lydian" => some lydian
  | "Mahajani" => some mahajani
  | "Makasar" => some makasar
  | "Malayalam" => some malayalam
  | "Mandaic" => some mandaic
  | "Manichaean" => some manichaean
  | "Marchen" => some marchen
  | "Masaram_Gondi" => some masaramGondi
  | "Medefaidrin" => some medefaidrin
  | "Meetei_Mayek" => some meeteiMayek
  | "Mende_Kikakui" => some mendeKikakui
  | "Meroitic_Cursive" => some meroiticCursive
  | "Meroitic_Hieroglyphs" => some meroiticHieroglyphs
  | "Miao" => some miao
  | "Modi" => some modi
  | "Mongolian" => some mongolian
  | "Mro" => some mro
  | "Multani" => some multani
  | "Myanmar" => some myanmar
  | "Nabataean" => some nabataean
  | "Nag_Mundari" => some nagMundari
  | "Nandinagari" => some nandinagari
  | "New_Tai_Lue" => some newTaiLue
  | "Newa" => some newa
  | "Nko" => some nko
  | "Nushu" => some nushu
  | "Nyiakeng_Puachue_Hmong" => some nyiakengPuachueHmong
  | "Ogham" => some ogham
  | "Ol_Chiki" => some olChiki
  | "Ol_Onal" => some olOnal
  | "Old_Hungarian" => some oldHungarian
  | "Old_Italic" => some oldItalic
  | "Old_North_Arabian" => some oldNorthArabian
  | "Old_Permic" => some oldPermic
  | "Old_Persian" => some oldPersian
  | "Old_Sogdian" => some oldSogdian
  | "Old_South_Arabian" => some oldSouthArabian
  | "Old_Turkic" => some oldTurkic
  | "Old_Uyghur" => some oldUyghur
  | "Oriya" => some oriya
  | "Osage" => some osage
  | "Osmanya" => some osmanya
  | "Pahawh_Hmong" => some pahawhHmong
  | "Palmyrene" => some palmyrene
  | "Pau_Cin_Hau" => some pauCinHau
  | "Phags_Pa" => some phagsPa
  | "Phoenician" => some phoenician
  | "Psalter_Pahlavi" => some psalterPahlavi
  | "Rejang" => some rejang
  | "Runic" => some runic
  | "Samaritan" => some samaritan
  | "Saurashtra" => some saurashtra
  | "Sharada" => some sharada
  | "Shavian" => some shavian
  | "Siddham" => some siddham
  | "Sidetic" => some sidetic
  | "SignWriting" => some signwriting
  | "Sinhala" => some sinhala
  | "Sogdian" => some sogdian
  | "Sora_Sompeng" => some soraSompeng
  | "Soyombo" => some soyombo
  | "Sundanese" => some sundanese
  | "Sunuwar" => some sunuwar
  | "Syloti_Nagri" => some sylotiNagri
  | "Syriac" => some syriac
  | "Tagalog" => some tagalog
  | "Tagbanwa" => some tagbanwa
  | "Tai_Le" => some taiLe
  | "Tai_Tham" => some taiTham
  | "Tai_Viet" => some taiViet
  | "Tai_Yo" => some taiYo
  | "Takri" => some takri
  | "Tamil" => some tamil
  | "Tangsa" => some tangsa
  | "Tangut" => some tangut
  | "Telugu" => some telugu
  | "Thaana" => some thaana
  | "Thai" => some thai
  | "Tibetan" => some tibetan
  | "Tifinagh" => some tifinagh
  | "Tirhuta" => some tirhuta
  | "Todhri" => some todhri
  | "Tolong_Siki" => some tolongSiki
  | "Toto" => some toto
  | "Tulu_Tigalari" => some tuluTigalari
  | "Ugaritic" => some ugaritic
  | "Vai" => some vai
  | "Vithkuqi" => some vithkuqi
  | "Wancho" => some wancho
  | "Warang_Citi" => some warangCiti
  | "Yezidi" => some yezidi
  | "Yi" => some yi
  | "Zanabazar_Square" => some zanabazarSquare
  | _ => none

@[inline]
public def ofString? : String → Option ScriptName := ofFullName?

end ScriptName

namespace MaybeUnknownScriptName

public def ofFullName? : String → Option MaybeUnknownScriptName
  | "Unknown" => some unknown
  | s => ScriptName.ofFullName? s |>.map scriptName

@[inline]
public def ofString? : String → Option MaybeUnknownScriptName := ofFullName?

end MaybeUnknownScriptName

end Unicode
