/- This file is generated by table-generators/makeTablesForLookup. -/
module

public import UnicodeBasic.TableLookupTables.Name.DuplicatedReturnedStrings

@[expose] public section

namespace Unicode.TableLookupTables.Name.Chunk22

@[inline_if_reduce, reducible]
def getInsideSparseRangeValueTable (v : UInt32) : Option String :=
  if v < 0x313A then
    if v < 0x30B4 then
      if v < 0x3072 then
        if v < 0x3052 then
          if v < 0x3042 then
            if v < 0x3039 then
              if v < 0x3035 then
                if v < 0x3033 then
                  if v < 0x3032 then
                    if v == 0x3031 then some ("VERTICAL KANA REPEAT MARK") else none
                  else if 0x3032 < v then
                    none
                  else some ("VERTICAL KANA REPEAT WITH VOICED SOUND MARK")
                else if 0x3033 < v then
                  if v == 0x3034 then some ("VERTICAL KANA REPEAT WITH VOICED SOUND MARK UPPER HALF") else none
                else some ("VERTICAL KANA REPEAT MARK UPPER HALF")
              else if 0x3035 < v then
                if v < 0x3037 then
                  if v == 0x3036 then some ("CIRCLED POSTAL MARK") else none
                else if 0x3037 < v then
                  if v == 0x3038 then some ("HANGZHOU NUMERAL TEN") else none
                else some ("IDEOGRAPHIC TELEGRAPH LINE FEED SEPARATOR SYMBOL")
              else some ("VERTICAL KANA REPEAT MARK LOWER HALF")
            else if 0x3039 < v then
              if v < 0x303D then
                if v < 0x303B then
                  if v == 0x303A then some ("HANGZHOU NUMERAL THIRTY") else none
                else if 0x303B < v then
                  if v == 0x303C then some ("MASU MARK") else none
                else some ("VERTICAL IDEOGRAPHIC ITERATION MARK")
              else if 0x303D < v then
                if v < 0x303F then
                  if v == 0x303E then some ("IDEOGRAPHIC VARIATION INDICATOR") else none
                else if 0x303F < v then
                  if v == 0x3041 then some ("HIRAGANA LETTER SMALL A") else none
                else some ("IDEOGRAPHIC HALF FILL SPACE")
              else some ("PART ALTERNATION MARK")
            else some ("HANGZHOU NUMERAL TWENTY")
          else if 0x3042 < v then
            if v < 0x304A then
              if v < 0x3046 then
                if v < 0x3044 then
                  if v == 0x3043 then some ("HIRAGANA LETTER SMALL I") else none
                else if 0x3044 < v then
                  if v == 0x3045 then some ("HIRAGANA LETTER SMALL U") else none
                else some ("HIRAGANA LETTER I")
              else if 0x3046 < v then
                if v < 0x3048 then
                  if v == 0x3047 then some ("HIRAGANA LETTER SMALL E") else none
                else if 0x3048 < v then
                  if v == 0x3049 then some ("HIRAGANA LETTER SMALL O") else none
                else some ("HIRAGANA LETTER E")
              else some ("HIRAGANA LETTER U")
            else if 0x304A < v then
              if v < 0x304E then
                if v < 0x304C then
                  if v == 0x304B then some ("HIRAGANA LETTER KA") else none
                else if 0x304C < v then
                  if v == 0x304D then some ("HIRAGANA LETTER KI") else none
                else some ("HIRAGANA LETTER GA")
              else if 0x304E < v then
                if v < 0x3050 then
                  if v == 0x304F then some ("HIRAGANA LETTER KU") else none
                else if 0x3050 < v then
                  if v == 0x3051 then some ("HIRAGANA LETTER KE") else none
                else some ("HIRAGANA LETTER GU")
              else some ("HIRAGANA LETTER GI")
            else some ("HIRAGANA LETTER O")
          else some ("HIRAGANA LETTER A")
        else if 0x3052 < v then
          if v < 0x3062 then
            if v < 0x305A then
              if v < 0x3056 then
                if v < 0x3054 then
                  if v == 0x3053 then some ("HIRAGANA LETTER KO") else none
                else if 0x3054 < v then
                  if v == 0x3055 then some ("HIRAGANA LETTER SA") else none
                else some ("HIRAGANA LETTER GO")
              else if 0x3056 < v then
                if v < 0x3058 then
                  if v == 0x3057 then some ("HIRAGANA LETTER SI") else none
                else if 0x3058 < v then
                  if v == 0x3059 then some ("HIRAGANA LETTER SU") else none
                else some ("HIRAGANA LETTER ZI")
              else some ("HIRAGANA LETTER ZA")
            else if 0x305A < v then
              if v < 0x305E then
                if v < 0x305C then
                  if v == 0x305B then some ("HIRAGANA LETTER SE") else none
                else if 0x305C < v then
                  if v == 0x305D then some ("HIRAGANA LETTER SO") else none
                else some ("HIRAGANA LETTER ZE")
              else if 0x305E < v then
                if v < 0x3060 then
                  if v == 0x305F then some ("HIRAGANA LETTER TA") else none
                else if 0x3060 < v then
                  if v == 0x3061 then some ("HIRAGANA LETTER TI") else none
                else some ("HIRAGANA LETTER DA")
              else some ("HIRAGANA LETTER ZO")
            else some ("HIRAGANA LETTER ZU")
          else if 0x3062 < v then
            if v < 0x306A then
              if v < 0x3066 then
                if v < 0x3064 then
                  if v == 0x3063 then some ("HIRAGANA LETTER SMALL TU") else none
                else if 0x3064 < v then
                  if v == 0x3065 then some ("HIRAGANA LETTER DU") else none
                else some ("HIRAGANA LETTER TU")
              else if 0x3066 < v then
                if v < 0x3068 then
                  if v == 0x3067 then some ("HIRAGANA LETTER DE") else none
                else if 0x3068 < v then
                  if v == 0x3069 then some ("HIRAGANA LETTER DO") else none
                else some ("HIRAGANA LETTER TO")
              else some ("HIRAGANA LETTER TE")
            else if 0x306A < v then
              if v < 0x306E then
                if v < 0x306C then
                  if v == 0x306B then some ("HIRAGANA LETTER NI") else none
                else if 0x306C < v then
                  if v == 0x306D then some ("HIRAGANA LETTER NE") else none
                else some ("HIRAGANA LETTER NU")
              else if 0x306E < v then
                if v < 0x3070 then
                  if v == 0x306F then some ("HIRAGANA LETTER HA") else none
                else if 0x3070 < v then
                  if v == 0x3071 then some ("HIRAGANA LETTER PA") else none
                else some ("HIRAGANA LETTER BA")
              else some ("HIRAGANA LETTER NO")
            else some ("HIRAGANA LETTER NA")
          else some ("HIRAGANA LETTER DI")
        else some ("HIRAGANA LETTER GE")
      else if 0x3072 < v then
        if v < 0x3092 then
          if v < 0x3082 then
            if v < 0x307A then
              if v < 0x3076 then
                if v < 0x3074 then
                  if v == 0x3073 then some ("HIRAGANA LETTER BI") else none
                else if 0x3074 < v then
                  if v == 0x3075 then some ("HIRAGANA LETTER HU") else none
                else some ("HIRAGANA LETTER PI")
              else if 0x3076 < v then
                if v < 0x3078 then
                  if v == 0x3077 then some ("HIRAGANA LETTER PU") else none
                else if 0x3078 < v then
                  if v == 0x3079 then some ("HIRAGANA LETTER BE") else none
                else some ("HIRAGANA LETTER HE")
              else some ("HIRAGANA LETTER BU")
            else if 0x307A < v then
              if v < 0x307E then
                if v < 0x307C then
                  if v == 0x307B then some ("HIRAGANA LETTER HO") else none
                else if 0x307C < v then
                  if v == 0x307D then some ("HIRAGANA LETTER PO") else none
                else some ("HIRAGANA LETTER BO")
              else if 0x307E < v then
                if v < 0x3080 then
                  if v == 0x307F then some ("HIRAGANA LETTER MI") else none
                else if 0x3080 < v then
                  if v == 0x3081 then some ("HIRAGANA LETTER ME") else none
                else some ("HIRAGANA LETTER MU")
              else some ("HIRAGANA LETTER MA")
            else some ("HIRAGANA LETTER PE")
          else if 0x3082 < v then
            if v < 0x308A then
              if v < 0x3086 then
                if v < 0x3084 then
                  if v == 0x3083 then some ("HIRAGANA LETTER SMALL YA") else none
                else if 0x3084 < v then
                  if v == 0x3085 then some ("HIRAGANA LETTER SMALL YU") else none
                else some ("HIRAGANA LETTER YA")
              else if 0x3086 < v then
                if v < 0x3088 then
                  if v == 0x3087 then some ("HIRAGANA LETTER SMALL YO") else none
                else if 0x3088 < v then
                  if v == 0x3089 then some ("HIRAGANA LETTER RA") else none
                else some ("HIRAGANA LETTER YO")
              else some ("HIRAGANA LETTER YU")
            else if 0x308A < v then
              if v < 0x308E then
                if v < 0x308C then
                  if v == 0x308B then some ("HIRAGANA LETTER RU") else none
                else if 0x308C < v then
                  if v == 0x308D then some ("HIRAGANA LETTER RO") else none
                else some ("HIRAGANA LETTER RE")
              else if 0x308E < v then
                if v < 0x3090 then
                  if v == 0x308F then some ("HIRAGANA LETTER WA") else none
                else if 0x3090 < v then
                  if v == 0x3091 then some ("HIRAGANA LETTER WE") else none
                else some ("HIRAGANA LETTER WI")
              else some ("HIRAGANA LETTER SMALL WA")
            else some ("HIRAGANA LETTER RI")
          else some ("HIRAGANA LETTER MO")
        else if 0x3092 < v then
          if v < 0x30A4 then
            if v < 0x309C then
              if v < 0x3096 then
                if v < 0x3094 then
                  if v == 0x3093 then some ("HIRAGANA LETTER N") else none
                else if 0x3094 < v then
                  if v == 0x3095 then some ("HIRAGANA LETTER SMALL KA") else none
                else some ("HIRAGANA LETTER VU")
              else if 0x3096 < v then
                if v < 0x309A then
                  if v == 0x3099 then some ("COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK") else none
                else if 0x309A < v then
                  if v == 0x309B then some ("KATAKANA-HIRAGANA VOICED SOUND MARK") else none
                else some ("COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK")
              else some ("HIRAGANA LETTER SMALL KE")
            else if 0x309C < v then
              if v < 0x30A0 then
                if v < 0x309E then
                  if v == 0x309D then some ("HIRAGANA ITERATION MARK") else none
                else if 0x309E < v then
                  if v == 0x309F then some ("HIRAGANA DIGRAPH YORI") else none
                else some ("HIRAGANA VOICED ITERATION MARK")
              else if 0x30A0 < v then
                if v < 0x30A2 then
                  if v == 0x30A1 then some ("KATAKANA LETTER SMALL A") else none
                else if 0x30A2 < v then
                  if v == 0x30A3 then some ("KATAKANA LETTER SMALL I") else none
                else some ("KATAKANA LETTER A")
              else some ("KATAKANA-HIRAGANA DOUBLE HYPHEN")
            else some ("KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK")
          else if 0x30A4 < v then
            if v < 0x30AC then
              if v < 0x30A8 then
                if v < 0x30A6 then
                  if v == 0x30A5 then some ("KATAKANA LETTER SMALL U") else none
                else if 0x30A6 < v then
                  if v == 0x30A7 then some ("KATAKANA LETTER SMALL E") else none
                else some ("KATAKANA LETTER U")
              else if 0x30A8 < v then
                if v < 0x30AA then
                  if v == 0x30A9 then some ("KATAKANA LETTER SMALL O") else none
                else if 0x30AA < v then
                  if v == 0x30AB then some ("KATAKANA LETTER KA") else none
                else some ("KATAKANA LETTER O")
              else some ("KATAKANA LETTER E")
            else if 0x30AC < v then
              if v < 0x30B0 then
                if v < 0x30AE then
                  if v == 0x30AD then some ("KATAKANA LETTER KI") else none
                else if 0x30AE < v then
                  if v == 0x30AF then some ("KATAKANA LETTER KU") else none
                else some ("KATAKANA LETTER GI")
              else if 0x30B0 < v then
                if v < 0x30B2 then
                  if v == 0x30B1 then some ("KATAKANA LETTER KE") else none
                else if 0x30B2 < v then
                  if v == 0x30B3 then some ("KATAKANA LETTER KO") else none
                else some ("KATAKANA LETTER GE")
              else some ("KATAKANA LETTER GU")
            else some ("KATAKANA LETTER GA")
          else some ("KATAKANA LETTER I")
        else some ("HIRAGANA LETTER WO")
      else some ("HIRAGANA LETTER HI")
    else if 0x30B4 < v then
      if v < 0x30F4 then
        if v < 0x30D4 then
          if v < 0x30C4 then
            if v < 0x30BC then
              if v < 0x30B8 then
                if v < 0x30B6 then
                  if v == 0x30B5 then some ("KATAKANA LETTER SA") else none
                else if 0x30B6 < v then
                  if v == 0x30B7 then some ("KATAKANA LETTER SI") else none
                else some ("KATAKANA LETTER ZA")
              else if 0x30B8 < v then
                if v < 0x30BA then
                  if v == 0x30B9 then some ("KATAKANA LETTER SU") else none
                else if 0x30BA < v then
                  if v == 0x30BB then some ("KATAKANA LETTER SE") else none
                else some ("KATAKANA LETTER ZU")
              else some ("KATAKANA LETTER ZI")
            else if 0x30BC < v then
              if v < 0x30C0 then
                if v < 0x30BE then
                  if v == 0x30BD then some ("KATAKANA LETTER SO") else none
                else if 0x30BE < v then
                  if v == 0x30BF then some ("KATAKANA LETTER TA") else none
                else some ("KATAKANA LETTER ZO")
              else if 0x30C0 < v then
                if v < 0x30C2 then
                  if v == 0x30C1 then some ("KATAKANA LETTER TI") else none
                else if 0x30C2 < v then
                  if v == 0x30C3 then some ("KATAKANA LETTER SMALL TU") else none
                else some ("KATAKANA LETTER DI")
              else some ("KATAKANA LETTER DA")
            else some ("KATAKANA LETTER ZE")
          else if 0x30C4 < v then
            if v < 0x30CC then
              if v < 0x30C8 then
                if v < 0x30C6 then
                  if v == 0x30C5 then some ("KATAKANA LETTER DU") else none
                else if 0x30C6 < v then
                  if v == 0x30C7 then some ("KATAKANA LETTER DE") else none
                else some ("KATAKANA LETTER TE")
              else if 0x30C8 < v then
                if v < 0x30CA then
                  if v == 0x30C9 then some ("KATAKANA LETTER DO") else none
                else if 0x30CA < v then
                  if v == 0x30CB then some ("KATAKANA LETTER NI") else none
                else some ("KATAKANA LETTER NA")
              else some ("KATAKANA LETTER TO")
            else if 0x30CC < v then
              if v < 0x30D0 then
                if v < 0x30CE then
                  if v == 0x30CD then some ("KATAKANA LETTER NE") else none
                else if 0x30CE < v then
                  if v == 0x30CF then some ("KATAKANA LETTER HA") else none
                else some ("KATAKANA LETTER NO")
              else if 0x30D0 < v then
                if v < 0x30D2 then
                  if v == 0x30D1 then some ("KATAKANA LETTER PA") else none
                else if 0x30D2 < v then
                  if v == 0x30D3 then some ("KATAKANA LETTER BI") else none
                else some ("KATAKANA LETTER HI")
              else some ("KATAKANA LETTER BA")
            else some ("KATAKANA LETTER NU")
          else some ("KATAKANA LETTER TU")
        else if 0x30D4 < v then
          if v < 0x30E4 then
            if v < 0x30DC then
              if v < 0x30D8 then
                if v < 0x30D6 then
                  if v == 0x30D5 then some ("KATAKANA LETTER HU") else none
                else if 0x30D6 < v then
                  if v == 0x30D7 then some ("KATAKANA LETTER PU") else none
                else some ("KATAKANA LETTER BU")
              else if 0x30D8 < v then
                if v < 0x30DA then
                  if v == 0x30D9 then some ("KATAKANA LETTER BE") else none
                else if 0x30DA < v then
                  if v == 0x30DB then some ("KATAKANA LETTER HO") else none
                else some ("KATAKANA LETTER PE")
              else some ("KATAKANA LETTER HE")
            else if 0x30DC < v then
              if v < 0x30E0 then
                if v < 0x30DE then
                  if v == 0x30DD then some ("KATAKANA LETTER PO") else none
                else if 0x30DE < v then
                  if v == 0x30DF then some ("KATAKANA LETTER MI") else none
                else some ("KATAKANA LETTER MA")
              else if 0x30E0 < v then
                if v < 0x30E2 then
                  if v == 0x30E1 then some ("KATAKANA LETTER ME") else none
                else if 0x30E2 < v then
                  if v == 0x30E3 then some ("KATAKANA LETTER SMALL YA") else none
                else some ("KATAKANA LETTER MO")
              else some ("KATAKANA LETTER MU")
            else some ("KATAKANA LETTER BO")
          else if 0x30E4 < v then
            if v < 0x30EC then
              if v < 0x30E8 then
                if v < 0x30E6 then
                  if v == 0x30E5 then some ("KATAKANA LETTER SMALL YU") else none
                else if 0x30E6 < v then
                  if v == 0x30E7 then some ("KATAKANA LETTER SMALL YO") else none
                else some ("KATAKANA LETTER YU")
              else if 0x30E8 < v then
                if v < 0x30EA then
                  if v == 0x30E9 then some ("KATAKANA LETTER RA") else none
                else if 0x30EA < v then
                  if v == 0x30EB then some ("KATAKANA LETTER RU") else none
                else some ("KATAKANA LETTER RI")
              else some ("KATAKANA LETTER YO")
            else if 0x30EC < v then
              if v < 0x30F0 then
                if v < 0x30EE then
                  if v == 0x30ED then some ("KATAKANA LETTER RO") else none
                else if 0x30EE < v then
                  if v == 0x30EF then some ("KATAKANA LETTER WA") else none
                else some ("KATAKANA LETTER SMALL WA")
              else if 0x30F0 < v then
                if v < 0x30F2 then
                  if v == 0x30F1 then some ("KATAKANA LETTER WE") else none
                else if 0x30F2 < v then
                  if v == 0x30F3 then some ("KATAKANA LETTER N") else none
                else some ("KATAKANA LETTER WO")
              else some ("KATAKANA LETTER WI")
            else some ("KATAKANA LETTER RE")
          else some ("KATAKANA LETTER YA")
        else some ("KATAKANA LETTER PI")
      else if 0x30F4 < v then
        if v < 0x3119 then
          if v < 0x3109 then
            if v < 0x30FC then
              if v < 0x30F8 then
                if v < 0x30F6 then
                  if v == 0x30F5 then some ("KATAKANA LETTER SMALL KA") else none
                else if 0x30F6 < v then
                  if v == 0x30F7 then some ("KATAKANA LETTER VA") else none
                else some ("KATAKANA LETTER SMALL KE")
              else if 0x30F8 < v then
                if v < 0x30FA then
                  if v == 0x30F9 then some ("KATAKANA LETTER VE") else none
                else if 0x30FA < v then
                  if v == 0x30FB then some ("KATAKANA MIDDLE DOT") else none
                else some ("KATAKANA LETTER VO")
              else some ("KATAKANA LETTER VI")
            else if 0x30FC < v then
              if v < 0x3105 then
                if v < 0x30FE then
                  if v == 0x30FD then some ("KATAKANA ITERATION MARK") else none
                else if 0x30FE < v then
                  if v == 0x30FF then some ("KATAKANA DIGRAPH KOTO") else none
                else some ("KATAKANA VOICED ITERATION MARK")
              else if 0x3105 < v then
                if v < 0x3107 then
                  if v == 0x3106 then some ("BOPOMOFO LETTER P") else none
                else if 0x3107 < v then
                  if v == 0x3108 then some ("BOPOMOFO LETTER F") else none
                else some ("BOPOMOFO LETTER M")
              else some ("BOPOMOFO LETTER B")
            else some ("KATAKANA-HIRAGANA PROLONGED SOUND MARK")
          else if 0x3109 < v then
            if v < 0x3111 then
              if v < 0x310D then
                if v < 0x310B then
                  if v == 0x310A then some ("BOPOMOFO LETTER T") else none
                else if 0x310B < v then
                  if v == 0x310C then some ("BOPOMOFO LETTER L") else none
                else some ("BOPOMOFO LETTER N")
              else if 0x310D < v then
                if v < 0x310F then
                  if v == 0x310E then some ("BOPOMOFO LETTER K") else none
                else if 0x310F < v then
                  if v == 0x3110 then some ("BOPOMOFO LETTER J") else none
                else some ("BOPOMOFO LETTER H")
              else some ("BOPOMOFO LETTER G")
            else if 0x3111 < v then
              if v < 0x3115 then
                if v < 0x3113 then
                  if v == 0x3112 then some ("BOPOMOFO LETTER X") else none
                else if 0x3113 < v then
                  if v == 0x3114 then some ("BOPOMOFO LETTER CH") else none
                else some ("BOPOMOFO LETTER ZH")
              else if 0x3115 < v then
                if v < 0x3117 then
                  if v == 0x3116 then some ("BOPOMOFO LETTER R") else none
                else if 0x3117 < v then
                  if v == 0x3118 then some ("BOPOMOFO LETTER C") else none
                else some ("BOPOMOFO LETTER Z")
              else some ("BOPOMOFO LETTER SH")
            else some ("BOPOMOFO LETTER Q")
          else some ("BOPOMOFO LETTER D")
        else if 0x3119 < v then
          if v < 0x3129 then
            if v < 0x3121 then
              if v < 0x311D then
                if v < 0x311B then
                  if v == 0x311A then some ("BOPOMOFO LETTER A") else none
                else if 0x311B < v then
                  if v == 0x311C then some ("BOPOMOFO LETTER E") else none
                else some ("BOPOMOFO LETTER O")
              else if 0x311D < v then
                if v < 0x311F then
                  if v == 0x311E then some ("BOPOMOFO LETTER AI") else none
                else if 0x311F < v then
                  if v == 0x3120 then some ("BOPOMOFO LETTER AU") else none
                else some ("BOPOMOFO LETTER EI")
              else some ("BOPOMOFO LETTER EH")
            else if 0x3121 < v then
              if v < 0x3125 then
                if v < 0x3123 then
                  if v == 0x3122 then some ("BOPOMOFO LETTER AN") else none
                else if 0x3123 < v then
                  if v == 0x3124 then some ("BOPOMOFO LETTER ANG") else none
                else some ("BOPOMOFO LETTER EN")
              else if 0x3125 < v then
                if v < 0x3127 then
                  if v == 0x3126 then some ("BOPOMOFO LETTER ER") else none
                else if 0x3127 < v then
                  if v == 0x3128 then some ("BOPOMOFO LETTER U") else none
                else some ("BOPOMOFO LETTER I")
              else some ("BOPOMOFO LETTER ENG")
            else some ("BOPOMOFO LETTER OU")
          else if 0x3129 < v then
            if v < 0x3132 then
              if v < 0x312D then
                if v < 0x312B then
                  if v == 0x312A then some ("BOPOMOFO LETTER V") else none
                else if 0x312B < v then
                  if v == 0x312C then some ("BOPOMOFO LETTER GN") else none
                else some ("BOPOMOFO LETTER NG")
              else if 0x312D < v then
                if v < 0x312F then
                  if v == 0x312E then some ("BOPOMOFO LETTER O WITH DOT ABOVE") else none
                else if 0x312F < v then
                  if v == 0x3131 then some ("HANGUL LETTER KIYEOK") else none
                else some ("BOPOMOFO LETTER NN")
              else some ("BOPOMOFO LETTER IH")
            else if 0x3132 < v then
              if v < 0x3136 then
                if v < 0x3134 then
                  if v == 0x3133 then some ("HANGUL LETTER KIYEOK-SIOS") else none
                else if 0x3134 < v then
                  if v == 0x3135 then some ("HANGUL LETTER NIEUN-CIEUC") else none
                else some ("HANGUL LETTER NIEUN")
              else if 0x3136 < v then
                if v < 0x3138 then
                  if v == 0x3137 then some ("HANGUL LETTER TIKEUT") else none
                else if 0x3138 < v then
                  if v == 0x3139 then some ("HANGUL LETTER RIEUL") else none
                else some ("HANGUL LETTER SSANGTIKEUT")
              else some ("HANGUL LETTER NIEUN-HIEUH")
            else some ("HANGUL LETTER SSANGKIYEOK")
          else some ("BOPOMOFO LETTER IU")
        else some ("BOPOMOFO LETTER S")
      else some ("KATAKANA LETTER VU")
    else some ("KATAKANA LETTER GO")
  else if 0x313A < v then
    if v < 0x31BB then
      if v < 0x317A then
        if v < 0x315A then
          if v < 0x314A then
            if v < 0x3142 then
              if v < 0x313E then
                if v < 0x313C then
                  if v == 0x313B then some ("HANGUL LETTER RIEUL-MIEUM") else none
                else if 0x313C < v then
                  if v == 0x313D then some ("HANGUL LETTER RIEUL-SIOS") else none
                else some ("HANGUL LETTER RIEUL-PIEUP")
              else if 0x313E < v then
                if v < 0x3140 then
                  if v == 0x313F then some ("HANGUL LETTER RIEUL-PHIEUPH") else none
                else if 0x3140 < v then
                  if v == 0x3141 then some ("HANGUL LETTER MIEUM") else none
                else some ("HANGUL LETTER RIEUL-HIEUH")
              else some ("HANGUL LETTER RIEUL-THIEUTH")
            else if 0x3142 < v then
              if v < 0x3146 then
                if v < 0x3144 then
                  if v == 0x3143 then some ("HANGUL LETTER SSANGPIEUP") else none
                else if 0x3144 < v then
                  if v == 0x3145 then some ("HANGUL LETTER SIOS") else none
                else some ("HANGUL LETTER PIEUP-SIOS")
              else if 0x3146 < v then
                if v < 0x3148 then
                  if v == 0x3147 then some ("HANGUL LETTER IEUNG") else none
                else if 0x3148 < v then
                  if v == 0x3149 then some ("HANGUL LETTER SSANGCIEUC") else none
                else some ("HANGUL LETTER CIEUC")
              else some ("HANGUL LETTER SSANGSIOS")
            else some ("HANGUL LETTER PIEUP")
          else if 0x314A < v then
            if v < 0x3152 then
              if v < 0x314E then
                if v < 0x314C then
                  if v == 0x314B then some ("HANGUL LETTER KHIEUKH") else none
                else if 0x314C < v then
                  if v == 0x314D then some ("HANGUL LETTER PHIEUPH") else none
                else some ("HANGUL LETTER THIEUTH")
              else if 0x314E < v then
                if v < 0x3150 then
                  if v == 0x314F then some ("HANGUL LETTER A") else none
                else if 0x3150 < v then
                  if v == 0x3151 then some ("HANGUL LETTER YA") else none
                else some ("HANGUL LETTER AE")
              else some ("HANGUL LETTER HIEUH")
            else if 0x3152 < v then
              if v < 0x3156 then
                if v < 0x3154 then
                  if v == 0x3153 then some ("HANGUL LETTER EO") else none
                else if 0x3154 < v then
                  if v == 0x3155 then some ("HANGUL LETTER YEO") else none
                else some ("HANGUL LETTER E")
              else if 0x3156 < v then
                if v < 0x3158 then
                  if v == 0x3157 then some ("HANGUL LETTER O") else none
                else if 0x3158 < v then
                  if v == 0x3159 then some ("HANGUL LETTER WAE") else none
                else some ("HANGUL LETTER WA")
              else some ("HANGUL LETTER YE")
            else some ("HANGUL LETTER YAE")
          else some ("HANGUL LETTER CHIEUCH")
        else if 0x315A < v then
          if v < 0x316A then
            if v < 0x3162 then
              if v < 0x315E then
                if v < 0x315C then
                  if v == 0x315B then some ("HANGUL LETTER YO") else none
                else if 0x315C < v then
                  if v == 0x315D then some ("HANGUL LETTER WEO") else none
                else some ("HANGUL LETTER U")
              else if 0x315E < v then
                if v < 0x3160 then
                  if v == 0x315F then some ("HANGUL LETTER WI") else none
                else if 0x3160 < v then
                  if v == 0x3161 then some ("HANGUL LETTER EU") else none
                else some ("HANGUL LETTER YU")
              else some ("HANGUL LETTER WE")
            else if 0x3162 < v then
              if v < 0x3166 then
                if v < 0x3164 then
                  if v == 0x3163 then some ("HANGUL LETTER I") else none
                else if 0x3164 < v then
                  if v == 0x3165 then some ("HANGUL LETTER SSANGNIEUN") else none
                else some ("HANGUL FILLER")
              else if 0x3166 < v then
                if v < 0x3168 then
                  if v == 0x3167 then some ("HANGUL LETTER NIEUN-SIOS") else none
                else if 0x3168 < v then
                  if v == 0x3169 then some ("HANGUL LETTER RIEUL-KIYEOK-SIOS") else none
                else some ("HANGUL LETTER NIEUN-PANSIOS")
              else some ("HANGUL LETTER NIEUN-TIKEUT")
            else some ("HANGUL LETTER YI")
          else if 0x316A < v then
            if v < 0x3172 then
              if v < 0x316E then
                if v < 0x316C then
                  if v == 0x316B then some ("HANGUL LETTER RIEUL-PIEUP-SIOS") else none
                else if 0x316C < v then
                  if v == 0x316D then some ("HANGUL LETTER RIEUL-YEORINHIEUH") else none
                else some ("HANGUL LETTER RIEUL-PANSIOS")
              else if 0x316E < v then
                if v < 0x3170 then
                  if v == 0x316F then some ("HANGUL LETTER MIEUM-SIOS") else none
                else if 0x3170 < v then
                  if v == 0x3171 then some ("HANGUL LETTER KAPYEOUNMIEUM") else none
                else some ("HANGUL LETTER MIEUM-PANSIOS")
              else some ("HANGUL LETTER MIEUM-PIEUP")
            else if 0x3172 < v then
              if v < 0x3176 then
                if v < 0x3174 then
                  if v == 0x3173 then some ("HANGUL LETTER PIEUP-TIKEUT") else none
                else if 0x3174 < v then
                  if v == 0x3175 then some ("HANGUL LETTER PIEUP-SIOS-TIKEUT") else none
                else some ("HANGUL LETTER PIEUP-SIOS-KIYEOK")
              else if 0x3176 < v then
                if v < 0x3178 then
                  if v == 0x3177 then some ("HANGUL LETTER PIEUP-THIEUTH") else none
                else if 0x3178 < v then
                  if v == 0x3179 then some ("HANGUL LETTER KAPYEOUNSSANGPIEUP") else none
                else some ("HANGUL LETTER KAPYEOUNPIEUP")
              else some ("HANGUL LETTER PIEUP-CIEUC")
            else some ("HANGUL LETTER PIEUP-KIYEOK")
          else some ("HANGUL LETTER RIEUL-TIKEUT")
        else some ("HANGUL LETTER OE")
      else if 0x317A < v then
        if v < 0x319B then
          if v < 0x318A then
            if v < 0x3182 then
              if v < 0x317E then
                if v < 0x317C then
                  if v == 0x317B then some ("HANGUL LETTER SIOS-NIEUN") else none
                else if 0x317C < v then
                  if v == 0x317D then some ("HANGUL LETTER SIOS-PIEUP") else none
                else some ("HANGUL LETTER SIOS-TIKEUT")
              else if 0x317E < v then
                if v < 0x3180 then
                  if v == 0x317F then some ("HANGUL LETTER PANSIOS") else none
                else if 0x3180 < v then
                  if v == 0x3181 then some ("HANGUL LETTER YESIEUNG") else none
                else some ("HANGUL LETTER SSANGIEUNG")
              else some ("HANGUL LETTER SIOS-CIEUC")
            else if 0x3182 < v then
              if v < 0x3186 then
                if v < 0x3184 then
                  if v == 0x3183 then some ("HANGUL LETTER YESIEUNG-PANSIOS") else none
                else if 0x3184 < v then
                  if v == 0x3185 then some ("HANGUL LETTER SSANGHIEUH") else none
                else some ("HANGUL LETTER KAPYEOUNPHIEUPH")
              else if 0x3186 < v then
                if v < 0x3188 then
                  if v == 0x3187 then some ("HANGUL LETTER YO-YA") else none
                else if 0x3188 < v then
                  if v == 0x3189 then some ("HANGUL LETTER YO-I") else none
                else some ("HANGUL LETTER YO-YAE")
              else some ("HANGUL LETTER YEORINHIEUH")
            else some ("HANGUL LETTER YESIEUNG-SIOS")
          else if 0x318A < v then
            if v < 0x3193 then
              if v < 0x318E then
                if v < 0x318C then
                  if v == 0x318B then some ("HANGUL LETTER YU-YE") else none
                else if 0x318C < v then
                  if v == 0x318D then some ("HANGUL LETTER ARAEA") else none
                else some ("HANGUL LETTER YU-I")
              else if 0x318E < v then
                if v < 0x3191 then
                  if v == 0x3190 then some ("IDEOGRAPHIC ANNOTATION LINKING MARK") else none
                else if 0x3191 < v then
                  if v == 0x3192 then some ("IDEOGRAPHIC ANNOTATION ONE MARK") else none
                else some ("IDEOGRAPHIC ANNOTATION REVERSE MARK")
              else some ("HANGUL LETTER ARAEAE")
            else if 0x3193 < v then
              if v < 0x3197 then
                if v < 0x3195 then
                  if v == 0x3194 then some ("IDEOGRAPHIC ANNOTATION THREE MARK") else none
                else if 0x3195 < v then
                  if v == 0x3196 then some ("IDEOGRAPHIC ANNOTATION TOP MARK") else none
                else some ("IDEOGRAPHIC ANNOTATION FOUR MARK")
              else if 0x3197 < v then
                if v < 0x3199 then
                  if v == 0x3198 then some ("IDEOGRAPHIC ANNOTATION BOTTOM MARK") else none
                else if 0x3199 < v then
                  if v == 0x319A then some ("IDEOGRAPHIC ANNOTATION SECOND MARK") else none
                else some ("IDEOGRAPHIC ANNOTATION FIRST MARK")
              else some ("IDEOGRAPHIC ANNOTATION MIDDLE MARK")
            else some ("IDEOGRAPHIC ANNOTATION TWO MARK")
          else some ("HANGUL LETTER YU-YEO")
        else if 0x319B < v then
          if v < 0x31AB then
            if v < 0x31A3 then
              if v < 0x319F then
                if v < 0x319D then
                  if v == 0x319C then some ("IDEOGRAPHIC ANNOTATION FOURTH MARK") else none
                else if 0x319D < v then
                  if v == 0x319E then some ("IDEOGRAPHIC ANNOTATION EARTH MARK") else none
                else some ("IDEOGRAPHIC ANNOTATION HEAVEN MARK")
              else if 0x319F < v then
                if v < 0x31A1 then
                  if v == 0x31A0 then some ("BOPOMOFO LETTER BU") else none
                else if 0x31A1 < v then
                  if v == 0x31A2 then some ("BOPOMOFO LETTER JI") else none
                else some ("BOPOMOFO LETTER ZI")
              else some ("IDEOGRAPHIC ANNOTATION MAN MARK")
            else if 0x31A3 < v then
              if v < 0x31A7 then
                if v < 0x31A5 then
                  if v == 0x31A4 then some ("BOPOMOFO LETTER EE") else none
                else if 0x31A5 < v then
                  if v == 0x31A6 then some ("BOPOMOFO LETTER OO") else none
                else some ("BOPOMOFO LETTER ENN")
              else if 0x31A7 < v then
                if v < 0x31A9 then
                  if v == 0x31A8 then some ("BOPOMOFO LETTER IR") else none
                else if 0x31A9 < v then
                  if v == 0x31AA then some ("BOPOMOFO LETTER INN") else none
                else some ("BOPOMOFO LETTER ANN")
              else some ("BOPOMOFO LETTER ONN")
            else some ("BOPOMOFO LETTER GU")
          else if 0x31AB < v then
            if v < 0x31B3 then
              if v < 0x31AF then
                if v < 0x31AD then
                  if v == 0x31AC then some ("BOPOMOFO LETTER IM") else none
                else if 0x31AD < v then
                  if v == 0x31AE then some ("BOPOMOFO LETTER AINN") else none
                else some ("BOPOMOFO LETTER NGG")
              else if 0x31AF < v then
                if v < 0x31B1 then
                  if v == 0x31B0 then some ("BOPOMOFO LETTER AM") else none
                else if 0x31B1 < v then
                  if v == 0x31B2 then some ("BOPOMOFO LETTER ONG") else none
                else some ("BOPOMOFO LETTER OM")
              else some ("BOPOMOFO LETTER AUNN")
            else if 0x31B3 < v then
              if v < 0x31B7 then
                if v < 0x31B5 then
                  if v == 0x31B4 then some ("BOPOMOFO FINAL LETTER P") else none
                else if 0x31B5 < v then
                  if v == 0x31B6 then some ("BOPOMOFO FINAL LETTER K") else none
                else some ("BOPOMOFO FINAL LETTER T")
              else if 0x31B7 < v then
                if v < 0x31B9 then
                  if v == 0x31B8 then some ("BOPOMOFO LETTER GH") else none
                else if 0x31B9 < v then
                  if v == 0x31BA then some ("BOPOMOFO LETTER ZY") else none
                else some ("BOPOMOFO LETTER LH")
              else some ("BOPOMOFO FINAL LETTER H")
            else some ("BOPOMOFO LETTER INNN")
          else some ("BOPOMOFO LETTER UNN")
        else some ("IDEOGRAPHIC ANNOTATION THIRD MARK")
      else some ("HANGUL LETTER SIOS-KIYEOK")
    else if 0x31BB < v then
      if v < 0x3204 then
        if v < 0x31DB then
          if v < 0x31CB then
            if v < 0x31C3 then
              if v < 0x31BF then
                if v < 0x31BD then
                  if v == 0x31BC then some ("BOPOMOFO LETTER GW") else none
                else if 0x31BD < v then
                  if v == 0x31BE then some ("BOPOMOFO LETTER OE") else none
                else some ("BOPOMOFO LETTER KW")
              else if 0x31BF < v then
                if v < 0x31C1 then
                  if v == 0x31C0 then some ("CJK STROKE T") else none
                else if 0x31C1 < v then
                  if v == 0x31C2 then some ("CJK STROKE XG") else none
                else some ("CJK STROKE WG")
              else some ("BOPOMOFO LETTER AH")
            else if 0x31C3 < v then
              if v < 0x31C7 then
                if v < 0x31C5 then
                  if v == 0x31C4 then some ("CJK STROKE SW") else none
                else if 0x31C5 < v then
                  if v == 0x31C6 then some ("CJK STROKE HZG") else none
                else some ("CJK STROKE HZZ")
              else if 0x31C7 < v then
                if v < 0x31C9 then
                  if v == 0x31C8 then some ("CJK STROKE HZWG") else none
                else if 0x31C9 < v then
                  if v == 0x31CA then some ("CJK STROKE HZT") else none
                else some ("CJK STROKE SZWG")
              else some ("CJK STROKE HP")
            else some ("CJK STROKE BXG")
          else if 0x31CB < v then
            if v < 0x31D3 then
              if v < 0x31CF then
                if v < 0x31CD then
                  if v == 0x31CC then some ("CJK STROKE HPWG") else none
                else if 0x31CD < v then
                  if v == 0x31CE then some ("CJK STROKE HZZZ") else none
                else some ("CJK STROKE HZW")
              else if 0x31CF < v then
                if v < 0x31D1 then
                  if v == 0x31D0 then some ("CJK STROKE H") else none
                else if 0x31D1 < v then
                  if v == 0x31D2 then some ("CJK STROKE P") else none
                else some ("CJK STROKE S")
              else some ("CJK STROKE N")
            else if 0x31D3 < v then
              if v < 0x31D7 then
                if v < 0x31D5 then
                  if v == 0x31D4 then some ("CJK STROKE D") else none
                else if 0x31D5 < v then
                  if v == 0x31D6 then some ("CJK STROKE HG") else none
                else some ("CJK STROKE HZ")
              else if 0x31D7 < v then
                if v < 0x31D9 then
                  if v == 0x31D8 then some ("CJK STROKE SWZ") else none
                else if 0x31D9 < v then
                  if v == 0x31DA then some ("CJK STROKE SG") else none
                else some ("CJK STROKE ST")
              else some ("CJK STROKE SZ")
            else some ("CJK STROKE SP")
          else some ("CJK STROKE HZZP")
        else if 0x31DB < v then
          if v < 0x31F4 then
            if v < 0x31E3 then
              if v < 0x31DF then
                if v < 0x31DD then
                  if v == 0x31DC then some ("CJK STROKE PZ") else none
                else if 0x31DD < v then
                  if v == 0x31DE then some ("CJK STROKE SZZ") else none
                else some ("CJK STROKE TN")
              else if 0x31DF < v then
                if v < 0x31E1 then
                  if v == 0x31E0 then some ("CJK STROKE HXWG") else none
                else if 0x31E1 < v then
                  if v == 0x31E2 then some ("CJK STROKE PG") else none
                else some ("CJK STROKE HZZZG")
              else some ("CJK STROKE SWG")
            else if 0x31E3 < v then
              if v < 0x31F0 then
                if v < 0x31E5 then
                  if v == 0x31E4 then some ("CJK STROKE HXG") else none
                else if 0x31E5 < v then
                  if v == 0x31EF then some ("IDEOGRAPHIC DESCRIPTION CHARACTER SUBTRACTION") else none
                else some ("CJK STROKE SZP")
              else if 0x31F0 < v then
                if v < 0x31F2 then
                  if v == 0x31F1 then some ("KATAKANA LETTER SMALL SI") else none
                else if 0x31F2 < v then
                  if v == 0x31F3 then some ("KATAKANA LETTER SMALL TO") else none
                else some ("KATAKANA LETTER SMALL SU")
              else some ("KATAKANA LETTER SMALL KU")
            else some ("CJK STROKE Q")
          else if 0x31F4 < v then
            if v < 0x31FC then
              if v < 0x31F8 then
                if v < 0x31F6 then
                  if v == 0x31F5 then some ("KATAKANA LETTER SMALL HA") else none
                else if 0x31F6 < v then
                  if v == 0x31F7 then some ("KATAKANA LETTER SMALL HU") else none
                else some ("KATAKANA LETTER SMALL HI")
              else if 0x31F8 < v then
                if v < 0x31FA then
                  if v == 0x31F9 then some ("KATAKANA LETTER SMALL HO") else none
                else if 0x31FA < v then
                  if v == 0x31FB then some ("KATAKANA LETTER SMALL RA") else none
                else some ("KATAKANA LETTER SMALL MU")
              else some ("KATAKANA LETTER SMALL HE")
            else if 0x31FC < v then
              if v < 0x3200 then
                if v < 0x31FE then
                  if v == 0x31FD then some ("KATAKANA LETTER SMALL RU") else none
                else if 0x31FE < v then
                  if v == 0x31FF then some ("KATAKANA LETTER SMALL RO") else none
                else some ("KATAKANA LETTER SMALL RE")
              else if 0x3200 < v then
                if v < 0x3202 then
                  if v == 0x3201 then some ("PARENTHESIZED HANGUL NIEUN") else none
                else if 0x3202 < v then
                  if v == 0x3203 then some ("PARENTHESIZED HANGUL RIEUL") else none
                else some ("PARENTHESIZED HANGUL TIKEUT")
              else some ("PARENTHESIZED HANGUL KIYEOK")
            else some ("KATAKANA LETTER SMALL RI")
          else some ("KATAKANA LETTER SMALL NU")
        else some ("CJK STROKE PD")
      else if 0x3204 < v then
        if v < 0x3225 then
          if v < 0x3214 then
            if v < 0x320C then
              if v < 0x3208 then
                if v < 0x3206 then
                  if v == 0x3205 then some ("PARENTHESIZED HANGUL PIEUP") else none
                else if 0x3206 < v then
                  if v == 0x3207 then some ("PARENTHESIZED HANGUL IEUNG") else none
                else some ("PARENTHESIZED HANGUL SIOS")
              else if 0x3208 < v then
                if v < 0x320A then
                  if v == 0x3209 then some ("PARENTHESIZED HANGUL CHIEUCH") else none
                else if 0x320A < v then
                  if v == 0x320B then some ("PARENTHESIZED HANGUL THIEUTH") else none
                else some ("PARENTHESIZED HANGUL KHIEUKH")
              else some ("PARENTHESIZED HANGUL CIEUC")
            else if 0x320C < v then
              if v < 0x3210 then
                if v < 0x320E then
                  if v == 0x320D then some ("PARENTHESIZED HANGUL HIEUH") else none
                else if 0x320E < v then
                  if v == 0x320F then some ("PARENTHESIZED HANGUL NIEUN A") else none
                else some ("PARENTHESIZED HANGUL KIYEOK A")
              else if 0x3210 < v then
                if v < 0x3212 then
                  if v == 0x3211 then some ("PARENTHESIZED HANGUL RIEUL A") else none
                else if 0x3212 < v then
                  if v == 0x3213 then some ("PARENTHESIZED HANGUL PIEUP A") else none
                else some ("PARENTHESIZED HANGUL MIEUM A")
              else some ("PARENTHESIZED HANGUL TIKEUT A")
            else some ("PARENTHESIZED HANGUL PHIEUPH")
          else if 0x3214 < v then
            if v < 0x321C then
              if v < 0x3218 then
                if v < 0x3216 then
                  if v == 0x3215 then some ("PARENTHESIZED HANGUL IEUNG A") else none
                else if 0x3216 < v then
                  if v == 0x3217 then some ("PARENTHESIZED HANGUL CHIEUCH A") else none
                else some ("PARENTHESIZED HANGUL CIEUC A")
              else if 0x3218 < v then
                if v < 0x321A then
                  if v == 0x3219 then some ("PARENTHESIZED HANGUL THIEUTH A") else none
                else if 0x321A < v then
                  if v == 0x321B then some ("PARENTHESIZED HANGUL HIEUH A") else none
                else some ("PARENTHESIZED HANGUL PHIEUPH A")
              else some ("PARENTHESIZED HANGUL KHIEUKH A")
            else if 0x321C < v then
              if v < 0x3221 then
                if v < 0x321E then
                  if v == 0x321D then some ("PARENTHESIZED KOREAN CHARACTER OJEON") else none
                else if 0x321E < v then
                  if v == 0x3220 then some ("PARENTHESIZED IDEOGRAPH ONE") else none
                else some ("PARENTHESIZED KOREAN CHARACTER O HU")
              else if 0x3221 < v then
                if v < 0x3223 then
                  if v == 0x3222 then some ("PARENTHESIZED IDEOGRAPH THREE") else none
                else if 0x3223 < v then
                  if v == 0x3224 then some ("PARENTHESIZED IDEOGRAPH FIVE") else none
                else some ("PARENTHESIZED IDEOGRAPH FOUR")
              else some ("PARENTHESIZED IDEOGRAPH TWO")
            else some ("PARENTHESIZED HANGUL CIEUC U")
          else some ("PARENTHESIZED HANGUL SIOS A")
        else if 0x3225 < v then
          if v < 0x3235 then
            if v < 0x322D then
              if v < 0x3229 then
                if v < 0x3227 then
                  if v == 0x3226 then some ("PARENTHESIZED IDEOGRAPH SEVEN") else none
                else if 0x3227 < v then
                  if v == 0x3228 then some ("PARENTHESIZED IDEOGRAPH NINE") else none
                else some ("PARENTHESIZED IDEOGRAPH EIGHT")
              else if 0x3229 < v then
                if v < 0x322B then
                  if v == 0x322A then some ("PARENTHESIZED IDEOGRAPH MOON") else none
                else if 0x322B < v then
                  if v == 0x322C then some ("PARENTHESIZED IDEOGRAPH WATER") else none
                else some ("PARENTHESIZED IDEOGRAPH FIRE")
              else some ("PARENTHESIZED IDEOGRAPH TEN")
            else if 0x322D < v then
              if v < 0x3231 then
                if v < 0x322F then
                  if v == 0x322E then some ("PARENTHESIZED IDEOGRAPH METAL") else none
                else if 0x322F < v then
                  if v == 0x3230 then some ("PARENTHESIZED IDEOGRAPH SUN") else none
                else some ("PARENTHESIZED IDEOGRAPH EARTH")
              else if 0x3231 < v then
                if v < 0x3233 then
                  if v == 0x3232 then some ("PARENTHESIZED IDEOGRAPH HAVE") else none
                else if 0x3233 < v then
                  if v == 0x3234 then some ("PARENTHESIZED IDEOGRAPH NAME") else none
                else some ("PARENTHESIZED IDEOGRAPH SOCIETY")
              else some ("PARENTHESIZED IDEOGRAPH STOCK")
            else some ("PARENTHESIZED IDEOGRAPH WOOD")
          else if 0x3235 < v then
            if v < 0x323D then
              if v < 0x3239 then
                if v < 0x3237 then
                  if v == 0x3236 then some ("PARENTHESIZED IDEOGRAPH FINANCIAL") else none
                else if 0x3237 < v then
                  if v == 0x3238 then some ("PARENTHESIZED IDEOGRAPH LABOR") else none
                else some ("PARENTHESIZED IDEOGRAPH CONGRATULATION")
              else if 0x3239 < v then
                if v < 0x323B then
                  if v == 0x323A then some ("PARENTHESIZED IDEOGRAPH CALL") else none
                else if 0x323B < v then
                  if v == 0x323C then some ("PARENTHESIZED IDEOGRAPH SUPERVISE") else none
                else some ("PARENTHESIZED IDEOGRAPH STUDY")
              else some ("PARENTHESIZED IDEOGRAPH REPRESENT")
            else if 0x323D < v then
              if v < 0x3241 then
                if v < 0x323F then
                  if v == 0x323E then some ("PARENTHESIZED IDEOGRAPH RESOURCE") else none
                else if 0x323F < v then
                  if v == 0x3240 then some ("PARENTHESIZED IDEOGRAPH FESTIVAL") else none
                else some ("PARENTHESIZED IDEOGRAPH ALLIANCE")
              else if 0x3241 < v then
                if v < 0x3243 then
                  if v == 0x3242 then some ("PARENTHESIZED IDEOGRAPH SELF") else none
                else if 0x3243 < v then
                  if v == 0x3244 then some ("CIRCLED IDEOGRAPH QUESTION") else none
                else some ("PARENTHESIZED IDEOGRAPH REACH")
              else some ("PARENTHESIZED IDEOGRAPH REST")
            else some ("PARENTHESIZED IDEOGRAPH ENTERPRISE")
          else some ("PARENTHESIZED IDEOGRAPH SPECIAL")
        else some ("PARENTHESIZED IDEOGRAPH SIX")
      else some ("PARENTHESIZED HANGUL MIEUM")
    else some ("BOPOMOFO FINAL LETTER G")
  else some ("HANGUL LETTER RIEUL-KIYEOK")

end Unicode.TableLookupTables.Name.Chunk22
