/- This file is generated by table-generators/makeTablesForLookup. -/
module

public import UnicodeBasic.TableLookupTables.Name.DuplicatedReturnedStrings

@[expose] public section

namespace Unicode.TableLookupTables.Name.Chunk59

@[inline_if_reduce, reducible]
def getInsideSparseRangeValueTable (v : UInt32) : Option String :=
  if v < 0x1CC24 then
    if v < 0x1BC37 then
      if v < 0x1B150 then
        if v < 0x1B104 then
          if v < 0x1B0F4 then
            if v < 0x1B0EC then
              if v < 0x1B0E8 then
                if v < 0x1B0E6 then
                  if v < 0x1B0E5 then
                    if v == 0x1B0E4 then some ("HENTAIGANA LETTER YU-2") else none
                  else if 0x1B0E5 < v then
                    none
                  else some ("HENTAIGANA LETTER YU-3")
                else if 0x1B0E6 < v then
                  if v == 0x1B0E7 then some ("HENTAIGANA LETTER YO-1") else none
                else some ("HENTAIGANA LETTER YU-4")
              else if 0x1B0E8 < v then
                if v < 0x1B0EA then
                  if v == 0x1B0E9 then some ("HENTAIGANA LETTER YO-3") else none
                else if 0x1B0EA < v then
                  if v == 0x1B0EB then some ("HENTAIGANA LETTER YO-5") else none
                else some ("HENTAIGANA LETTER YO-4")
              else some ("HENTAIGANA LETTER YO-2")
            else if 0x1B0EC < v then
              if v < 0x1B0F0 then
                if v < 0x1B0EE then
                  if v == 0x1B0ED then some ("HENTAIGANA LETTER RA-1") else none
                else if 0x1B0EE < v then
                  if v == 0x1B0EF then some ("HENTAIGANA LETTER RA-3") else none
                else some ("HENTAIGANA LETTER RA-2")
              else if 0x1B0F0 < v then
                if v < 0x1B0F2 then
                  if v == 0x1B0F1 then some ("HENTAIGANA LETTER RI-1") else none
                else if 0x1B0F2 < v then
                  if v == 0x1B0F3 then some ("HENTAIGANA LETTER RI-3") else none
                else some ("HENTAIGANA LETTER RI-2")
              else some ("HENTAIGANA LETTER RA-4")
            else some ("HENTAIGANA LETTER YO-6")
          else if 0x1B0F4 < v then
            if v < 0x1B0FC then
              if v < 0x1B0F8 then
                if v < 0x1B0F6 then
                  if v == 0x1B0F5 then some ("HENTAIGANA LETTER RI-5") else none
                else if 0x1B0F6 < v then
                  if v == 0x1B0F7 then some ("HENTAIGANA LETTER RI-7") else none
                else some ("HENTAIGANA LETTER RI-6")
              else if 0x1B0F8 < v then
                if v < 0x1B0FA then
                  if v == 0x1B0F9 then some ("HENTAIGANA LETTER RU-2") else none
                else if 0x1B0FA < v then
                  if v == 0x1B0FB then some ("HENTAIGANA LETTER RU-4") else none
                else some ("HENTAIGANA LETTER RU-3")
              else some ("HENTAIGANA LETTER RU-1")
            else if 0x1B0FC < v then
              if v < 0x1B100 then
                if v < 0x1B0FE then
                  if v == 0x1B0FD then some ("HENTAIGANA LETTER RU-6") else none
                else if 0x1B0FE < v then
                  if v == 0x1B0FF then some ("HENTAIGANA LETTER RE-2") else none
                else some ("HENTAIGANA LETTER RE-1")
              else if 0x1B100 < v then
                if v < 0x1B102 then
                  if v == 0x1B101 then some ("HENTAIGANA LETTER RE-4") else none
                else if 0x1B102 < v then
                  if v == 0x1B103 then some ("HENTAIGANA LETTER RO-2") else none
                else some ("HENTAIGANA LETTER RO-1")
              else some ("HENTAIGANA LETTER RE-3")
            else some ("HENTAIGANA LETTER RU-5")
          else some ("HENTAIGANA LETTER RI-4")
        else if 0x1B104 < v then
          if v < 0x1B114 then
            if v < 0x1B10C then
              if v < 0x1B108 then
                if v < 0x1B106 then
                  if v == 0x1B105 then some ("HENTAIGANA LETTER RO-4") else none
                else if 0x1B106 < v then
                  if v == 0x1B107 then some ("HENTAIGANA LETTER RO-6") else none
                else some ("HENTAIGANA LETTER RO-5")
              else if 0x1B108 < v then
                if v < 0x1B10A then
                  if v == 0x1B109 then some ("HENTAIGANA LETTER WA-2") else none
                else if 0x1B10A < v then
                  if v == 0x1B10B then some ("HENTAIGANA LETTER WA-4") else none
                else some ("HENTAIGANA LETTER WA-3")
              else some ("HENTAIGANA LETTER WA-1")
            else if 0x1B10C < v then
              if v < 0x1B110 then
                if v < 0x1B10E then
                  if v == 0x1B10D then some ("HENTAIGANA LETTER WI-1") else none
                else if 0x1B10E < v then
                  if v == 0x1B10F then some ("HENTAIGANA LETTER WI-3") else none
                else some ("HENTAIGANA LETTER WI-2")
              else if 0x1B110 < v then
                if v < 0x1B112 then
                  if v == 0x1B111 then some ("HENTAIGANA LETTER WI-5") else none
                else if 0x1B112 < v then
                  if v == 0x1B113 then some ("HENTAIGANA LETTER WE-2") else none
                else some ("HENTAIGANA LETTER WE-1")
              else some ("HENTAIGANA LETTER WI-4")
            else some ("HENTAIGANA LETTER WA-5")
          else if 0x1B114 < v then
            if v < 0x1B11C then
              if v < 0x1B118 then
                if v < 0x1B116 then
                  if v == 0x1B115 then some ("HENTAIGANA LETTER WE-4") else none
                else if 0x1B116 < v then
                  if v == 0x1B117 then some ("HENTAIGANA LETTER WO-2") else none
                else some ("HENTAIGANA LETTER WO-1")
              else if 0x1B118 < v then
                if v < 0x1B11A then
                  if v == 0x1B119 then some ("HENTAIGANA LETTER WO-4") else none
                else if 0x1B11A < v then
                  if v == 0x1B11B then some ("HENTAIGANA LETTER WO-6") else none
                else some ("HENTAIGANA LETTER WO-5")
              else some ("HENTAIGANA LETTER WO-3")
            else if 0x1B11C < v then
              if v < 0x1B120 then
                if v < 0x1B11E then
                  if v == 0x1B11D then some ("HENTAIGANA LETTER N-MU-MO-1") else none
                else if 0x1B11E < v then
                  if v == 0x1B11F then some ("HIRAGANA LETTER ARCHAIC WU") else none
                else some ("HENTAIGANA LETTER N-MU-MO-2")
              else if 0x1B120 < v then
                if v < 0x1B122 then
                  if v == 0x1B121 then some ("KATAKANA LETTER ARCHAIC YE") else none
                else if 0x1B122 < v then
                  if v == 0x1B132 then some ("HIRAGANA LETTER SMALL KO") else none
                else some ("KATAKANA LETTER ARCHAIC WU")
              else some ("KATAKANA LETTER ARCHAIC YI")
            else some ("HENTAIGANA LETTER WO-7")
          else some ("HENTAIGANA LETTER WE-3")
        else some ("HENTAIGANA LETTER RO-3")
      else if 0x1B150 < v then
        if v < 0x1BC17 then
          if v < 0x1BC07 then
            if v < 0x1B170 then
              if v < 0x1B164 then
                if v < 0x1B152 then
                  if v == 0x1B151 then some ("HIRAGANA LETTER SMALL WE") else none
                else if 0x1B152 < v then
                  if v == 0x1B155 then some ("KATAKANA LETTER SMALL KO") else none
                else some ("HIRAGANA LETTER SMALL WO")
              else if 0x1B164 < v then
                if v < 0x1B166 then
                  if v == 0x1B165 then some ("KATAKANA LETTER SMALL WE") else none
                else if 0x1B166 < v then
                  if v == 0x1B167 then some ("KATAKANA LETTER SMALL N") else none
                else some ("KATAKANA LETTER SMALL WO")
              else some ("KATAKANA LETTER SMALL WI")
            else if 0x1B2FB < v then
              if v < 0x1BC03 then
                if v < 0x1BC01 then
                  if v == 0x1BC00 then some ("DUPLOYAN LETTER H") else none
                else if 0x1BC01 < v then
                  if v == 0x1BC02 then some ("DUPLOYAN LETTER P") else none
                else some ("DUPLOYAN LETTER X")
              else if 0x1BC03 < v then
                if v < 0x1BC05 then
                  if v == 0x1BC04 then some ("DUPLOYAN LETTER F") else none
                else if 0x1BC05 < v then
                  if v == 0x1BC06 then some ("DUPLOYAN LETTER L") else none
                else some ("DUPLOYAN LETTER K")
              else some ("DUPLOYAN LETTER T")
            else some ("<Nushu Character>")
          else if 0x1BC07 < v then
            if v < 0x1BC0F then
              if v < 0x1BC0B then
                if v < 0x1BC09 then
                  if v == 0x1BC08 then some ("DUPLOYAN LETTER D") else none
                else if 0x1BC09 < v then
                  if v == 0x1BC0A then some ("DUPLOYAN LETTER G") else none
                else some ("DUPLOYAN LETTER V")
              else if 0x1BC0B < v then
                if v < 0x1BC0D then
                  if v == 0x1BC0C then some ("DUPLOYAN LETTER P N") else none
                else if 0x1BC0D < v then
                  if v == 0x1BC0E then some ("DUPLOYAN LETTER F N") else none
                else some ("DUPLOYAN LETTER D S")
              else some ("DUPLOYAN LETTER R")
            else if 0x1BC0F < v then
              if v < 0x1BC13 then
                if v < 0x1BC11 then
                  if v == 0x1BC10 then some ("DUPLOYAN LETTER R S") else none
                else if 0x1BC11 < v then
                  if v == 0x1BC12 then some ("DUPLOYAN LETTER SLOAN DH") else none
                else some ("DUPLOYAN LETTER TH")
              else if 0x1BC13 < v then
                if v < 0x1BC15 then
                  if v == 0x1BC14 then some ("DUPLOYAN LETTER KK") else none
                else if 0x1BC15 < v then
                  if v == 0x1BC16 then some ("DUPLOYAN LETTER HL") else none
                else some ("DUPLOYAN LETTER SLOAN J")
              else some ("DUPLOYAN LETTER DH")
            else some ("DUPLOYAN LETTER K M")
          else some ("DUPLOYAN LETTER B")
        else if 0x1BC17 < v then
          if v < 0x1BC27 then
            if v < 0x1BC1F then
              if v < 0x1BC1B then
                if v < 0x1BC19 then
                  if v == 0x1BC18 then some ("DUPLOYAN LETTER RH") else none
                else if 0x1BC19 < v then
                  if v == 0x1BC1A then some ("DUPLOYAN LETTER N") else none
                else some ("DUPLOYAN LETTER M")
              else if 0x1BC1B < v then
                if v < 0x1BC1D then
                  if v == 0x1BC1C then some ("DUPLOYAN LETTER S") else none
                else if 0x1BC1D < v then
                  if v == 0x1BC1E then some ("DUPLOYAN LETTER N M") else none
                else some ("DUPLOYAN LETTER M N")
              else some ("DUPLOYAN LETTER J")
            else if 0x1BC1F < v then
              if v < 0x1BC23 then
                if v < 0x1BC21 then
                  if v == 0x1BC20 then some ("DUPLOYAN LETTER S J") else none
                else if 0x1BC21 < v then
                  if v == 0x1BC22 then some ("DUPLOYAN LETTER N WITH DOT") else none
                else some ("DUPLOYAN LETTER M WITH DOT")
              else if 0x1BC23 < v then
                if v < 0x1BC25 then
                  if v == 0x1BC24 then some ("DUPLOYAN LETTER J WITH DOTS INSIDE AND ABOVE") else none
                else if 0x1BC25 < v then
                  if v == 0x1BC26 then some ("DUPLOYAN LETTER S WITH DOT BELOW") else none
                else some ("DUPLOYAN LETTER S WITH DOT")
              else some ("DUPLOYAN LETTER J WITH DOT")
            else some ("DUPLOYAN LETTER J M")
          else if 0x1BC27 < v then
            if v < 0x1BC2F then
              if v < 0x1BC2B then
                if v < 0x1BC29 then
                  if v == 0x1BC28 then some ("DUPLOYAN LETTER N S") else none
                else if 0x1BC29 < v then
                  if v == 0x1BC2A then some ("DUPLOYAN LETTER S S") else none
                else some ("DUPLOYAN LETTER J S")
              else if 0x1BC2B < v then
                if v < 0x1BC2D then
                  if v == 0x1BC2C then some ("DUPLOYAN LETTER N M S") else none
                else if 0x1BC2D < v then
                  if v == 0x1BC2E then some ("DUPLOYAN LETTER S J S") else none
                else some ("DUPLOYAN LETTER J M S")
              else some ("DUPLOYAN LETTER M N S")
            else if 0x1BC2F < v then
              if v < 0x1BC33 then
                if v < 0x1BC31 then
                  if v == 0x1BC30 then some ("DUPLOYAN LETTER J N") else none
                else if 0x1BC31 < v then
                  if v == 0x1BC32 then some ("DUPLOYAN LETTER S T") else none
                else some ("DUPLOYAN LETTER J N S")
              else if 0x1BC33 < v then
                if v < 0x1BC35 then
                  if v == 0x1BC34 then some ("DUPLOYAN LETTER S P") else none
                else if 0x1BC35 < v then
                  if v == 0x1BC36 then some ("DUPLOYAN LETTER T S") else none
                else some ("DUPLOYAN LETTER S P R")
              else some ("DUPLOYAN LETTER S T R")
            else some ("DUPLOYAN LETTER J S WITH DOT")
          else some ("DUPLOYAN LETTER M S")
        else some ("DUPLOYAN LETTER LH")
      else some ("HIRAGANA LETTER SMALL WI")
    else if 0x1BC37 < v then
      if v < 0x1BC7C then
        if v < 0x1BC57 then
          if v < 0x1BC47 then
            if v < 0x1BC3F then
              if v < 0x1BC3B then
                if v < 0x1BC39 then
                  if v == 0x1BC38 then some ("DUPLOYAN LETTER W") else none
                else if 0x1BC39 < v then
                  if v == 0x1BC3A then some ("DUPLOYAN LETTER W R") else none
                else some ("DUPLOYAN LETTER WH")
              else if 0x1BC3B < v then
                if v < 0x1BC3D then
                  if v == 0x1BC3C then some ("DUPLOYAN LETTER S M") else none
                else if 0x1BC3D < v then
                  if v == 0x1BC3E then some ("DUPLOYAN LETTER G R S") else none
                else some ("DUPLOYAN LETTER K R S")
              else some ("DUPLOYAN LETTER S N")
            else if 0x1BC3F < v then
              if v < 0x1BC43 then
                if v < 0x1BC41 then
                  if v == 0x1BC40 then some ("DUPLOYAN LETTER S K R") else none
                else if 0x1BC41 < v then
                  if v == 0x1BC42 then some ("DUPLOYAN LETTER SLOAN OW") else none
                else some ("DUPLOYAN LETTER A")
              else if 0x1BC43 < v then
                if v < 0x1BC45 then
                  if v == 0x1BC44 then some ("DUPLOYAN LETTER O") else none
                else if 0x1BC45 < v then
                  if v == 0x1BC46 then some ("DUPLOYAN LETTER I") else none
                else some ("DUPLOYAN LETTER AOU")
              else some ("DUPLOYAN LETTER OA")
            else some ("DUPLOYAN LETTER S K")
          else if 0x1BC47 < v then
            if v < 0x1BC4F then
              if v < 0x1BC4B then
                if v < 0x1BC49 then
                  if v == 0x1BC48 then some ("DUPLOYAN LETTER IE") else none
                else if 0x1BC49 < v then
                  if v == 0x1BC4A then some ("DUPLOYAN LETTER UI") else none
                else some ("DUPLOYAN LETTER SHORT I")
              else if 0x1BC4B < v then
                if v < 0x1BC4D then
                  if v == 0x1BC4C then some ("DUPLOYAN LETTER SLOAN EH") else none
                else if 0x1BC4D < v then
                  if v == 0x1BC4E then some ("DUPLOYAN LETTER SLOAN EE") else none
                else some ("DUPLOYAN LETTER ROMANIAN I")
              else some ("DUPLOYAN LETTER EE")
            else if 0x1BC4F < v then
              if v < 0x1BC53 then
                if v < 0x1BC51 then
                  if v == 0x1BC50 then some ("DUPLOYAN LETTER YE") else none
                else if 0x1BC51 < v then
                  if v == 0x1BC52 then some ("DUPLOYAN LETTER EU") else none
                else some ("DUPLOYAN LETTER U")
              else if 0x1BC53 < v then
                if v < 0x1BC55 then
                  if v == 0x1BC54 then some ("DUPLOYAN LETTER U N") else none
                else if 0x1BC55 < v then
                  if v == 0x1BC56 then some ("DUPLOYAN LETTER ROMANIAN U") else none
                else some ("DUPLOYAN LETTER LONG U")
              else some ("DUPLOYAN LETTER XW")
            else some ("DUPLOYAN LETTER LONG I")
          else some ("DUPLOYAN LETTER E")
        else if 0x1BC57 < v then
          if v < 0x1BC67 then
            if v < 0x1BC5F then
              if v < 0x1BC5B then
                if v < 0x1BC59 then
                  if v == 0x1BC58 then some ("DUPLOYAN LETTER SLOAN U") else none
                else if 0x1BC59 < v then
                  if v == 0x1BC5A then some ("DUPLOYAN LETTER OW") else none
                else some ("DUPLOYAN LETTER OOH")
              else if 0x1BC5B < v then
                if v < 0x1BC5D then
                  if v == 0x1BC5C then some ("DUPLOYAN LETTER WA") else none
                else if 0x1BC5D < v then
                  if v == 0x1BC5E then some ("DUPLOYAN LETTER WI") else none
                else some ("DUPLOYAN LETTER WO")
              else some ("DUPLOYAN LETTER OU")
            else if 0x1BC5F < v then
              if v < 0x1BC63 then
                if v < 0x1BC61 then
                  if v == 0x1BC60 then some ("DUPLOYAN LETTER WOW") else none
                else if 0x1BC61 < v then
                  if v == 0x1BC62 then some ("DUPLOYAN LETTER NASAL O") else none
                else some ("DUPLOYAN LETTER NASAL U")
              else if 0x1BC63 < v then
                if v < 0x1BC65 then
                  if v == 0x1BC64 then some ("DUPLOYAN LETTER NASAL A") else none
                else if 0x1BC65 < v then
                  if v == 0x1BC66 then some ("DUPLOYAN LETTER PERNIN AM") else none
                else some ("DUPLOYAN LETTER PERNIN AN")
              else some ("DUPLOYAN LETTER NASAL I")
            else some ("DUPLOYAN LETTER WEI")
          else if 0x1BC67 < v then
            if v < 0x1BC74 then
              if v < 0x1BC70 then
                if v < 0x1BC69 then
                  if v == 0x1BC68 then some ("DUPLOYAN LETTER SLOAN AN") else none
                else if 0x1BC69 < v then
                  if v == 0x1BC6A then some ("DUPLOYAN LETTER VOCALIC M") else none
                else some ("DUPLOYAN LETTER SLOAN ON")
              else if 0x1BC70 < v then
                if v < 0x1BC72 then
                  if v == 0x1BC71 then some ("DUPLOYAN AFFIX MID HORIZONTAL SECANT") else none
                else if 0x1BC72 < v then
                  if v == 0x1BC73 then some ("DUPLOYAN AFFIX LOW VERTICAL SECANT") else none
                else some ("DUPLOYAN AFFIX RIGHT HORIZONTAL SECANT")
              else some ("DUPLOYAN AFFIX LEFT HORIZONTAL SECANT")
            else if 0x1BC74 < v then
              if v < 0x1BC78 then
                if v < 0x1BC76 then
                  if v == 0x1BC75 then some ("DUPLOYAN AFFIX HIGH VERTICAL SECANT") else none
                else if 0x1BC76 < v then
                  if v == 0x1BC77 then some ("DUPLOYAN AFFIX ATTACHED LEFT-TO-RIGHT SECANT") else none
                else some ("DUPLOYAN AFFIX ATTACHED SECANT")
              else if 0x1BC78 < v then
                if v < 0x1BC7A then
                  if v == 0x1BC79 then some ("DUPLOYAN AFFIX ATTACHED TAIL") else none
                else if 0x1BC7A < v then
                  if v == 0x1BC7B then some ("DUPLOYAN AFFIX ATTACHED I HOOK") else none
                else some ("DUPLOYAN AFFIX ATTACHED E HOOK")
              else some ("DUPLOYAN AFFIX ATTACHED TANGENT")
            else some ("DUPLOYAN AFFIX MID VERTICAL SECANT")
          else some ("DUPLOYAN LETTER SLOAN EN")
        else some ("DUPLOYAN LETTER UH")
      else if 0x1BC7C < v then
        if v < 0x1CC04 then
          if v < 0x1BC96 then
            if v < 0x1BC87 then
              if v < 0x1BC83 then
                if v < 0x1BC81 then
                  if v == 0x1BC80 then some ("DUPLOYAN AFFIX HIGH ACUTE") else none
                else if 0x1BC81 < v then
                  if v == 0x1BC82 then some ("DUPLOYAN AFFIX HIGH GRAVE") else none
                else some ("DUPLOYAN AFFIX HIGH TIGHT ACUTE")
              else if 0x1BC83 < v then
                if v < 0x1BC85 then
                  if v == 0x1BC84 then some ("DUPLOYAN AFFIX HIGH DOT") else none
                else if 0x1BC85 < v then
                  if v == 0x1BC86 then some ("DUPLOYAN AFFIX HIGH LINE") else none
                else some ("DUPLOYAN AFFIX HIGH CIRCLE")
              else some ("DUPLOYAN AFFIX HIGH LONG GRAVE")
            else if 0x1BC87 < v then
              if v < 0x1BC92 then
                if v < 0x1BC90 then
                  if v == 0x1BC88 then some ("DUPLOYAN AFFIX HIGH VERTICAL") else none
                else if 0x1BC90 < v then
                  if v == 0x1BC91 then some ("DUPLOYAN AFFIX LOW TIGHT ACUTE") else none
                else some ("DUPLOYAN AFFIX LOW ACUTE")
              else if 0x1BC92 < v then
                if v < 0x1BC94 then
                  if v == 0x1BC93 then some ("DUPLOYAN AFFIX LOW LONG GRAVE") else none
                else if 0x1BC94 < v then
                  if v == 0x1BC95 then some ("DUPLOYAN AFFIX LOW CIRCLE") else none
                else some ("DUPLOYAN AFFIX LOW DOT")
              else some ("DUPLOYAN AFFIX LOW GRAVE")
            else some ("DUPLOYAN AFFIX HIGH WAVE")
          else if 0x1BC96 < v then
            if v < 0x1BCA0 then
              if v < 0x1BC9C then
                if v < 0x1BC98 then
                  if v == 0x1BC97 then some ("DUPLOYAN AFFIX LOW WAVE") else none
                else if 0x1BC98 < v then
                  if v == 0x1BC99 then some ("DUPLOYAN AFFIX LOW ARROW") else none
                else some ("DUPLOYAN AFFIX LOW VERTICAL")
              else if 0x1BC9C < v then
                if v < 0x1BC9E then
                  if v == 0x1BC9D then some ("DUPLOYAN THICK LETTER SELECTOR") else none
                else if 0x1BC9E < v then
                  if v == 0x1BC9F then some ("DUPLOYAN PUNCTUATION CHINOOK FULL STOP") else none
                else some ("DUPLOYAN DOUBLE MARK")
              else some ("DUPLOYAN SIGN O WITH CROSS")
            else if 0x1BCA0 < v then
              if v < 0x1CC00 then
                if v < 0x1BCA2 then
                  if v == 0x1BCA1 then some ("SHORTHAND FORMAT CONTINUING OVERLAP") else none
                else if 0x1BCA2 < v then
                  if v == 0x1BCA3 then some ("SHORTHAND FORMAT UP STEP") else none
                else some ("SHORTHAND FORMAT DOWN STEP")
              else if 0x1CC00 < v then
                if v < 0x1CC02 then
                  if v == 0x1CC01 then some ("RIGHT-POINTING GO-KART") else none
                else if 0x1CC02 < v then
                  if v == 0x1CC03 then some ("RIGHT-POINTING STICK FIGURE") else none
                else some ("LEFT-POINTING STICK FIGURE")
              else some ("UP-POINTING GO-KART")
            else some ("SHORTHAND FORMAT LETTER OVERLAP")
          else some ("DUPLOYAN AFFIX LOW LINE")
        else if 0x1CC04 < v then
          if v < 0x1CC14 then
            if v < 0x1CC0C then
              if v < 0x1CC08 then
                if v < 0x1CC06 then
                  if v == 0x1CC05 then some ("LOWER HORIZONTAL RULER SEGMENT") else none
                else if 0x1CC06 < v then
                  if v == 0x1CC07 then some ("LOWER RIGHT RULER SEGMENT") else none
                else some ("RIGHT VERTICAL RULER SEGMENT")
              else if 0x1CC08 < v then
                if v < 0x1CC0A then
                  if v == 0x1CC09 then some ("HORIZONTAL RESISTOR SEGMENT") else none
                else if 0x1CC0A < v then
                  if v == 0x1CC0B then some ("LEFT THIRD INDUCTOR") else none
                else some ("VERTICAL RESISTOR SEGMENT")
              else some ("ANTENNA")
            else if 0x1CC0C < v then
              if v < 0x1CC10 then
                if v < 0x1CC0E then
                  if v == 0x1CC0D then some ("RIGHT THIRD INDUCTOR") else none
                else if 0x1CC0E < v then
                  if v == 0x1CC0F then some ("RIGHT-POINTING DIODE") else none
                else some ("LEFT-POINTING DIODE")
              else if 0x1CC10 < v then
                if v < 0x1CC12 then
                  if v == 0x1CC11 then some ("PNP TRANSISTOR") else none
                else if 0x1CC12 < v then
                  if v == 0x1CC13 then some ("HORIZONTAL CAPACITOR") else none
                else some ("RECEPTACLE")
              else some ("NPN TRANSISTOR")
            else some ("MIDDLE THIRD INDUCTOR")
          else if 0x1CC14 < v then
            if v < 0x1CC1C then
              if v < 0x1CC18 then
                if v < 0x1CC16 then
                  if v == 0x1CC15 then some ("LOGIC GATE OR") else none
                else if 0x1CC16 < v then
                  if v == 0x1CC17 then some ("LOGIC GATE INVERTED INPUTS") else none
                else some ("LOGIC GATE AND")
              else if 0x1CC18 < v then
                if v < 0x1CC1A then
                  if v == 0x1CC19 then some ("LOGIC GATE BUFFER") else none
                else if 0x1CC1A < v then
                  if v == 0x1CC1B then some ("BOX DRAWINGS LIGHT HORIZONTAL AND UPPER RIGHT") else none
                else some ("LOGIC GATE BUFFER WITH INVERTED INPUT")
              else some ("LOGIC GATE INVERTED OUTPUT")
            else if 0x1CC1C < v then
              if v < 0x1CC20 then
                if v < 0x1CC1E then
                  if v == 0x1CC1D then some ("BOX DRAWINGS LIGHT TOP AND UPPER LEFT") else none
                else if 0x1CC1E < v then
                  if v == 0x1CC1F then some ("BOX DRAWINGS DOUBLE DIAGONAL UPPER RIGHT TO LOWER LEFT") else none
                else some ("BOX DRAWINGS LIGHT BOTTOM AND LOWER LEFT")
              else if 0x1CC20 < v then
                if v < 0x1CC22 then
                  if v == 0x1CC21 then some ("SEPARATED BLOCK QUADRANT-1") else none
                else if 0x1CC22 < v then
                  if v == 0x1CC23 then some ("SEPARATED BLOCK QUADRANT-12") else none
                else some ("SEPARATED BLOCK QUADRANT-2")
              else some ("BOX DRAWINGS DOUBLE DIAGONAL UPPER LEFT TO LOWER RIGHT")
            else some ("BOX DRAWINGS LIGHT HORIZONTAL AND LOWER RIGHT")
          else some ("VERTICAL CAPACITOR")
        else some ("DOWN-POINTING STICK FIGURE")
      else some ("DUPLOYAN AFFIX ATTACHED TANGENT HOOK")
    else some ("DUPLOYAN LETTER T R S")
  else if 0x1CC24 < v then
    if v < 0x1CCA4 then
      if v < 0x1CC64 then
        if v < 0x1CC44 then
          if v < 0x1CC34 then
            if v < 0x1CC2C then
              if v < 0x1CC28 then
                if v < 0x1CC26 then
                  if v == 0x1CC25 then some ("SEPARATED BLOCK QUADRANT-13") else none
                else if 0x1CC26 < v then
                  if v == 0x1CC27 then some ("SEPARATED BLOCK QUADRANT-123") else none
                else some ("SEPARATED BLOCK QUADRANT-23")
              else if 0x1CC28 < v then
                if v < 0x1CC2A then
                  if v == 0x1CC29 then some ("SEPARATED BLOCK QUADRANT-14") else none
                else if 0x1CC2A < v then
                  if v == 0x1CC2B then some ("SEPARATED BLOCK QUADRANT-124") else none
                else some ("SEPARATED BLOCK QUADRANT-24")
              else some ("SEPARATED BLOCK QUADRANT-4")
            else if 0x1CC2C < v then
              if v < 0x1CC30 then
                if v < 0x1CC2E then
                  if v == 0x1CC2D then some ("SEPARATED BLOCK QUADRANT-134") else none
                else if 0x1CC2E < v then
                  if v == 0x1CC2F then some ("SEPARATED BLOCK QUADRANT-1234") else none
                else some ("SEPARATED BLOCK QUADRANT-234")
              else if 0x1CC30 < v then
                if v < 0x1CC32 then
                  if v == 0x1CC31 then some ("UPPER CENTRE LEFT TWELFTH CIRCLE") else none
                else if 0x1CC32 < v then
                  if v == 0x1CC33 then some ("UPPER RIGHT TWELFTH CIRCLE") else none
                else some ("UPPER CENTRE RIGHT TWELFTH CIRCLE")
              else some ("UPPER LEFT TWELFTH CIRCLE")
            else some ("SEPARATED BLOCK QUADRANT-34")
          else if 0x1CC34 < v then
            if v < 0x1CC3C then
              if v < 0x1CC38 then
                if v < 0x1CC36 then
                  if v == 0x1CC35 then some ("UPPER LEFT QUARTER CIRCLE") else none
                else if 0x1CC36 < v then
                  if v == 0x1CC37 then some ("UPPER MIDDLE RIGHT TWELFTH CIRCLE") else none
                else some ("UPPER RIGHT QUARTER CIRCLE")
              else if 0x1CC38 < v then
                if v < 0x1CC3A then
                  if v == 0x1CC39 then some ("LOWER LEFT QUARTER CIRCLE") else none
                else if 0x1CC3A < v then
                  if v == 0x1CC3B then some ("LOWER MIDDLE RIGHT TWELFTH CIRCLE") else none
                else some ("LOWER RIGHT QUARTER CIRCLE")
              else some ("LOWER MIDDLE LEFT TWELFTH CIRCLE")
            else if 0x1CC3C < v then
              if v < 0x1CC40 then
                if v < 0x1CC3E then
                  if v == 0x1CC3D then some ("LOWER CENTRE LEFT TWELFTH CIRCLE") else none
                else if 0x1CC3E < v then
                  if v == 0x1CC3F then some ("LOWER RIGHT TWELFTH CIRCLE") else none
                else some ("LOWER CENTRE RIGHT TWELFTH CIRCLE")
              else if 0x1CC40 < v then
                if v < 0x1CC42 then
                  if v == 0x1CC41 then some ("SPARSE VERTICAL FILL") else none
                else if 0x1CC42 < v then
                  if v == 0x1CC43 then some ("DIAGONAL CROSSHATCH FILL") else none
                else some ("ORTHOGONAL CROSSHATCH FILL")
              else some ("SPARSE HORIZONTAL FILL")
            else some ("LOWER LEFT TWELFTH CIRCLE")
          else some ("UPPER MIDDLE LEFT TWELFTH CIRCLE")
        else if 0x1CC44 < v then
          if v < 0x1CC54 then
            if v < 0x1CC4C then
              if v < 0x1CC48 then
                if v < 0x1CC46 then
                  if v == 0x1CC45 then some ("DENSE HORIZONTAL FILL") else none
                else if 0x1CC46 < v then
                  if v == 0x1CC47 then some ("SPECKLE FILL FRAME-2") else none
                else some ("SPECKLE FILL FRAME-1")
              else if 0x1CC48 < v then
                if v < 0x1CC4A then
                  if v == 0x1CC49 then some ("RIGHT-FACING BASSINET") else none
                else if 0x1CC4A < v then
                  if v == 0x1CC4B then some ("FLYING SAUCER WITHOUT BEAMS") else none
                else some ("FLYING SAUCER WITH BEAMS")
              else some ("LEFT-FACING BASSINET")
            else if 0x1CC4C < v then
              if v < 0x1CC50 then
                if v < 0x1CC4E then
                  if v == 0x1CC4D then some ("ALIEN MONSTER CLOSED JAWS") else none
                else if 0x1CC4E < v then
                  if v == 0x1CC4F then some ("ALIEN SQUID CLOSED TENTACLES") else none
                else some ("ALIEN SQUID OPEN TENTACLES")
              else if 0x1CC50 < v then
                if v < 0x1CC52 then
                  if v == 0x1CC51 then some ("ALIEN CRAB STEPPING LEFT") else none
                else if 0x1CC52 < v then
                  if v == 0x1CC53 then some ("ALIEN SPIDER SPREAD") else none
                else some ("ALIEN SPIDER CROUCHING")
              else some ("ALIEN CRAB STEPPING RIGHT")
            else some ("ALIEN MONSTER OPEN JAWS")
          else if 0x1CC54 < v then
            if v < 0x1CC5C then
              if v < 0x1CC58 then
                if v < 0x1CC56 then
                  if v == 0x1CC55 then some ("ALIEN MONSTER STEP-2") else none
                else if 0x1CC56 < v then
                  if v == 0x1CC57 then some ("UP-POINTING ROCKET SHIP") else none
                else some ("LEFT-POINTING ROCKET SHIP")
              else if 0x1CC58 < v then
                if v < 0x1CC5A then
                  if v == 0x1CC59 then some ("DOWN-POINTING ROCKET SHIP") else none
                else if 0x1CC5A < v then
                  if v == 0x1CC5B then some ("TOP HALF FORWARD-FACING ROBOT") else none
                else some ("TOP HALF LEFT-FACING ROBOT")
              else some ("RIGHT-POINTING ROCKET SHIP")
            else if 0x1CC5C < v then
              if v < 0x1CC60 then
                if v < 0x1CC5E then
                  if v == 0x1CC5D then some ("BOTTOM HALF LEFT-FACING ROBOT") else none
                else if 0x1CC5E < v then
                  if v == 0x1CC5F then some ("BOTTOM HALF RIGHT-FACING ROBOT") else none
                else some ("BOTTOM HALF FORWARD-FACING ROBOT")
              else if 0x1CC60 < v then
                if v < 0x1CC62 then
                  if v == 0x1CC61 then some ("UP-POINTING ATOMIC BOMB") else none
                else if 0x1CC62 < v then
                  if v == 0x1CC63 then some ("DOWN-POINTING ATOMIC BOMB") else none
                else some ("RIGHT-POINTING ATOMIC BOMB")
              else some ("LEFT-POINTING ATOMIC BOMB")
            else some ("TOP HALF RIGHT-FACING ROBOT")
          else some ("ALIEN MONSTER STEP-1")
        else some ("DENSE VERTICAL FILL")
      else if 0x1CC64 < v then
        if v < 0x1CC84 then
          if v < 0x1CC74 then
            if v < 0x1CC6C then
              if v < 0x1CC68 then
                if v < 0x1CC66 then
                  if v == 0x1CC65 then some ("LEFT-POINTING RIFLE") else none
                else if 0x1CC66 < v then
                  if v == 0x1CC67 then some ("RIGHT-POINTING RIFLE") else none
                else some ("UP-POINTING RIFLE")
              else if 0x1CC68 < v then
                if v < 0x1CC6A then
                  if v == 0x1CC69 then some ("EIGHT RAYS INWARD") else none
                else if 0x1CC6A < v then
                  if v == 0x1CC6B then some ("BLACK LARGE CIRCLE MINUS LEFT QUARTER SECTION") else none
                else some ("EIGHT RAYS OUTWARD")
              else some ("DOWN-POINTING RIFLE")
            else if 0x1CC6C < v then
              if v < 0x1CC70 then
                if v < 0x1CC6E then
                  if v == 0x1CC6D then some ("BLACK LARGE CIRCLE MINUS RIGHT QUARTER SECTION") else none
                else if 0x1CC6E < v then
                  if v == 0x1CC6F then some ("BLACK NEUTRAL FACE") else none
                else some ("BLACK LARGE CIRCLE MINUS LOWER QUARTER SECTION")
              else if 0x1CC70 < v then
                if v < 0x1CC72 then
                  if v == 0x1CC71 then some ("UP-FACING SNAKE HEAD WITH OPEN MOUTH") else none
                else if 0x1CC72 < v then
                  if v == 0x1CC73 then some ("DOWN-FACING SNAKE HEAD WITH OPEN MOUTH") else none
                else some ("RIGHT-FACING SNAKE HEAD WITH OPEN MOUTH")
              else some ("LEFT-FACING SNAKE HEAD WITH OPEN MOUTH")
            else some ("BLACK LARGE CIRCLE MINUS UPPER QUARTER SECTION")
          else if 0x1CC74 < v then
            if v < 0x1CC7C then
              if v < 0x1CC78 then
                if v < 0x1CC76 then
                  if v == 0x1CC75 then some ("UP-FACING SNAKE HEAD WITH CLOSED MOUTH") else none
                else if 0x1CC76 < v then
                  if v == 0x1CC77 then some ("DOWN-FACING SNAKE HEAD WITH CLOSED MOUTH") else none
                else some ("RIGHT-FACING SNAKE HEAD WITH CLOSED MOUTH")
              else if 0x1CC78 < v then
                if v < 0x1CC7A then
                  if v == 0x1CC79 then some ("UP-POINTING ENERGY WAVE") else none
                else if 0x1CC7A < v then
                  if v == 0x1CC7B then some ("DOWN-POINTING ENERGY WAVE") else none
                else some ("RIGHT-POINTING ENERGY WAVE")
              else some ("LEFT-POINTING ENERGY WAVE")
            else if 0x1CC7C < v then
              if v < 0x1CC80 then
                if v < 0x1CC7E then
                  if v == 0x1CC7D then some ("SQUARE SPIRAL FROM TOP RIGHT") else none
                else if 0x1CC7E < v then
                  if v == 0x1CC7F then some ("SQUARE SPIRAL FROM BOTTOM LEFT") else none
                else some ("SQUARE SPIRAL FROM BOTTOM RIGHT")
              else if 0x1CC80 < v then
                if v < 0x1CC82 then
                  if v == 0x1CC81 then some ("STRIPED UP-POINTING TRIANGLE") else none
                else if 0x1CC82 < v then
                  if v == 0x1CC83 then some ("STRIPED DOWN-POINTING TRIANGLE") else none
                else some ("STRIPED RIGHT-POINTING TRIANGLE")
              else some ("STRIPED LEFT-POINTING TRIANGLE")
            else some ("SQUARE SPIRAL FROM TOP LEFT")
          else some ("LEFT-FACING SNAKE HEAD WITH CLOSED MOUTH")
        else if 0x1CC84 < v then
          if v < 0x1CC94 then
            if v < 0x1CC8C then
              if v < 0x1CC88 then
                if v < 0x1CC86 then
                  if v == 0x1CC85 then some ("HORIZONTAL LADDER") else none
                else if 0x1CC86 < v then
                  if v == 0x1CC87 then some ("WHITE LOWER RIGHT POINTER") else none
                else some ("WHITE LOWER LEFT POINTER")
              else if 0x1CC88 < v then
                if v < 0x1CC8A then
                  if v == 0x1CC89 then some ("SQUARE FOUR CORNER SALTIRES") else none
                else if 0x1CC8A < v then
                  if v == 0x1CC8B then some ("SQUARE FOUR CORNER BLACK TRIANGLES") else none
                else some ("SQUARE FOUR CORNER DIAGONALS")
              else some ("TWO RINGS ALIGNED HORIZONTALLY")
            else if 0x1CC8C < v then
              if v < 0x1CC90 then
                if v < 0x1CC8E then
                  if v == 0x1CC8D then some ("INVERSE BLACK DIAMOND") else none
                else if 0x1CC8E < v then
                  if v == 0x1CC8F then some ("INVERSE BLACK SMALL SQUARE") else none
                else some ("LEFT AND UPPER ONE EIGHTH BLOCK CONTAINING BLACK SMALL SQUARE")
              else if 0x1CC90 < v then
                if v < 0x1CC92 then
                  if v == 0x1CC91 then some ("HORIZONTAL LINE WITH FOUR TICK MARKS") else none
                else if 0x1CC92 < v then
                  if v == 0x1CC93 then some ("RIGHT-FACING FISH") else none
                else some ("LEFT-FACING FISH")
              else some ("VERTICAL LINE WITH FOUR TICK MARKS")
            else some ("SQUARE APERTURE")
          else if 0x1CC94 < v then
            if v < 0x1CC9C then
              if v < 0x1CC98 then
                if v < 0x1CC96 then
                  if v == 0x1CC95 then some ("RIGHT-FACING FISH WITH OPEN MOUTH") else none
                else if 0x1CC96 < v then
                  if v == 0x1CC97 then some ("LEFT-POINTING RACING CAR") else none
                else some ("FLAPPING BIRD")
              else if 0x1CC98 < v then
                if v < 0x1CC9A then
                  if v == 0x1CC99 then some ("RIGHT-POINTING RACING CAR") else none
                else if 0x1CC9A < v then
                  if v == 0x1CC9B then some ("HORIZONTAL RACING CAR") else none
                else some ("DOWN-POINTING RACING CAR")
              else some ("UP-POINTING RACING CAR")
            else if 0x1CC9C < v then
              if v < 0x1CCA0 then
                if v < 0x1CC9E then
                  if v == 0x1CC9D then some ("VERTICAL GO-KART") else none
                else if 0x1CC9E < v then
                  if v == 0x1CC9F then some ("RIGHT-POINTING TANK") else none
                else some ("LEFT-POINTING TANK")
              else if 0x1CCA0 < v then
                if v < 0x1CCA2 then
                  if v == 0x1CCA1 then some ("RIGHT-POINTING ROCKET BOOSTER") else none
                else if 0x1CCA2 < v then
                  if v == 0x1CCA3 then some ("RIGHT-POINTING ROLLER COASTER CAR") else none
                else some ("LEFT-POINTING ROLLER COASTER CAR")
              else some ("LEFT-POINTING ROCKET BOOSTER")
            else some ("VERTICAL RACING CAR")
          else some ("LEFT-FACING FISH WITH OPEN MOUTH")
        else some ("VERTICAL LADDER")
      else some ("MUSHROOM CLOUD")
    else if 0x1CCA4 < v then
      if v < 0x1CCE4 then
        if v < 0x1CCC4 then
          if v < 0x1CCB4 then
            if v < 0x1CCAC then
              if v < 0x1CCA8 then
                if v < 0x1CCA6 then
                  if v == 0x1CCA5 then some ("RIGHT HALF FLYING SAUCER") else none
                else if 0x1CCA6 < v then
                  if v == 0x1CCA7 then some ("UPPER RIGHT QUADRANT FACE WITH OPEN EYES") else none
                else some ("UPPER LEFT QUADRANT FACE WITH OPEN EYES")
              else if 0x1CCA8 < v then
                if v < 0x1CCAA then
                  if v == 0x1CCA9 then some ("UPPER RIGHT QUADRANT FACE WITH CLOSED EYES") else none
                else if 0x1CCAA < v then
                  if v == 0x1CCAB then some ("LOWER RIGHT QUADRANT SMILING FACE") else none
                else some ("LOWER LEFT QUADRANT SMILING FACE")
              else some ("UPPER LEFT QUADRANT FACE WITH CLOSED EYES")
            else if 0x1CCAC < v then
              if v < 0x1CCB0 then
                if v < 0x1CCAE then
                  if v == 0x1CCAD then some ("LOWER RIGHT QUADRANT NEUTRAL FACE") else none
                else if 0x1CCAE < v then
                  if v == 0x1CCAF then some ("LOWER RIGHT QUADRANT FACE WITH OPEN MOUTH") else none
                else some ("LOWER LEFT QUADRANT FACE WITH OPEN MOUTH")
              else if 0x1CCB0 < v then
                if v < 0x1CCB2 then
                  if v == 0x1CCB1 then some ("LOWER RIGHT QUADRANT FROWNING FACE") else none
                else if 0x1CCB2 < v then
                  if v == 0x1CCB3 then some ("UPPER RIGHT QUADRANT TELEVISION") else none
                else some ("UPPER LEFT QUADRANT TELEVISION")
              else some ("LOWER LEFT QUADRANT FROWNING FACE")
            else some ("LOWER LEFT QUADRANT NEUTRAL FACE")
          else if 0x1CCB4 < v then
            if v < 0x1CCBC then
              if v < 0x1CCB8 then
                if v < 0x1CCB6 then
                  if v == 0x1CCB5 then some ("LOWER RIGHT QUADRANT TELEVISION") else none
                else if 0x1CCB6 < v then
                  if v == 0x1CCB7 then some ("UPPER RIGHT QUADRANT MICROCOMPUTER") else none
                else some ("UPPER LEFT QUADRANT MICROCOMPUTER")
              else if 0x1CCB8 < v then
                if v < 0x1CCBA then
                  if v == 0x1CCB9 then some ("LOWER RIGHT QUADRANT MICROCOMPUTER") else none
                else if 0x1CCBA < v then
                  if v == 0x1CCBB then some ("UPPER RIGHT QUADRANT CHESS KING") else none
                else some ("UPPER LEFT QUADRANT CHESS KING")
              else some ("LOWER LEFT QUADRANT MICROCOMPUTER")
            else if 0x1CCBC < v then
              if v < 0x1CCC0 then
                if v < 0x1CCBE then
                  if v == 0x1CCBD then some ("LOWER RIGHT QUADRANT CHESS KING") else none
                else if 0x1CCBE < v then
                  if v == 0x1CCBF then some ("UPPER RIGHT QUADRANT CHESS QUEEN") else none
                else some ("UPPER LEFT QUADRANT CHESS QUEEN")
              else if 0x1CCC0 < v then
                if v < 0x1CCC2 then
                  if v == 0x1CCC1 then some ("LOWER RIGHT QUADRANT CHESS QUEEN") else none
                else if 0x1CCC2 < v then
                  if v == 0x1CCC3 then some ("UPPER RIGHT QUADRANT CHESS ROOK") else none
                else some ("UPPER LEFT QUADRANT CHESS ROOK")
              else some ("LOWER LEFT QUADRANT CHESS QUEEN")
            else some ("LOWER LEFT QUADRANT CHESS KING")
          else some ("LOWER LEFT QUADRANT TELEVISION")
        else if 0x1CCC4 < v then
          if v < 0x1CCD4 then
            if v < 0x1CCCC then
              if v < 0x1CCC8 then
                if v < 0x1CCC6 then
                  if v == 0x1CCC5 then some ("LOWER RIGHT QUADRANT CHESS ROOK") else none
                else if 0x1CCC6 < v then
                  if v == 0x1CCC7 then some ("UPPER RIGHT QUADRANT CHESS BISHOP") else none
                else some ("UPPER LEFT QUADRANT CHESS BISHOP")
              else if 0x1CCC8 < v then
                if v < 0x1CCCA then
                  if v == 0x1CCC9 then some ("LOWER RIGHT QUADRANT CHESS BISHOP") else none
                else if 0x1CCCA < v then
                  if v == 0x1CCCB then some ("UPPER RIGHT QUADRANT CHESS KNIGHT") else none
                else some ("UPPER LEFT QUADRANT CHESS KNIGHT")
              else some ("LOWER LEFT QUADRANT CHESS BISHOP")
            else if 0x1CCCC < v then
              if v < 0x1CCD0 then
                if v < 0x1CCCE then
                  if v == 0x1CCCD then some ("LOWER RIGHT QUADRANT CHESS KNIGHT") else none
                else if 0x1CCCE < v then
                  if v == 0x1CCCF then some ("UPPER RIGHT QUADRANT CHESS PAWN") else none
                else some ("UPPER LEFT QUADRANT CHESS PAWN")
              else if 0x1CCD0 < v then
                if v < 0x1CCD2 then
                  if v == 0x1CCD1 then some ("LOWER RIGHT QUADRANT CHESS PAWN") else none
                else if 0x1CCD2 < v then
                  if v == 0x1CCD3 then some ("UPPER RIGHT QUADRANT STANDING KNIGHT") else none
                else some ("UPPER LEFT QUADRANT STANDING KNIGHT")
              else some ("LOWER LEFT QUADRANT CHESS PAWN")
            else some ("LOWER LEFT QUADRANT CHESS KNIGHT")
          else if 0x1CCD4 < v then
            if v < 0x1CCDC then
              if v < 0x1CCD8 then
                if v < 0x1CCD6 then
                  if v == 0x1CCD5 then some ("LOWER RIGHT QUADRANT STANDING KNIGHT") else none
                else if 0x1CCD6 < v then
                  if v == 0x1CCD7 then some ("OUTLINED LATIN CAPITAL LETTER B") else none
                else some ("OUTLINED LATIN CAPITAL LETTER A")
              else if 0x1CCD8 < v then
                if v < 0x1CCDA then
                  if v == 0x1CCD9 then some ("OUTLINED LATIN CAPITAL LETTER D") else none
                else if 0x1CCDA < v then
                  if v == 0x1CCDB then some ("OUTLINED LATIN CAPITAL LETTER F") else none
                else some ("OUTLINED LATIN CAPITAL LETTER E")
              else some ("OUTLINED LATIN CAPITAL LETTER C")
            else if 0x1CCDC < v then
              if v < 0x1CCE0 then
                if v < 0x1CCDE then
                  if v == 0x1CCDD then some ("OUTLINED LATIN CAPITAL LETTER H") else none
                else if 0x1CCDE < v then
                  if v == 0x1CCDF then some ("OUTLINED LATIN CAPITAL LETTER J") else none
                else some ("OUTLINED LATIN CAPITAL LETTER I")
              else if 0x1CCE0 < v then
                if v < 0x1CCE2 then
                  if v == 0x1CCE1 then some ("OUTLINED LATIN CAPITAL LETTER L") else none
                else if 0x1CCE2 < v then
                  if v == 0x1CCE3 then some ("OUTLINED LATIN CAPITAL LETTER N") else none
                else some ("OUTLINED LATIN CAPITAL LETTER M")
              else some ("OUTLINED LATIN CAPITAL LETTER K")
            else some ("OUTLINED LATIN CAPITAL LETTER G")
          else some ("LOWER LEFT QUADRANT STANDING KNIGHT")
        else some ("LOWER LEFT QUADRANT CHESS ROOK")
      else if 0x1CCE4 < v then
        if v < 0x1CD07 then
          if v < 0x1CCF4 then
            if v < 0x1CCEC then
              if v < 0x1CCE8 then
                if v < 0x1CCE6 then
                  if v == 0x1CCE5 then some ("OUTLINED LATIN CAPITAL LETTER P") else none
                else if 0x1CCE6 < v then
                  if v == 0x1CCE7 then some ("OUTLINED LATIN CAPITAL LETTER R") else none
                else some ("OUTLINED LATIN CAPITAL LETTER Q")
              else if 0x1CCE8 < v then
                if v < 0x1CCEA then
                  if v == 0x1CCE9 then some ("OUTLINED LATIN CAPITAL LETTER T") else none
                else if 0x1CCEA < v then
                  if v == 0x1CCEB then some ("OUTLINED LATIN CAPITAL LETTER V") else none
                else some ("OUTLINED LATIN CAPITAL LETTER U")
              else some ("OUTLINED LATIN CAPITAL LETTER S")
            else if 0x1CCEC < v then
              if v < 0x1CCF0 then
                if v < 0x1CCEE then
                  if v == 0x1CCED then some ("OUTLINED LATIN CAPITAL LETTER X") else none
                else if 0x1CCEE < v then
                  if v == 0x1CCEF then some ("OUTLINED LATIN CAPITAL LETTER Z") else none
                else some ("OUTLINED LATIN CAPITAL LETTER Y")
              else if 0x1CCF0 < v then
                if v < 0x1CCF2 then
                  if v == 0x1CCF1 then some ("OUTLINED DIGIT ONE") else none
                else if 0x1CCF2 < v then
                  if v == 0x1CCF3 then some ("OUTLINED DIGIT THREE") else none
                else some ("OUTLINED DIGIT TWO")
              else some ("OUTLINED DIGIT ZERO")
            else some ("OUTLINED LATIN CAPITAL LETTER W")
          else if 0x1CCF4 < v then
            if v < 0x1CCFC then
              if v < 0x1CCF8 then
                if v < 0x1CCF6 then
                  if v == 0x1CCF5 then some ("OUTLINED DIGIT FIVE") else none
                else if 0x1CCF6 < v then
                  if v == 0x1CCF7 then some ("OUTLINED DIGIT SEVEN") else none
                else some ("OUTLINED DIGIT SIX")
              else if 0x1CCF8 < v then
                if v < 0x1CCFA then
                  if v == 0x1CCF9 then some ("OUTLINED DIGIT NINE") else none
                else if 0x1CCFA < v then
                  if v == 0x1CCFB then some ("FLYING SAUCER SYMBOL") else none
                else some ("SNAKE SYMBOL")
              else some ("OUTLINED DIGIT EIGHT")
            else if 0x1CCFC < v then
              if v < 0x1CD03 then
                if v < 0x1CD01 then
                  if v == 0x1CD00 then some ("BLOCK OCTANT-3") else none
                else if 0x1CD01 < v then
                  if v == 0x1CD02 then some ("BLOCK OCTANT-123") else none
                else some ("BLOCK OCTANT-23")
              else if 0x1CD03 < v then
                if v < 0x1CD05 then
                  if v == 0x1CD04 then some ("BLOCK OCTANT-14") else none
                else if 0x1CD05 < v then
                  if v == 0x1CD06 then some ("BLOCK OCTANT-34") else none
                else some ("BLOCK OCTANT-124")
              else some ("BLOCK OCTANT-4")
            else some ("NOSE SYMBOL")
          else some ("OUTLINED DIGIT FOUR")
        else if 0x1CD07 < v then
          if v < 0x1CD17 then
            if v < 0x1CD0F then
              if v < 0x1CD0B then
                if v < 0x1CD09 then
                  if v == 0x1CD08 then some ("BLOCK OCTANT-234") else none
                else if 0x1CD09 < v then
                  if v == 0x1CD0A then some ("BLOCK OCTANT-15") else none
                else some ("BLOCK OCTANT-5")
              else if 0x1CD0B < v then
                if v < 0x1CD0D then
                  if v == 0x1CD0C then some ("BLOCK OCTANT-125") else none
                else if 0x1CD0D < v then
                  if v == 0x1CD0E then some ("BLOCK OCTANT-235") else none
                else some ("BLOCK OCTANT-135")
              else some ("BLOCK OCTANT-25")
            else if 0x1CD0F < v then
              if v < 0x1CD13 then
                if v < 0x1CD11 then
                  if v == 0x1CD10 then some ("BLOCK OCTANT-45") else none
                else if 0x1CD11 < v then
                  if v == 0x1CD12 then some ("BLOCK OCTANT-245") else none
                else some ("BLOCK OCTANT-145")
              else if 0x1CD13 < v then
                if v < 0x1CD15 then
                  if v == 0x1CD14 then some ("BLOCK OCTANT-345") else none
                else if 0x1CD15 < v then
                  if v == 0x1CD16 then some ("BLOCK OCTANT-2345") else none
                else some ("BLOCK OCTANT-1345")
              else some ("BLOCK OCTANT-1245")
            else some ("BLOCK OCTANT-1235")
          else if 0x1CD17 < v then
            if v < 0x1CD1F then
              if v < 0x1CD1B then
                if v < 0x1CD19 then
                  if v == 0x1CD18 then some ("BLOCK OCTANT-6") else none
                else if 0x1CD19 < v then
                  if v == 0x1CD1A then some ("BLOCK OCTANT-26") else none
                else some ("BLOCK OCTANT-16")
              else if 0x1CD1B < v then
                if v < 0x1CD1D then
                  if v == 0x1CD1C then some ("BLOCK OCTANT-36") else none
                else if 0x1CD1D < v then
                  if v == 0x1CD1E then some ("BLOCK OCTANT-236") else none
                else some ("BLOCK OCTANT-136")
              else some ("BLOCK OCTANT-126")
            else if 0x1CD1F < v then
              if v < 0x1CD23 then
                if v < 0x1CD21 then
                  if v == 0x1CD20 then some ("BLOCK OCTANT-146") else none
                else if 0x1CD21 < v then
                  if v == 0x1CD22 then some ("BLOCK OCTANT-1246") else none
                else some ("BLOCK OCTANT-246")
              else if 0x1CD23 < v then
                if v < 0x1CD25 then
                  if v == 0x1CD24 then some ("BLOCK OCTANT-1346") else none
                else if 0x1CD25 < v then
                  if v == 0x1CD26 then some ("BLOCK OCTANT-12346") else none
                else some ("BLOCK OCTANT-2346")
              else some ("BLOCK OCTANT-346")
            else some ("BLOCK OCTANT-1236")
          else some ("BLOCK OCTANT-12345")
        else some ("BLOCK OCTANT-134")
      else some ("OUTLINED LATIN CAPITAL LETTER O")
    else some ("LEFT HALF FLYING SAUCER")
  else some ("SEPARATED BLOCK QUADRANT-3")

end Unicode.TableLookupTables.Name.Chunk59
