/- This file is generated by table-generators/makeTablesForLookup. -/
module

public import UnicodeBasic.TableLookupTables.Name.DuplicatedReturnedStrings

@[expose] public section

namespace Unicode.TableLookupTables.Name.Chunk9

@[inline_if_reduce, reducible]
def getInsideSparseRangeValueTable (v : UInt32) : Option String :=
  if v < 0x1577 then
    if v < 0x14F7 then
      if v < 0x14B7 then
        if v < 0x1497 then
          if v < 0x1487 then
            if v < 0x147F then
              if v < 0x147B then
                if v < 0x1479 then
                  if v < 0x1478 then
                    if v == 0x1477 then some ("CANADIAN SYLLABICS WEST-CREE KWI") else none
                  else if 0x1478 < v then
                    none
                  else some ("CANADIAN SYLLABICS KWII")
                else if 0x1479 < v then
                  if v == 0x147A then some ("CANADIAN SYLLABICS KWO") else none
                else some ("CANADIAN SYLLABICS WEST-CREE KWII")
              else if 0x147B < v then
                if v < 0x147D then
                  if v == 0x147C then some ("CANADIAN SYLLABICS KWOO") else none
                else if 0x147D < v then
                  if v == 0x147E then some ("CANADIAN SYLLABICS KWA") else none
                else some ("CANADIAN SYLLABICS WEST-CREE KWOO")
              else some ("CANADIAN SYLLABICS WEST-CREE KWO")
            else if 0x147F < v then
              if v < 0x1483 then
                if v < 0x1481 then
                  if v == 0x1480 then some ("CANADIAN SYLLABICS KWAA") else none
                else if 0x1481 < v then
                  if v == 0x1482 then some ("CANADIAN SYLLABICS NASKAPI KWAA") else none
                else some ("CANADIAN SYLLABICS WEST-CREE KWAA")
              else if 0x1483 < v then
                if v < 0x1485 then
                  if v == 0x1484 then some ("CANADIAN SYLLABICS KW") else none
                else if 0x1485 < v then
                  if v == 0x1486 then some ("CANADIAN SYLLABICS SOUTH-SLAVEY KIH") else none
                else some ("CANADIAN SYLLABICS SOUTH-SLAVEY KEH")
              else some ("CANADIAN SYLLABICS K")
            else some ("CANADIAN SYLLABICS WEST-CREE KWA")
          else if 0x1487 < v then
            if v < 0x148F then
              if v < 0x148B then
                if v < 0x1489 then
                  if v == 0x1488 then some ("CANADIAN SYLLABICS SOUTH-SLAVEY KAH") else none
                else if 0x1489 < v then
                  if v == 0x148A then some ("CANADIAN SYLLABICS CAAI") else none
                else some ("CANADIAN SYLLABICS CE")
              else if 0x148B < v then
                if v < 0x148D then
                  if v == 0x148C then some ("CANADIAN SYLLABICS CII") else none
                else if 0x148D < v then
                  if v == 0x148E then some ("CANADIAN SYLLABICS COO") else none
                else some ("CANADIAN SYLLABICS CO")
              else some ("CANADIAN SYLLABICS CI")
            else if 0x148F < v then
              if v < 0x1493 then
                if v < 0x1491 then
                  if v == 0x1490 then some ("CANADIAN SYLLABICS CA") else none
                else if 0x1491 < v then
                  if v == 0x1492 then some ("CANADIAN SYLLABICS CWE") else none
                else some ("CANADIAN SYLLABICS CAA")
              else if 0x1493 < v then
                if v < 0x1495 then
                  if v == 0x1494 then some ("CANADIAN SYLLABICS CWI") else none
                else if 0x1495 < v then
                  if v == 0x1496 then some ("CANADIAN SYLLABICS CWII") else none
                else some ("CANADIAN SYLLABICS WEST-CREE CWI")
              else some ("CANADIAN SYLLABICS WEST-CREE CWE")
            else some ("CANADIAN SYLLABICS Y-CREE COO")
          else some ("CANADIAN SYLLABICS SOUTH-SLAVEY KOH")
        else if 0x1497 < v then
          if v < 0x14A7 then
            if v < 0x149F then
              if v < 0x149B then
                if v < 0x1499 then
                  if v == 0x1498 then some ("CANADIAN SYLLABICS CWO") else none
                else if 0x1499 < v then
                  if v == 0x149A then some ("CANADIAN SYLLABICS CWOO") else none
                else some ("CANADIAN SYLLABICS WEST-CREE CWO")
              else if 0x149B < v then
                if v < 0x149D then
                  if v == 0x149C then some ("CANADIAN SYLLABICS CWA") else none
                else if 0x149D < v then
                  if v == 0x149E then some ("CANADIAN SYLLABICS CWAA") else none
                else some ("CANADIAN SYLLABICS WEST-CREE CWA")
              else some ("CANADIAN SYLLABICS WEST-CREE CWOO")
            else if 0x149F < v then
              if v < 0x14A3 then
                if v < 0x14A1 then
                  if v == 0x14A0 then some ("CANADIAN SYLLABICS NASKAPI CWAA") else none
                else if 0x14A1 < v then
                  if v == 0x14A2 then some ("CANADIAN SYLLABICS SAYISI TH") else none
                else some ("CANADIAN SYLLABICS C")
              else if 0x14A3 < v then
                if v < 0x14A5 then
                  if v == 0x14A4 then some ("CANADIAN SYLLABICS MAAI") else none
                else if 0x14A5 < v then
                  if v == 0x14A6 then some ("CANADIAN SYLLABICS MII") else none
                else some ("CANADIAN SYLLABICS MI")
              else some ("CANADIAN SYLLABICS ME")
            else some ("CANADIAN SYLLABICS WEST-CREE CWAA")
          else if 0x14A7 < v then
            if v < 0x14AF then
              if v < 0x14AB then
                if v < 0x14A9 then
                  if v == 0x14A8 then some ("CANADIAN SYLLABICS MOO") else none
                else if 0x14A9 < v then
                  if v == 0x14AA then some ("CANADIAN SYLLABICS MA") else none
                else some ("CANADIAN SYLLABICS Y-CREE MOO")
              else if 0x14AB < v then
                if v < 0x14AD then
                  if v == 0x14AC then some ("CANADIAN SYLLABICS MWE") else none
                else if 0x14AD < v then
                  if v == 0x14AE then some ("CANADIAN SYLLABICS MWI") else none
                else some ("CANADIAN SYLLABICS WEST-CREE MWE")
              else some ("CANADIAN SYLLABICS MAA")
            else if 0x14AF < v then
              if v < 0x14B3 then
                if v < 0x14B1 then
                  if v == 0x14B0 then some ("CANADIAN SYLLABICS MWII") else none
                else if 0x14B1 < v then
                  if v == 0x14B2 then some ("CANADIAN SYLLABICS MWO") else none
                else some ("CANADIAN SYLLABICS WEST-CREE MWII")
              else if 0x14B3 < v then
                if v < 0x14B5 then
                  if v == 0x14B4 then some ("CANADIAN SYLLABICS MWOO") else none
                else if 0x14B5 < v then
                  if v == 0x14B6 then some ("CANADIAN SYLLABICS MWA") else none
                else some ("CANADIAN SYLLABICS WEST-CREE MWOO")
              else some ("CANADIAN SYLLABICS WEST-CREE MWO")
            else some ("CANADIAN SYLLABICS WEST-CREE MWI")
          else some ("CANADIAN SYLLABICS MO")
        else some ("CANADIAN SYLLABICS WEST-CREE CWII")
      else if 0x14B7 < v then
        if v < 0x14D7 then
          if v < 0x14C7 then
            if v < 0x14BF then
              if v < 0x14BB then
                if v < 0x14B9 then
                  if v == 0x14B8 then some ("CANADIAN SYLLABICS MWAA") else none
                else if 0x14B9 < v then
                  if v == 0x14BA then some ("CANADIAN SYLLABICS NASKAPI MWAA") else none
                else some ("CANADIAN SYLLABICS WEST-CREE MWAA")
              else if 0x14BB < v then
                if v < 0x14BD then
                  if v == 0x14BC then some ("CANADIAN SYLLABICS WEST-CREE M") else none
                else if 0x14BD < v then
                  if v == 0x14BE then some ("CANADIAN SYLLABICS ATHAPASCAN M") else none
                else some ("CANADIAN SYLLABICS MH")
              else some ("CANADIAN SYLLABICS M")
            else if 0x14BF < v then
              if v < 0x14C3 then
                if v < 0x14C1 then
                  if v == 0x14C0 then some ("CANADIAN SYLLABICS NE") else none
                else if 0x14C1 < v then
                  if v == 0x14C2 then some ("CANADIAN SYLLABICS NI") else none
                else some ("CANADIAN SYLLABICS NAAI")
              else if 0x14C3 < v then
                if v < 0x14C5 then
                  if v == 0x14C4 then some ("CANADIAN SYLLABICS NO") else none
                else if 0x14C5 < v then
                  if v == 0x14C6 then some ("CANADIAN SYLLABICS Y-CREE NOO") else none
                else some ("CANADIAN SYLLABICS NOO")
              else some ("CANADIAN SYLLABICS NII")
            else some ("CANADIAN SYLLABICS SAYISI M")
          else if 0x14C7 < v then
            if v < 0x14CF then
              if v < 0x14CB then
                if v < 0x14C9 then
                  if v == 0x14C8 then some ("CANADIAN SYLLABICS NAA") else none
                else if 0x14C9 < v then
                  if v == 0x14CA then some ("CANADIAN SYLLABICS WEST-CREE NWE") else none
                else some ("CANADIAN SYLLABICS NWE")
              else if 0x14CB < v then
                if v < 0x14CD then
                  if v == 0x14CC then some ("CANADIAN SYLLABICS WEST-CREE NWA") else none
                else if 0x14CD < v then
                  if v == 0x14CE then some ("CANADIAN SYLLABICS WEST-CREE NWAA") else none
                else some ("CANADIAN SYLLABICS NWAA")
              else some ("CANADIAN SYLLABICS NWA")
            else if 0x14CF < v then
              if v < 0x14D3 then
                if v < 0x14D1 then
                  if v == 0x14D0 then some ("CANADIAN SYLLABICS N") else none
                else if 0x14D1 < v then
                  if v == 0x14D2 then some ("CANADIAN SYLLABICS NH") else none
                else some ("CANADIAN SYLLABICS CARRIER NG")
              else if 0x14D3 < v then
                if v < 0x14D5 then
                  if v == 0x14D4 then some ("CANADIAN SYLLABICS LAAI") else none
                else if 0x14D5 < v then
                  if v == 0x14D6 then some ("CANADIAN SYLLABICS LII") else none
                else some ("CANADIAN SYLLABICS LI")
              else some ("CANADIAN SYLLABICS LE")
            else some ("CANADIAN SYLLABICS NASKAPI NWAA")
          else some ("CANADIAN SYLLABICS NA")
        else if 0x14D7 < v then
          if v < 0x14E7 then
            if v < 0x14DF then
              if v < 0x14DB then
                if v < 0x14D9 then
                  if v == 0x14D8 then some ("CANADIAN SYLLABICS LOO") else none
                else if 0x14D9 < v then
                  if v == 0x14DA then some ("CANADIAN SYLLABICS LA") else none
                else some ("CANADIAN SYLLABICS Y-CREE LOO")
              else if 0x14DB < v then
                if v < 0x14DD then
                  if v == 0x14DC then some ("CANADIAN SYLLABICS LWE") else none
                else if 0x14DD < v then
                  if v == 0x14DE then some ("CANADIAN SYLLABICS LWI") else none
                else some ("CANADIAN SYLLABICS WEST-CREE LWE")
              else some ("CANADIAN SYLLABICS LAA")
            else if 0x14DF < v then
              if v < 0x14E3 then
                if v < 0x14E1 then
                  if v == 0x14E0 then some ("CANADIAN SYLLABICS LWII") else none
                else if 0x14E1 < v then
                  if v == 0x14E2 then some ("CANADIAN SYLLABICS LWO") else none
                else some ("CANADIAN SYLLABICS WEST-CREE LWII")
              else if 0x14E3 < v then
                if v < 0x14E5 then
                  if v == 0x14E4 then some ("CANADIAN SYLLABICS LWOO") else none
                else if 0x14E5 < v then
                  if v == 0x14E6 then some ("CANADIAN SYLLABICS LWA") else none
                else some ("CANADIAN SYLLABICS WEST-CREE LWOO")
              else some ("CANADIAN SYLLABICS WEST-CREE LWO")
            else some ("CANADIAN SYLLABICS WEST-CREE LWI")
          else if 0x14E7 < v then
            if v < 0x14EF then
              if v < 0x14EB then
                if v < 0x14E9 then
                  if v == 0x14E8 then some ("CANADIAN SYLLABICS LWAA") else none
                else if 0x14E9 < v then
                  if v == 0x14EA then some ("CANADIAN SYLLABICS L") else none
                else some ("CANADIAN SYLLABICS WEST-CREE LWAA")
              else if 0x14EB < v then
                if v < 0x14ED then
                  if v == 0x14EC then some ("CANADIAN SYLLABICS MEDIAL L") else none
                else if 0x14ED < v then
                  if v == 0x14EE then some ("CANADIAN SYLLABICS SAAI") else none
                else some ("CANADIAN SYLLABICS SE")
              else some ("CANADIAN SYLLABICS WEST-CREE L")
            else if 0x14EF < v then
              if v < 0x14F3 then
                if v < 0x14F1 then
                  if v == 0x14F0 then some ("CANADIAN SYLLABICS SII") else none
                else if 0x14F1 < v then
                  if v == 0x14F2 then some ("CANADIAN SYLLABICS SOO") else none
                else some ("CANADIAN SYLLABICS SO")
              else if 0x14F3 < v then
                if v < 0x14F5 then
                  if v == 0x14F4 then some ("CANADIAN SYLLABICS SA") else none
                else if 0x14F5 < v then
                  if v == 0x14F6 then some ("CANADIAN SYLLABICS SWE") else none
                else some ("CANADIAN SYLLABICS SAA")
              else some ("CANADIAN SYLLABICS Y-CREE SOO")
            else some ("CANADIAN SYLLABICS SI")
          else some ("CANADIAN SYLLABICS WEST-CREE LWA")
        else some ("CANADIAN SYLLABICS LO")
      else some ("CANADIAN SYLLABICS WEST-CREE MWA")
    else if 0x14F7 < v then
      if v < 0x1537 then
        if v < 0x1517 then
          if v < 0x1507 then
            if v < 0x14FF then
              if v < 0x14FB then
                if v < 0x14F9 then
                  if v == 0x14F8 then some ("CANADIAN SYLLABICS SWI") else none
                else if 0x14F9 < v then
                  if v == 0x14FA then some ("CANADIAN SYLLABICS SWII") else none
                else some ("CANADIAN SYLLABICS WEST-CREE SWI")
              else if 0x14FB < v then
                if v < 0x14FD then
                  if v == 0x14FC then some ("CANADIAN SYLLABICS SWO") else none
                else if 0x14FD < v then
                  if v == 0x14FE then some ("CANADIAN SYLLABICS SWOO") else none
                else some ("CANADIAN SYLLABICS WEST-CREE SWO")
              else some ("CANADIAN SYLLABICS WEST-CREE SWII")
            else if 0x14FF < v then
              if v < 0x1503 then
                if v < 0x1501 then
                  if v == 0x1500 then some ("CANADIAN SYLLABICS SWA") else none
                else if 0x1501 < v then
                  if v == 0x1502 then some ("CANADIAN SYLLABICS SWAA") else none
                else some ("CANADIAN SYLLABICS WEST-CREE SWA")
              else if 0x1503 < v then
                if v < 0x1505 then
                  if v == 0x1504 then some ("CANADIAN SYLLABICS NASKAPI SWAA") else none
                else if 0x1505 < v then
                  if v == 0x1506 then some ("CANADIAN SYLLABICS ATHAPASCAN S") else none
                else some ("CANADIAN SYLLABICS S")
              else some ("CANADIAN SYLLABICS WEST-CREE SWAA")
            else some ("CANADIAN SYLLABICS WEST-CREE SWOO")
          else if 0x1507 < v then
            if v < 0x150F then
              if v < 0x150B then
                if v < 0x1509 then
                  if v == 0x1508 then some ("CANADIAN SYLLABICS BLACKFOOT S") else none
                else if 0x1509 < v then
                  if v == 0x150A then some ("CANADIAN SYLLABICS NASKAPI SKW") else none
                else some ("CANADIAN SYLLABICS MOOSE-CREE SK")
              else if 0x150B < v then
                if v < 0x150D then
                  if v == 0x150C then some ("CANADIAN SYLLABICS NASKAPI SPWA") else none
                else if 0x150D < v then
                  if v == 0x150E then some ("CANADIAN SYLLABICS NASKAPI SKWA") else none
                else some ("CANADIAN SYLLABICS NASKAPI STWA")
              else some ("CANADIAN SYLLABICS NASKAPI S-W")
            else if 0x150F < v then
              if v < 0x1513 then
                if v < 0x1511 then
                  if v == 0x1510 then some ("CANADIAN SYLLABICS SHE") else none
                else if 0x1511 < v then
                  if v == 0x1512 then some ("CANADIAN SYLLABICS SHII") else none
                else some ("CANADIAN SYLLABICS SHI")
              else if 0x1513 < v then
                if v < 0x1515 then
                  if v == 0x1514 then some ("CANADIAN SYLLABICS SHOO") else none
                else if 0x1515 < v then
                  if v == 0x1516 then some ("CANADIAN SYLLABICS SHAA") else none
                else some ("CANADIAN SYLLABICS SHA")
              else some ("CANADIAN SYLLABICS SHO")
            else some ("CANADIAN SYLLABICS NASKAPI SCWA")
          else some ("CANADIAN SYLLABICS SW")
        else if 0x1517 < v then
          if v < 0x1527 then
            if v < 0x151F then
              if v < 0x151B then
                if v < 0x1519 then
                  if v == 0x1518 then some ("CANADIAN SYLLABICS WEST-CREE SHWE") else none
                else if 0x1519 < v then
                  if v == 0x151A then some ("CANADIAN SYLLABICS WEST-CREE SHWI") else none
                else some ("CANADIAN SYLLABICS SHWI")
              else if 0x151B < v then
                if v < 0x151D then
                  if v == 0x151C then some ("CANADIAN SYLLABICS WEST-CREE SHWII") else none
                else if 0x151D < v then
                  if v == 0x151E then some ("CANADIAN SYLLABICS WEST-CREE SHWO") else none
                else some ("CANADIAN SYLLABICS SHWO")
              else some ("CANADIAN SYLLABICS SHWII")
            else if 0x151F < v then
              if v < 0x1523 then
                if v < 0x1521 then
                  if v == 0x1520 then some ("CANADIAN SYLLABICS WEST-CREE SHWOO") else none
                else if 0x1521 < v then
                  if v == 0x1522 then some ("CANADIAN SYLLABICS WEST-CREE SHWA") else none
                else some ("CANADIAN SYLLABICS SHWA")
              else if 0x1523 < v then
                if v < 0x1525 then
                  if v == 0x1524 then some ("CANADIAN SYLLABICS WEST-CREE SHWAA") else none
                else if 0x1525 < v then
                  if v == 0x1526 then some ("CANADIAN SYLLABICS YE") else none
                else some ("CANADIAN SYLLABICS SH")
              else some ("CANADIAN SYLLABICS SHWAA")
            else some ("CANADIAN SYLLABICS SHWOO")
          else if 0x1527 < v then
            if v < 0x152F then
              if v < 0x152B then
                if v < 0x1529 then
                  if v == 0x1528 then some ("CANADIAN SYLLABICS YI") else none
                else if 0x1529 < v then
                  if v == 0x152A then some ("CANADIAN SYLLABICS YO") else none
                else some ("CANADIAN SYLLABICS YII")
              else if 0x152B < v then
                if v < 0x152D then
                  if v == 0x152C then some ("CANADIAN SYLLABICS Y-CREE YOO") else none
                else if 0x152D < v then
                  if v == 0x152E then some ("CANADIAN SYLLABICS YAA") else none
                else some ("CANADIAN SYLLABICS YA")
              else some ("CANADIAN SYLLABICS YOO")
            else if 0x152F < v then
              if v < 0x1533 then
                if v < 0x1531 then
                  if v == 0x1530 then some ("CANADIAN SYLLABICS WEST-CREE YWE") else none
                else if 0x1531 < v then
                  if v == 0x1532 then some ("CANADIAN SYLLABICS WEST-CREE YWI") else none
                else some ("CANADIAN SYLLABICS YWI")
              else if 0x1533 < v then
                if v < 0x1535 then
                  if v == 0x1534 then some ("CANADIAN SYLLABICS WEST-CREE YWII") else none
                else if 0x1535 < v then
                  if v == 0x1536 then some ("CANADIAN SYLLABICS WEST-CREE YWO") else none
                else some ("CANADIAN SYLLABICS YWO")
              else some ("CANADIAN SYLLABICS YWII")
            else some ("CANADIAN SYLLABICS YWE")
          else some ("CANADIAN SYLLABICS YAAI")
        else some ("CANADIAN SYLLABICS SHWE")
      else if 0x1537 < v then
        if v < 0x1557 then
          if v < 0x1547 then
            if v < 0x153F then
              if v < 0x153B then
                if v < 0x1539 then
                  if v == 0x1538 then some ("CANADIAN SYLLABICS WEST-CREE YWOO") else none
                else if 0x1539 < v then
                  if v == 0x153A then some ("CANADIAN SYLLABICS WEST-CREE YWA") else none
                else some ("CANADIAN SYLLABICS YWA")
              else if 0x153B < v then
                if v < 0x153D then
                  if v == 0x153C then some ("CANADIAN SYLLABICS WEST-CREE YWAA") else none
                else if 0x153D < v then
                  if v == 0x153E then some ("CANADIAN SYLLABICS Y") else none
                else some ("CANADIAN SYLLABICS NASKAPI YWAA")
              else some ("CANADIAN SYLLABICS YWAA")
            else if 0x153F < v then
              if v < 0x1543 then
                if v < 0x1541 then
                  if v == 0x1540 then some ("CANADIAN SYLLABICS WEST-CREE Y") else none
                else if 0x1541 < v then
                  if v == 0x1542 then some ("CANADIAN SYLLABICS RE") else none
                else some ("CANADIAN SYLLABICS SAYISI YI")
              else if 0x1543 < v then
                if v < 0x1545 then
                  if v == 0x1544 then some ("CANADIAN SYLLABICS WEST-CREE LE") else none
                else if 0x1545 < v then
                  if v == 0x1546 then some ("CANADIAN SYLLABICS RI") else none
                else some ("CANADIAN SYLLABICS RAAI")
              else some ("CANADIAN SYLLABICS R-CREE RE")
            else some ("CANADIAN SYLLABICS BIBLE-CREE Y")
          else if 0x1547 < v then
            if v < 0x154F then
              if v < 0x154B then
                if v < 0x1549 then
                  if v == 0x1548 then some ("CANADIAN SYLLABICS RO") else none
                else if 0x1549 < v then
                  if v == 0x154A then some ("CANADIAN SYLLABICS WEST-CREE LO") else none
                else some ("CANADIAN SYLLABICS ROO")
              else if 0x154B < v then
                if v < 0x154D then
                  if v == 0x154C then some ("CANADIAN SYLLABICS RAA") else none
                else if 0x154D < v then
                  if v == 0x154E then some ("CANADIAN SYLLABICS RWAA") else none
                else some ("CANADIAN SYLLABICS WEST-CREE LA")
              else some ("CANADIAN SYLLABICS RA")
            else if 0x154F < v then
              if v < 0x1553 then
                if v < 0x1551 then
                  if v == 0x1550 then some ("CANADIAN SYLLABICS R") else none
                else if 0x1551 < v then
                  if v == 0x1552 then some ("CANADIAN SYLLABICS MEDIAL R") else none
                else some ("CANADIAN SYLLABICS WEST-CREE R")
              else if 0x1553 < v then
                if v < 0x1555 then
                  if v == 0x1554 then some ("CANADIAN SYLLABICS FAAI") else none
                else if 0x1555 < v then
                  if v == 0x1556 then some ("CANADIAN SYLLABICS FII") else none
                else some ("CANADIAN SYLLABICS FI")
              else some ("CANADIAN SYLLABICS FE")
            else some ("CANADIAN SYLLABICS WEST-CREE RWAA")
          else some ("CANADIAN SYLLABICS RII")
        else if 0x1557 < v then
          if v < 0x1567 then
            if v < 0x155F then
              if v < 0x155B then
                if v < 0x1559 then
                  if v == 0x1558 then some ("CANADIAN SYLLABICS FOO") else none
                else if 0x1559 < v then
                  if v == 0x155A then some ("CANADIAN SYLLABICS FAA") else none
                else some ("CANADIAN SYLLABICS FA")
              else if 0x155B < v then
                if v < 0x155D then
                  if v == 0x155C then some ("CANADIAN SYLLABICS WEST-CREE FWAA") else none
                else if 0x155D < v then
                  if v == 0x155E then some ("CANADIAN SYLLABICS THE") else none
                else some ("CANADIAN SYLLABICS F")
              else some ("CANADIAN SYLLABICS FWAA")
            else if 0x155F < v then
              if v < 0x1563 then
                if v < 0x1561 then
                  if v == 0x1560 then some ("CANADIAN SYLLABICS THI") else none
                else if 0x1561 < v then
                  if v == 0x1562 then some ("CANADIAN SYLLABICS THII") else none
                else some ("CANADIAN SYLLABICS N-CREE THI")
              else if 0x1563 < v then
                if v < 0x1565 then
                  if v == 0x1564 then some ("CANADIAN SYLLABICS THO") else none
                else if 0x1565 < v then
                  if v == 0x1566 then some ("CANADIAN SYLLABICS THA") else none
                else some ("CANADIAN SYLLABICS THOO")
              else some ("CANADIAN SYLLABICS N-CREE THII")
            else some ("CANADIAN SYLLABICS N-CREE THE")
          else if 0x1567 < v then
            if v < 0x156F then
              if v < 0x156B then
                if v < 0x1569 then
                  if v == 0x1568 then some ("CANADIAN SYLLABICS THWAA") else none
                else if 0x1569 < v then
                  if v == 0x156A then some ("CANADIAN SYLLABICS TH") else none
                else some ("CANADIAN SYLLABICS WEST-CREE THWAA")
              else if 0x156B < v then
                if v < 0x156D then
                  if v == 0x156C then some ("CANADIAN SYLLABICS TTHI") else none
                else if 0x156D < v then
                  if v == 0x156E then some ("CANADIAN SYLLABICS TTHA") else none
                else some ("CANADIAN SYLLABICS TTHO")
              else some ("CANADIAN SYLLABICS TTHE")
            else if 0x156F < v then
              if v < 0x1573 then
                if v < 0x1571 then
                  if v == 0x1570 then some ("CANADIAN SYLLABICS TYE") else none
                else if 0x1571 < v then
                  if v == 0x1572 then some ("CANADIAN SYLLABICS TYO") else none
                else some ("CANADIAN SYLLABICS TYI")
              else if 0x1573 < v then
                if v < 0x1575 then
                  if v == 0x1574 then some ("CANADIAN SYLLABICS NUNAVIK HE") else none
                else if 0x1575 < v then
                  if v == 0x1576 then some ("CANADIAN SYLLABICS NUNAVIK HII") else none
                else some ("CANADIAN SYLLABICS NUNAVIK HI")
              else some ("CANADIAN SYLLABICS TYA")
            else some ("CANADIAN SYLLABICS TTH")
          else some ("CANADIAN SYLLABICS THAA")
        else some ("CANADIAN SYLLABICS FO")
      else some ("CANADIAN SYLLABICS YWOO")
    else some ("CANADIAN SYLLABICS WEST-CREE SWE")
  else if 0x1577 < v then
    if v < 0x15F7 then
      if v < 0x15B7 then
        if v < 0x1597 then
          if v < 0x1587 then
            if v < 0x157F then
              if v < 0x157B then
                if v < 0x1579 then
                  if v == 0x1578 then some ("CANADIAN SYLLABICS NUNAVIK HOO") else none
                else if 0x1579 < v then
                  if v == 0x157A then some ("CANADIAN SYLLABICS NUNAVIK HAA") else none
                else some ("CANADIAN SYLLABICS NUNAVIK HA")
              else if 0x157B < v then
                if v < 0x157D then
                  if v == 0x157C then some ("CANADIAN SYLLABICS NUNAVUT H") else none
                else if 0x157D < v then
                  if v == 0x157E then some ("CANADIAN SYLLABICS QAAI") else none
                else some ("CANADIAN SYLLABICS HK")
              else some ("CANADIAN SYLLABICS NUNAVIK H")
            else if 0x157F < v then
              if v < 0x1583 then
                if v < 0x1581 then
                  if v == 0x1580 then some ("CANADIAN SYLLABICS QII") else none
                else if 0x1581 < v then
                  if v == 0x1582 then some ("CANADIAN SYLLABICS QOO") else none
                else some ("CANADIAN SYLLABICS QO")
              else if 0x1583 < v then
                if v < 0x1585 then
                  if v == 0x1584 then some ("CANADIAN SYLLABICS QAA") else none
                else if 0x1585 < v then
                  if v == 0x1586 then some ("CANADIAN SYLLABICS TLHE") else none
                else some ("CANADIAN SYLLABICS Q")
              else some ("CANADIAN SYLLABICS QA")
            else some ("CANADIAN SYLLABICS QI")
          else if 0x1587 < v then
            if v < 0x158F then
              if v < 0x158B then
                if v < 0x1589 then
                  if v == 0x1588 then some ("CANADIAN SYLLABICS TLHO") else none
                else if 0x1589 < v then
                  if v == 0x158A then some ("CANADIAN SYLLABICS WEST-CREE RE") else none
                else some ("CANADIAN SYLLABICS TLHA")
              else if 0x158B < v then
                if v < 0x158D then
                  if v == 0x158C then some ("CANADIAN SYLLABICS WEST-CREE RO") else none
                else if 0x158D < v then
                  if v == 0x158E then some ("CANADIAN SYLLABICS NGAAI") else none
                else some ("CANADIAN SYLLABICS WEST-CREE RA")
              else some ("CANADIAN SYLLABICS WEST-CREE RI")
            else if 0x158F < v then
              if v < 0x1593 then
                if v < 0x1591 then
                  if v == 0x1590 then some ("CANADIAN SYLLABICS NGII") else none
                else if 0x1591 < v then
                  if v == 0x1592 then some ("CANADIAN SYLLABICS NGOO") else none
                else some ("CANADIAN SYLLABICS NGO")
              else if 0x1593 < v then
                if v < 0x1595 then
                  if v == 0x1594 then some ("CANADIAN SYLLABICS NGAA") else none
                else if 0x1595 < v then
                  if v == 0x1596 then some ("CANADIAN SYLLABICS NNG") else none
                else some ("CANADIAN SYLLABICS NG")
              else some ("CANADIAN SYLLABICS NGA")
            else some ("CANADIAN SYLLABICS NGI")
          else some ("CANADIAN SYLLABICS TLHI")
        else if 0x1597 < v then
          if v < 0x15A7 then
            if v < 0x159F then
              if v < 0x159B then
                if v < 0x1599 then
                  if v == 0x1598 then some ("CANADIAN SYLLABICS SAYISI SHI") else none
                else if 0x1599 < v then
                  if v == 0x159A then some ("CANADIAN SYLLABICS SAYISI SHA") else none
                else some ("CANADIAN SYLLABICS SAYISI SHO")
              else if 0x159B < v then
                if v < 0x159D then
                  if v == 0x159C then some ("CANADIAN SYLLABICS WOODS-CREE THI") else none
                else if 0x159D < v then
                  if v == 0x159E then some ("CANADIAN SYLLABICS WOODS-CREE THA") else none
                else some ("CANADIAN SYLLABICS WOODS-CREE THO")
              else some ("CANADIAN SYLLABICS WOODS-CREE THE")
            else if 0x159F < v then
              if v < 0x15A3 then
                if v < 0x15A1 then
                  if v == 0x15A0 then some ("CANADIAN SYLLABICS LHI") else none
                else if 0x15A1 < v then
                  if v == 0x15A2 then some ("CANADIAN SYLLABICS LHO") else none
                else some ("CANADIAN SYLLABICS LHII")
              else if 0x15A3 < v then
                if v < 0x15A5 then
                  if v == 0x15A4 then some ("CANADIAN SYLLABICS LHA") else none
                else if 0x15A5 < v then
                  if v == 0x15A6 then some ("CANADIAN SYLLABICS LH") else none
                else some ("CANADIAN SYLLABICS LHAA")
              else some ("CANADIAN SYLLABICS LHOO")
            else some ("CANADIAN SYLLABICS WOODS-CREE TH")
          else if 0x15A7 < v then
            if v < 0x15AF then
              if v < 0x15AB then
                if v < 0x15A9 then
                  if v == 0x15A8 then some ("CANADIAN SYLLABICS TH-CREE THI") else none
                else if 0x15A9 < v then
                  if v == 0x15AA then some ("CANADIAN SYLLABICS TH-CREE THO") else none
                else some ("CANADIAN SYLLABICS TH-CREE THII")
              else if 0x15AB < v then
                if v < 0x15AD then
                  if v == 0x15AC then some ("CANADIAN SYLLABICS TH-CREE THA") else none
                else if 0x15AD < v then
                  if v == 0x15AE then some ("CANADIAN SYLLABICS TH-CREE TH") else none
                else some ("CANADIAN SYLLABICS TH-CREE THAA")
              else some ("CANADIAN SYLLABICS TH-CREE THOO")
            else if 0x15AF < v then
              if v < 0x15B3 then
                if v < 0x15B1 then
                  if v == 0x15B0 then some ("CANADIAN SYLLABICS BLACKFOOT E") else none
                else if 0x15B1 < v then
                  if v == 0x15B2 then some ("CANADIAN SYLLABICS BLACKFOOT O") else none
                else some ("CANADIAN SYLLABICS BLACKFOOT I")
              else if 0x15B3 < v then
                if v < 0x15B5 then
                  if v == 0x15B4 then some ("CANADIAN SYLLABICS BLACKFOOT WE") else none
                else if 0x15B5 < v then
                  if v == 0x15B6 then some ("CANADIAN SYLLABICS BLACKFOOT WO") else none
                else some ("CANADIAN SYLLABICS BLACKFOOT WI")
              else some ("CANADIAN SYLLABICS BLACKFOOT A")
            else some ("CANADIAN SYLLABICS AIVILIK B")
          else some ("CANADIAN SYLLABICS TH-CREE THE")
        else some ("CANADIAN SYLLABICS SAYISI SHE")
      else if 0x15B7 < v then
        if v < 0x15D7 then
          if v < 0x15C7 then
            if v < 0x15BF then
              if v < 0x15BB then
                if v < 0x15B9 then
                  if v == 0x15B8 then some ("CANADIAN SYLLABICS BLACKFOOT NE") else none
                else if 0x15B9 < v then
                  if v == 0x15BA then some ("CANADIAN SYLLABICS BLACKFOOT NO") else none
                else some ("CANADIAN SYLLABICS BLACKFOOT NI")
              else if 0x15BB < v then
                if v < 0x15BD then
                  if v == 0x15BC then some ("CANADIAN SYLLABICS BLACKFOOT KE") else none
                else if 0x15BD < v then
                  if v == 0x15BE then some ("CANADIAN SYLLABICS BLACKFOOT KO") else none
                else some ("CANADIAN SYLLABICS BLACKFOOT KI")
              else some ("CANADIAN SYLLABICS BLACKFOOT NA")
            else if 0x15BF < v then
              if v < 0x15C3 then
                if v < 0x15C1 then
                  if v == 0x15C0 then some ("CANADIAN SYLLABICS SAYISI HE") else none
                else if 0x15C1 < v then
                  if v == 0x15C2 then some ("CANADIAN SYLLABICS SAYISI HO") else none
                else some ("CANADIAN SYLLABICS SAYISI HI")
              else if 0x15C3 < v then
                if v < 0x15C5 then
                  if v == 0x15C4 then some ("CANADIAN SYLLABICS CARRIER GHU") else none
                else if 0x15C5 < v then
                  if v == 0x15C6 then some ("CANADIAN SYLLABICS CARRIER GHE") else none
                else some ("CANADIAN SYLLABICS CARRIER GHO")
              else some ("CANADIAN SYLLABICS SAYISI HA")
            else some ("CANADIAN SYLLABICS BLACKFOOT KA")
          else if 0x15C7 < v then
            if v < 0x15CF then
              if v < 0x15CB then
                if v < 0x15C9 then
                  if v == 0x15C8 then some ("CANADIAN SYLLABICS CARRIER GHI") else none
                else if 0x15C9 < v then
                  if v == 0x15CA then some ("CANADIAN SYLLABICS CARRIER RU") else none
                else some ("CANADIAN SYLLABICS CARRIER GHA")
              else if 0x15CB < v then
                if v < 0x15CD then
                  if v == 0x15CC then some ("CANADIAN SYLLABICS CARRIER RE") else none
                else if 0x15CD < v then
                  if v == 0x15CE then some ("CANADIAN SYLLABICS CARRIER RI") else none
                else some ("CANADIAN SYLLABICS CARRIER REE")
              else some ("CANADIAN SYLLABICS CARRIER RO")
            else if 0x15CF < v then
              if v < 0x15D3 then
                if v < 0x15D1 then
                  if v == 0x15D0 then some ("CANADIAN SYLLABICS CARRIER WU") else none
                else if 0x15D1 < v then
                  if v == 0x15D2 then some ("CANADIAN SYLLABICS CARRIER WE") else none
                else some ("CANADIAN SYLLABICS CARRIER WO")
              else if 0x15D3 < v then
                if v < 0x15D5 then
                  if v == 0x15D4 then some ("CANADIAN SYLLABICS CARRIER WI") else none
                else if 0x15D5 < v then
                  if v == 0x15D6 then some ("CANADIAN SYLLABICS CARRIER HWU") else none
                else some ("CANADIAN SYLLABICS CARRIER WA")
              else some ("CANADIAN SYLLABICS CARRIER WEE")
            else some ("CANADIAN SYLLABICS CARRIER RA")
          else some ("CANADIAN SYLLABICS CARRIER GHEE")
        else if 0x15D7 < v then
          if v < 0x15E7 then
            if v < 0x15DF then
              if v < 0x15DB then
                if v < 0x15D9 then
                  if v == 0x15D8 then some ("CANADIAN SYLLABICS CARRIER HWE") else none
                else if 0x15D9 < v then
                  if v == 0x15DA then some ("CANADIAN SYLLABICS CARRIER HWI") else none
                else some ("CANADIAN SYLLABICS CARRIER HWEE")
              else if 0x15DB < v then
                if v < 0x15DD then
                  if v == 0x15DC then some ("CANADIAN SYLLABICS CARRIER THU") else none
                else if 0x15DD < v then
                  if v == 0x15DE then some ("CANADIAN SYLLABICS CARRIER THE") else none
                else some ("CANADIAN SYLLABICS CARRIER THO")
              else some ("CANADIAN SYLLABICS CARRIER HWA")
            else if 0x15DF < v then
              if v < 0x15E3 then
                if v < 0x15E1 then
                  if v == 0x15E0 then some ("CANADIAN SYLLABICS CARRIER THI") else none
                else if 0x15E1 < v then
                  if v == 0x15E2 then some ("CANADIAN SYLLABICS CARRIER TTU") else none
                else some ("CANADIAN SYLLABICS CARRIER THA")
              else if 0x15E3 < v then
                if v < 0x15E5 then
                  if v == 0x15E4 then some ("CANADIAN SYLLABICS CARRIER TTE") else none
                else if 0x15E5 < v then
                  if v == 0x15E6 then some ("CANADIAN SYLLABICS CARRIER TTI") else none
                else some ("CANADIAN SYLLABICS CARRIER TTEE")
              else some ("CANADIAN SYLLABICS CARRIER TTO")
            else some ("CANADIAN SYLLABICS CARRIER THEE")
          else if 0x15E7 < v then
            if v < 0x15EF then
              if v < 0x15EB then
                if v < 0x15E9 then
                  if v == 0x15E8 then some ("CANADIAN SYLLABICS CARRIER PU") else none
                else if 0x15E9 < v then
                  if v == 0x15EA then some ("CANADIAN SYLLABICS CARRIER PE") else none
                else some ("CANADIAN SYLLABICS CARRIER PO")
              else if 0x15EB < v then
                if v < 0x15ED then
                  if v == 0x15EC then some ("CANADIAN SYLLABICS CARRIER PI") else none
                else if 0x15ED < v then
                  if v == 0x15EE then some ("CANADIAN SYLLABICS CARRIER P") else none
                else some ("CANADIAN SYLLABICS CARRIER PA")
              else some ("CANADIAN SYLLABICS CARRIER PEE")
            else if 0x15EF < v then
              if v < 0x15F3 then
                if v < 0x15F1 then
                  if v == 0x15F0 then some ("CANADIAN SYLLABICS CARRIER GO") else none
                else if 0x15F1 < v then
                  if v == 0x15F2 then some ("CANADIAN SYLLABICS CARRIER GEE") else none
                else some ("CANADIAN SYLLABICS CARRIER GE")
              else if 0x15F3 < v then
                if v < 0x15F5 then
                  if v == 0x15F4 then some ("CANADIAN SYLLABICS CARRIER GA") else none
                else if 0x15F5 < v then
                  if v == 0x15F6 then some ("CANADIAN SYLLABICS CARRIER KHO") else none
                else some ("CANADIAN SYLLABICS CARRIER KHU")
              else some ("CANADIAN SYLLABICS CARRIER GI")
            else some ("CANADIAN SYLLABICS CARRIER GU")
          else some ("CANADIAN SYLLABICS CARRIER TTA")
        else some ("CANADIAN SYLLABICS CARRIER HWO")
      else some ("CANADIAN SYLLABICS BLACKFOOT WA")
    else if 0x15F7 < v then
      if v < 0x1637 then
        if v < 0x1617 then
          if v < 0x1607 then
            if v < 0x15FF then
              if v < 0x15FB then
                if v < 0x15F9 then
                  if v == 0x15F8 then some ("CANADIAN SYLLABICS CARRIER KHEE") else none
                else if 0x15F9 < v then
                  if v == 0x15FA then some ("CANADIAN SYLLABICS CARRIER KHA") else none
                else some ("CANADIAN SYLLABICS CARRIER KHI")
              else if 0x15FB < v then
                if v < 0x15FD then
                  if v == 0x15FC then some ("CANADIAN SYLLABICS CARRIER KKO") else none
                else if 0x15FD < v then
                  if v == 0x15FE then some ("CANADIAN SYLLABICS CARRIER KKEE") else none
                else some ("CANADIAN SYLLABICS CARRIER KKE")
              else some ("CANADIAN SYLLABICS CARRIER KKU")
            else if 0x15FF < v then
              if v < 0x1603 then
                if v < 0x1601 then
                  if v == 0x1600 then some ("CANADIAN SYLLABICS CARRIER KKA") else none
                else if 0x1601 < v then
                  if v == 0x1602 then some ("CANADIAN SYLLABICS CARRIER NU") else none
                else some ("CANADIAN SYLLABICS CARRIER KK")
              else if 0x1603 < v then
                if v < 0x1605 then
                  if v == 0x1604 then some ("CANADIAN SYLLABICS CARRIER NE") else none
                else if 0x1605 < v then
                  if v == 0x1606 then some ("CANADIAN SYLLABICS CARRIER NI") else none
                else some ("CANADIAN SYLLABICS CARRIER NEE")
              else some ("CANADIAN SYLLABICS CARRIER NO")
            else some ("CANADIAN SYLLABICS CARRIER KKI")
          else if 0x1607 < v then
            if v < 0x160F then
              if v < 0x160B then
                if v < 0x1609 then
                  if v == 0x1608 then some ("CANADIAN SYLLABICS CARRIER MU") else none
                else if 0x1609 < v then
                  if v == 0x160A then some ("CANADIAN SYLLABICS CARRIER ME") else none
                else some ("CANADIAN SYLLABICS CARRIER MO")
              else if 0x160B < v then
                if v < 0x160D then
                  if v == 0x160C then some ("CANADIAN SYLLABICS CARRIER MI") else none
                else if 0x160D < v then
                  if v == 0x160E then some ("CANADIAN SYLLABICS CARRIER YU") else none
                else some ("CANADIAN SYLLABICS CARRIER MA")
              else some ("CANADIAN SYLLABICS CARRIER MEE")
            else if 0x160F < v then
              if v < 0x1613 then
                if v < 0x1611 then
                  if v == 0x1610 then some ("CANADIAN SYLLABICS CARRIER YE") else none
                else if 0x1611 < v then
                  if v == 0x1612 then some ("CANADIAN SYLLABICS CARRIER YI") else none
                else some ("CANADIAN SYLLABICS CARRIER YEE")
              else if 0x1613 < v then
                if v < 0x1615 then
                  if v == 0x1614 then some ("CANADIAN SYLLABICS CARRIER JU") else none
                else if 0x1615 < v then
                  if v == 0x1616 then some ("CANADIAN SYLLABICS CARRIER JO") else none
                else some ("CANADIAN SYLLABICS SAYISI JU")
              else some ("CANADIAN SYLLABICS CARRIER YA")
            else some ("CANADIAN SYLLABICS CARRIER YO")
          else some ("CANADIAN SYLLABICS CARRIER NA")
        else if 0x1617 < v then
          if v < 0x1627 then
            if v < 0x161F then
              if v < 0x161B then
                if v < 0x1619 then
                  if v == 0x1618 then some ("CANADIAN SYLLABICS CARRIER JEE") else none
                else if 0x1619 < v then
                  if v == 0x161A then some ("CANADIAN SYLLABICS SAYISI JI") else none
                else some ("CANADIAN SYLLABICS CARRIER JI")
              else if 0x161B < v then
                if v < 0x161D then
                  if v == 0x161C then some ("CANADIAN SYLLABICS CARRIER JJU") else none
                else if 0x161D < v then
                  if v == 0x161E then some ("CANADIAN SYLLABICS CARRIER JJE") else none
                else some ("CANADIAN SYLLABICS CARRIER JJO")
              else some ("CANADIAN SYLLABICS CARRIER JA")
            else if 0x161F < v then
              if v < 0x1623 then
                if v < 0x1621 then
                  if v == 0x1620 then some ("CANADIAN SYLLABICS CARRIER JJI") else none
                else if 0x1621 < v then
                  if v == 0x1622 then some ("CANADIAN SYLLABICS CARRIER LU") else none
                else some ("CANADIAN SYLLABICS CARRIER JJA")
              else if 0x1623 < v then
                if v < 0x1625 then
                  if v == 0x1624 then some ("CANADIAN SYLLABICS CARRIER LE") else none
                else if 0x1625 < v then
                  if v == 0x1626 then some ("CANADIAN SYLLABICS CARRIER LI") else none
                else some ("CANADIAN SYLLABICS CARRIER LEE")
              else some ("CANADIAN SYLLABICS CARRIER LO")
            else some ("CANADIAN SYLLABICS CARRIER JJEE")
          else if 0x1627 < v then
            if v < 0x162F then
              if v < 0x162B then
                if v < 0x1629 then
                  if v == 0x1628 then some ("CANADIAN SYLLABICS CARRIER DLU") else none
                else if 0x1629 < v then
                  if v == 0x162A then some ("CANADIAN SYLLABICS CARRIER DLE") else none
                else some ("CANADIAN SYLLABICS CARRIER DLO")
              else if 0x162B < v then
                if v < 0x162D then
                  if v == 0x162C then some ("CANADIAN SYLLABICS CARRIER DLI") else none
                else if 0x162D < v then
                  if v == 0x162E then some ("CANADIAN SYLLABICS CARRIER LHU") else none
                else some ("CANADIAN SYLLABICS CARRIER DLA")
              else some ("CANADIAN SYLLABICS CARRIER DLEE")
            else if 0x162F < v then
              if v < 0x1633 then
                if v < 0x1631 then
                  if v == 0x1630 then some ("CANADIAN SYLLABICS CARRIER LHE") else none
                else if 0x1631 < v then
                  if v == 0x1632 then some ("CANADIAN SYLLABICS CARRIER LHI") else none
                else some ("CANADIAN SYLLABICS CARRIER LHEE")
              else if 0x1633 < v then
                if v < 0x1635 then
                  if v == 0x1634 then some ("CANADIAN SYLLABICS CARRIER TLHU") else none
                else if 0x1635 < v then
                  if v == 0x1636 then some ("CANADIAN SYLLABICS CARRIER TLHE") else none
                else some ("CANADIAN SYLLABICS CARRIER TLHO")
              else some ("CANADIAN SYLLABICS CARRIER LHA")
            else some ("CANADIAN SYLLABICS CARRIER LHO")
          else some ("CANADIAN SYLLABICS CARRIER LA")
        else some ("CANADIAN SYLLABICS CARRIER JE")
      else if 0x1637 < v then
        if v < 0x1657 then
          if v < 0x1647 then
            if v < 0x163F then
              if v < 0x163B then
                if v < 0x1639 then
                  if v == 0x1638 then some ("CANADIAN SYLLABICS CARRIER TLHI") else none
                else if 0x1639 < v then
                  if v == 0x163A then some ("CANADIAN SYLLABICS CARRIER TLU") else none
                else some ("CANADIAN SYLLABICS CARRIER TLHA")
              else if 0x163B < v then
                if v < 0x163D then
                  if v == 0x163C then some ("CANADIAN SYLLABICS CARRIER TLE") else none
                else if 0x163D < v then
                  if v == 0x163E then some ("CANADIAN SYLLABICS CARRIER TLI") else none
                else some ("CANADIAN SYLLABICS CARRIER TLEE")
              else some ("CANADIAN SYLLABICS CARRIER TLO")
            else if 0x163F < v then
              if v < 0x1643 then
                if v < 0x1641 then
                  if v == 0x1640 then some ("CANADIAN SYLLABICS CARRIER ZU") else none
                else if 0x1641 < v then
                  if v == 0x1642 then some ("CANADIAN SYLLABICS CARRIER ZE") else none
                else some ("CANADIAN SYLLABICS CARRIER ZO")
              else if 0x1643 < v then
                if v < 0x1645 then
                  if v == 0x1644 then some ("CANADIAN SYLLABICS CARRIER ZI") else none
                else if 0x1645 < v then
                  if v == 0x1646 then some ("CANADIAN SYLLABICS CARRIER Z") else none
                else some ("CANADIAN SYLLABICS CARRIER ZA")
              else some ("CANADIAN SYLLABICS CARRIER ZEE")
            else some ("CANADIAN SYLLABICS CARRIER TLA")
          else if 0x1647 < v then
            if v < 0x164F then
              if v < 0x164B then
                if v < 0x1649 then
                  if v == 0x1648 then some ("CANADIAN SYLLABICS CARRIER DZU") else none
                else if 0x1649 < v then
                  if v == 0x164A then some ("CANADIAN SYLLABICS CARRIER DZE") else none
                else some ("CANADIAN SYLLABICS CARRIER DZO")
              else if 0x164B < v then
                if v < 0x164D then
                  if v == 0x164C then some ("CANADIAN SYLLABICS CARRIER DZI") else none
                else if 0x164D < v then
                  if v == 0x164E then some ("CANADIAN SYLLABICS CARRIER SU") else none
                else some ("CANADIAN SYLLABICS CARRIER DZA")
              else some ("CANADIAN SYLLABICS CARRIER DZEE")
            else if 0x164F < v then
              if v < 0x1653 then
                if v < 0x1651 then
                  if v == 0x1650 then some ("CANADIAN SYLLABICS CARRIER SE") else none
                else if 0x1651 < v then
                  if v == 0x1652 then some ("CANADIAN SYLLABICS CARRIER SI") else none
                else some ("CANADIAN SYLLABICS CARRIER SEE")
              else if 0x1653 < v then
                if v < 0x1655 then
                  if v == 0x1654 then some ("CANADIAN SYLLABICS CARRIER SHU") else none
                else if 0x1655 < v then
                  if v == 0x1656 then some ("CANADIAN SYLLABICS CARRIER SHE") else none
                else some ("CANADIAN SYLLABICS CARRIER SHO")
              else some ("CANADIAN SYLLABICS CARRIER SA")
            else some ("CANADIAN SYLLABICS CARRIER SO")
          else some ("CANADIAN SYLLABICS CARRIER INITIAL Z")
        else if 0x1657 < v then
          if v < 0x1667 then
            if v < 0x165F then
              if v < 0x165B then
                if v < 0x1659 then
                  if v == 0x1658 then some ("CANADIAN SYLLABICS CARRIER SHI") else none
                else if 0x1659 < v then
                  if v == 0x165A then some ("CANADIAN SYLLABICS CARRIER SH") else none
                else some ("CANADIAN SYLLABICS CARRIER SHA")
              else if 0x165B < v then
                if v < 0x165D then
                  if v == 0x165C then some ("CANADIAN SYLLABICS CARRIER TSO") else none
                else if 0x165D < v then
                  if v == 0x165E then some ("CANADIAN SYLLABICS CARRIER TSEE") else none
                else some ("CANADIAN SYLLABICS CARRIER TSE")
              else some ("CANADIAN SYLLABICS CARRIER TSU")
            else if 0x165F < v then
              if v < 0x1663 then
                if v < 0x1661 then
                  if v == 0x1660 then some ("CANADIAN SYLLABICS CARRIER TSA") else none
                else if 0x1661 < v then
                  if v == 0x1662 then some ("CANADIAN SYLLABICS CARRIER CHO") else none
                else some ("CANADIAN SYLLABICS CARRIER CHU")
              else if 0x1663 < v then
                if v < 0x1665 then
                  if v == 0x1664 then some ("CANADIAN SYLLABICS CARRIER CHEE") else none
                else if 0x1665 < v then
                  if v == 0x1666 then some ("CANADIAN SYLLABICS CARRIER CHA") else none
                else some ("CANADIAN SYLLABICS CARRIER CHI")
              else some ("CANADIAN SYLLABICS CARRIER CHE")
            else some ("CANADIAN SYLLABICS CARRIER TSI")
          else if 0x1667 < v then
            if v < 0x166F then
              if v < 0x166B then
                if v < 0x1669 then
                  if v == 0x1668 then some ("CANADIAN SYLLABICS CARRIER TTSO") else none
                else if 0x1669 < v then
                  if v == 0x166A then some ("CANADIAN SYLLABICS CARRIER TTSEE") else none
                else some ("CANADIAN SYLLABICS CARRIER TTSE")
              else if 0x166B < v then
                if v < 0x166D then
                  if v == 0x166C then some ("CANADIAN SYLLABICS CARRIER TTSA") else none
                else if 0x166D < v then
                  if v == 0x166E then some ("CANADIAN SYLLABICS FULL STOP") else none
                else some ("CANADIAN SYLLABICS CHI SIGN")
              else some ("CANADIAN SYLLABICS CARRIER TTSI")
            else if 0x166F < v then
              if v < 0x1673 then
                if v < 0x1671 then
                  if v == 0x1670 then some ("CANADIAN SYLLABICS NGAI") else none
                else if 0x1671 < v then
                  if v == 0x1672 then some ("CANADIAN SYLLABICS NNGII") else none
                else some ("CANADIAN SYLLABICS NNGI")
              else if 0x1673 < v then
                if v < 0x1675 then
                  if v == 0x1674 then some ("CANADIAN SYLLABICS NNGOO") else none
                else if 0x1675 < v then
                  if v == 0x1676 then some ("CANADIAN SYLLABICS NNGAA") else none
                else some ("CANADIAN SYLLABICS NNGA")
              else some ("CANADIAN SYLLABICS NNGO")
            else some ("CANADIAN SYLLABICS QAI")
          else some ("CANADIAN SYLLABICS CARRIER TTSU")
        else some ("CANADIAN SYLLABICS CARRIER SHEE")
      else some ("CANADIAN SYLLABICS CARRIER TLHEE")
    else some ("CANADIAN SYLLABICS CARRIER KHE")
  else some ("CANADIAN SYLLABICS NUNAVIK HO")

end Unicode.TableLookupTables.Name.Chunk9
