/- This file is generated by table-generators/makeTablesForLookup. -/
module

public import UnicodeBasic.TableLookupTables.Name.DuplicatedReturnedStrings

@[expose] public section

namespace Unicode.TableLookupTables.Name.Chunk63

@[inline_if_reduce, reducible]
def getInsideSparseRangeValueTable (v : UInt32) : Option String :=
  if v < 0x1D5ED then
    if v < 0x1D56D then
      if v < 0x1D526 then
        if v < 0x1D501 then
          if v < 0x1D4F1 then
            if v < 0x1D4E9 then
              if v < 0x1D4E5 then
                if v < 0x1D4E3 then
                  if v < 0x1D4E2 then
                    if v == 0x1D4E1 then some ("MATHEMATICAL BOLD SCRIPT CAPITAL R") else none
                  else if 0x1D4E2 < v then
                    none
                  else some ("MATHEMATICAL BOLD SCRIPT CAPITAL S")
                else if 0x1D4E3 < v then
                  if v == 0x1D4E4 then some ("MATHEMATICAL BOLD SCRIPT CAPITAL U") else none
                else some ("MATHEMATICAL BOLD SCRIPT CAPITAL T")
              else if 0x1D4E5 < v then
                if v < 0x1D4E7 then
                  if v == 0x1D4E6 then some ("MATHEMATICAL BOLD SCRIPT CAPITAL W") else none
                else if 0x1D4E7 < v then
                  if v == 0x1D4E8 then some ("MATHEMATICAL BOLD SCRIPT CAPITAL Y") else none
                else some ("MATHEMATICAL BOLD SCRIPT CAPITAL X")
              else some ("MATHEMATICAL BOLD SCRIPT CAPITAL V")
            else if 0x1D4E9 < v then
              if v < 0x1D4ED then
                if v < 0x1D4EB then
                  if v == 0x1D4EA then some ("MATHEMATICAL BOLD SCRIPT SMALL A") else none
                else if 0x1D4EB < v then
                  if v == 0x1D4EC then some ("MATHEMATICAL BOLD SCRIPT SMALL C") else none
                else some ("MATHEMATICAL BOLD SCRIPT SMALL B")
              else if 0x1D4ED < v then
                if v < 0x1D4EF then
                  if v == 0x1D4EE then some ("MATHEMATICAL BOLD SCRIPT SMALL E") else none
                else if 0x1D4EF < v then
                  if v == 0x1D4F0 then some ("MATHEMATICAL BOLD SCRIPT SMALL G") else none
                else some ("MATHEMATICAL BOLD SCRIPT SMALL F")
              else some ("MATHEMATICAL BOLD SCRIPT SMALL D")
            else some ("MATHEMATICAL BOLD SCRIPT CAPITAL Z")
          else if 0x1D4F1 < v then
            if v < 0x1D4F9 then
              if v < 0x1D4F5 then
                if v < 0x1D4F3 then
                  if v == 0x1D4F2 then some ("MATHEMATICAL BOLD SCRIPT SMALL I") else none
                else if 0x1D4F3 < v then
                  if v == 0x1D4F4 then some ("MATHEMATICAL BOLD SCRIPT SMALL K") else none
                else some ("MATHEMATICAL BOLD SCRIPT SMALL J")
              else if 0x1D4F5 < v then
                if v < 0x1D4F7 then
                  if v == 0x1D4F6 then some ("MATHEMATICAL BOLD SCRIPT SMALL M") else none
                else if 0x1D4F7 < v then
                  if v == 0x1D4F8 then some ("MATHEMATICAL BOLD SCRIPT SMALL O") else none
                else some ("MATHEMATICAL BOLD SCRIPT SMALL N")
              else some ("MATHEMATICAL BOLD SCRIPT SMALL L")
            else if 0x1D4F9 < v then
              if v < 0x1D4FD then
                if v < 0x1D4FB then
                  if v == 0x1D4FA then some ("MATHEMATICAL BOLD SCRIPT SMALL Q") else none
                else if 0x1D4FB < v then
                  if v == 0x1D4FC then some ("MATHEMATICAL BOLD SCRIPT SMALL S") else none
                else some ("MATHEMATICAL BOLD SCRIPT SMALL R")
              else if 0x1D4FD < v then
                if v < 0x1D4FF then
                  if v == 0x1D4FE then some ("MATHEMATICAL BOLD SCRIPT SMALL U") else none
                else if 0x1D4FF < v then
                  if v == 0x1D500 then some ("MATHEMATICAL BOLD SCRIPT SMALL W") else none
                else some ("MATHEMATICAL BOLD SCRIPT SMALL V")
              else some ("MATHEMATICAL BOLD SCRIPT SMALL T")
            else some ("MATHEMATICAL BOLD SCRIPT SMALL P")
          else some ("MATHEMATICAL BOLD SCRIPT SMALL H")
        else if 0x1D501 < v then
          if v < 0x1D514 then
            if v < 0x1D50A then
              if v < 0x1D505 then
                if v < 0x1D503 then
                  if v == 0x1D502 then some ("MATHEMATICAL BOLD SCRIPT SMALL Y") else none
                else if 0x1D503 < v then
                  if v == 0x1D504 then some ("MATHEMATICAL FRAKTUR CAPITAL A") else none
                else some ("MATHEMATICAL BOLD SCRIPT SMALL Z")
              else if 0x1D505 < v then
                if v < 0x1D508 then
                  if v == 0x1D507 then some ("MATHEMATICAL FRAKTUR CAPITAL D") else none
                else if 0x1D508 < v then
                  if v == 0x1D509 then some ("MATHEMATICAL FRAKTUR CAPITAL F") else none
                else some ("MATHEMATICAL FRAKTUR CAPITAL E")
              else some ("MATHEMATICAL FRAKTUR CAPITAL B")
            else if 0x1D50A < v then
              if v < 0x1D510 then
                if v < 0x1D50E then
                  if v == 0x1D50D then some ("MATHEMATICAL FRAKTUR CAPITAL J") else none
                else if 0x1D50E < v then
                  if v == 0x1D50F then some ("MATHEMATICAL FRAKTUR CAPITAL L") else none
                else some ("MATHEMATICAL FRAKTUR CAPITAL K")
              else if 0x1D510 < v then
                if v < 0x1D512 then
                  if v == 0x1D511 then some ("MATHEMATICAL FRAKTUR CAPITAL N") else none
                else if 0x1D512 < v then
                  if v == 0x1D513 then some ("MATHEMATICAL FRAKTUR CAPITAL P") else none
                else some ("MATHEMATICAL FRAKTUR CAPITAL O")
              else some ("MATHEMATICAL FRAKTUR CAPITAL M")
            else some ("MATHEMATICAL FRAKTUR CAPITAL G")
          else if 0x1D514 < v then
            if v < 0x1D51E then
              if v < 0x1D519 then
                if v < 0x1D517 then
                  if v == 0x1D516 then some ("MATHEMATICAL FRAKTUR CAPITAL S") else none
                else if 0x1D517 < v then
                  if v == 0x1D518 then some ("MATHEMATICAL FRAKTUR CAPITAL U") else none
                else some ("MATHEMATICAL FRAKTUR CAPITAL T")
              else if 0x1D519 < v then
                if v < 0x1D51B then
                  if v == 0x1D51A then some ("MATHEMATICAL FRAKTUR CAPITAL W") else none
                else if 0x1D51B < v then
                  if v == 0x1D51C then some ("MATHEMATICAL FRAKTUR CAPITAL Y") else none
                else some ("MATHEMATICAL FRAKTUR CAPITAL X")
              else some ("MATHEMATICAL FRAKTUR CAPITAL V")
            else if 0x1D51E < v then
              if v < 0x1D522 then
                if v < 0x1D520 then
                  if v == 0x1D51F then some ("MATHEMATICAL FRAKTUR SMALL B") else none
                else if 0x1D520 < v then
                  if v == 0x1D521 then some ("MATHEMATICAL FRAKTUR SMALL D") else none
                else some ("MATHEMATICAL FRAKTUR SMALL C")
              else if 0x1D522 < v then
                if v < 0x1D524 then
                  if v == 0x1D523 then some ("MATHEMATICAL FRAKTUR SMALL F") else none
                else if 0x1D524 < v then
                  if v == 0x1D525 then some ("MATHEMATICAL FRAKTUR SMALL H") else none
                else some ("MATHEMATICAL FRAKTUR SMALL G")
              else some ("MATHEMATICAL FRAKTUR SMALL E")
            else some ("MATHEMATICAL FRAKTUR SMALL A")
          else some ("MATHEMATICAL FRAKTUR CAPITAL Q")
        else some ("MATHEMATICAL BOLD SCRIPT SMALL X")
      else if 0x1D526 < v then
        if v < 0x1D54C then
          if v < 0x1D536 then
            if v < 0x1D52E then
              if v < 0x1D52A then
                if v < 0x1D528 then
                  if v == 0x1D527 then some ("MATHEMATICAL FRAKTUR SMALL J") else none
                else if 0x1D528 < v then
                  if v == 0x1D529 then some ("MATHEMATICAL FRAKTUR SMALL L") else none
                else some ("MATHEMATICAL FRAKTUR SMALL K")
              else if 0x1D52A < v then
                if v < 0x1D52C then
                  if v == 0x1D52B then some ("MATHEMATICAL FRAKTUR SMALL N") else none
                else if 0x1D52C < v then
                  if v == 0x1D52D then some ("MATHEMATICAL FRAKTUR SMALL P") else none
                else some ("MATHEMATICAL FRAKTUR SMALL O")
              else some ("MATHEMATICAL FRAKTUR SMALL M")
            else if 0x1D52E < v then
              if v < 0x1D532 then
                if v < 0x1D530 then
                  if v == 0x1D52F then some ("MATHEMATICAL FRAKTUR SMALL R") else none
                else if 0x1D530 < v then
                  if v == 0x1D531 then some ("MATHEMATICAL FRAKTUR SMALL T") else none
                else some ("MATHEMATICAL FRAKTUR SMALL S")
              else if 0x1D532 < v then
                if v < 0x1D534 then
                  if v == 0x1D533 then some ("MATHEMATICAL FRAKTUR SMALL V") else none
                else if 0x1D534 < v then
                  if v == 0x1D535 then some ("MATHEMATICAL FRAKTUR SMALL X") else none
                else some ("MATHEMATICAL FRAKTUR SMALL W")
              else some ("MATHEMATICAL FRAKTUR SMALL U")
            else some ("MATHEMATICAL FRAKTUR SMALL Q")
          else if 0x1D536 < v then
            if v < 0x1D540 then
              if v < 0x1D53B then
                if v < 0x1D538 then
                  if v == 0x1D537 then some ("MATHEMATICAL FRAKTUR SMALL Z") else none
                else if 0x1D538 < v then
                  if v == 0x1D539 then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL B") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL A")
              else if 0x1D53B < v then
                if v < 0x1D53D then
                  if v == 0x1D53C then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL E") else none
                else if 0x1D53D < v then
                  if v == 0x1D53E then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL G") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL F")
              else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL D")
            else if 0x1D540 < v then
              if v < 0x1D544 then
                if v < 0x1D542 then
                  if v == 0x1D541 then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL J") else none
                else if 0x1D542 < v then
                  if v == 0x1D543 then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL L") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL K")
              else if 0x1D544 < v then
                if v < 0x1D54A then
                  if v == 0x1D546 then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL O") else none
                else if 0x1D54A < v then
                  if v == 0x1D54B then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL T") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL S")
              else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL M")
            else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL I")
          else some ("MATHEMATICAL FRAKTUR SMALL Y")
        else if 0x1D54C < v then
          if v < 0x1D55D then
            if v < 0x1D555 then
              if v < 0x1D550 then
                if v < 0x1D54E then
                  if v == 0x1D54D then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL V") else none
                else if 0x1D54E < v then
                  if v == 0x1D54F then some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL X") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL W")
              else if 0x1D550 < v then
                if v < 0x1D553 then
                  if v == 0x1D552 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL A") else none
                else if 0x1D553 < v then
                  if v == 0x1D554 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL C") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK SMALL B")
              else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL Y")
            else if 0x1D555 < v then
              if v < 0x1D559 then
                if v < 0x1D557 then
                  if v == 0x1D556 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL E") else none
                else if 0x1D557 < v then
                  if v == 0x1D558 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL G") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK SMALL F")
              else if 0x1D559 < v then
                if v < 0x1D55B then
                  if v == 0x1D55A then some ("MATHEMATICAL DOUBLE-STRUCK SMALL I") else none
                else if 0x1D55B < v then
                  if v == 0x1D55C then some ("MATHEMATICAL DOUBLE-STRUCK SMALL K") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK SMALL J")
              else some ("MATHEMATICAL DOUBLE-STRUCK SMALL H")
            else some ("MATHEMATICAL DOUBLE-STRUCK SMALL D")
          else if 0x1D55D < v then
            if v < 0x1D565 then
              if v < 0x1D561 then
                if v < 0x1D55F then
                  if v == 0x1D55E then some ("MATHEMATICAL DOUBLE-STRUCK SMALL M") else none
                else if 0x1D55F < v then
                  if v == 0x1D560 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL O") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK SMALL N")
              else if 0x1D561 < v then
                if v < 0x1D563 then
                  if v == 0x1D562 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL Q") else none
                else if 0x1D563 < v then
                  if v == 0x1D564 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL S") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK SMALL R")
              else some ("MATHEMATICAL DOUBLE-STRUCK SMALL P")
            else if 0x1D565 < v then
              if v < 0x1D569 then
                if v < 0x1D567 then
                  if v == 0x1D566 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL U") else none
                else if 0x1D567 < v then
                  if v == 0x1D568 then some ("MATHEMATICAL DOUBLE-STRUCK SMALL W") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK SMALL V")
              else if 0x1D569 < v then
                if v < 0x1D56B then
                  if v == 0x1D56A then some ("MATHEMATICAL DOUBLE-STRUCK SMALL Y") else none
                else if 0x1D56B < v then
                  if v == 0x1D56C then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL A") else none
                else some ("MATHEMATICAL DOUBLE-STRUCK SMALL Z")
              else some ("MATHEMATICAL DOUBLE-STRUCK SMALL X")
            else some ("MATHEMATICAL DOUBLE-STRUCK SMALL T")
          else some ("MATHEMATICAL DOUBLE-STRUCK SMALL L")
        else some ("MATHEMATICAL DOUBLE-STRUCK CAPITAL U")
      else some ("MATHEMATICAL FRAKTUR SMALL I")
    else if 0x1D56D < v then
      if v < 0x1D5AD then
        if v < 0x1D58D then
          if v < 0x1D57D then
            if v < 0x1D575 then
              if v < 0x1D571 then
                if v < 0x1D56F then
                  if v == 0x1D56E then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL C") else none
                else if 0x1D56F < v then
                  if v == 0x1D570 then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL E") else none
                else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL D")
              else if 0x1D571 < v then
                if v < 0x1D573 then
                  if v == 0x1D572 then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL G") else none
                else if 0x1D573 < v then
                  if v == 0x1D574 then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL I") else none
                else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL H")
              else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL F")
            else if 0x1D575 < v then
              if v < 0x1D579 then
                if v < 0x1D577 then
                  if v == 0x1D576 then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL K") else none
                else if 0x1D577 < v then
                  if v == 0x1D578 then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL M") else none
                else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL L")
              else if 0x1D579 < v then
                if v < 0x1D57B then
                  if v == 0x1D57A then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL O") else none
                else if 0x1D57B < v then
                  if v == 0x1D57C then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL Q") else none
                else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL P")
              else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL N")
            else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL J")
          else if 0x1D57D < v then
            if v < 0x1D585 then
              if v < 0x1D581 then
                if v < 0x1D57F then
                  if v == 0x1D57E then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL S") else none
                else if 0x1D57F < v then
                  if v == 0x1D580 then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL U") else none
                else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL T")
              else if 0x1D581 < v then
                if v < 0x1D583 then
                  if v == 0x1D582 then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL W") else none
                else if 0x1D583 < v then
                  if v == 0x1D584 then some ("MATHEMATICAL BOLD FRAKTUR CAPITAL Y") else none
                else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL X")
              else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL V")
            else if 0x1D585 < v then
              if v < 0x1D589 then
                if v < 0x1D587 then
                  if v == 0x1D586 then some ("MATHEMATICAL BOLD FRAKTUR SMALL A") else none
                else if 0x1D587 < v then
                  if v == 0x1D588 then some ("MATHEMATICAL BOLD FRAKTUR SMALL C") else none
                else some ("MATHEMATICAL BOLD FRAKTUR SMALL B")
              else if 0x1D589 < v then
                if v < 0x1D58B then
                  if v == 0x1D58A then some ("MATHEMATICAL BOLD FRAKTUR SMALL E") else none
                else if 0x1D58B < v then
                  if v == 0x1D58C then some ("MATHEMATICAL BOLD FRAKTUR SMALL G") else none
                else some ("MATHEMATICAL BOLD FRAKTUR SMALL F")
              else some ("MATHEMATICAL BOLD FRAKTUR SMALL D")
            else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL Z")
          else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL R")
        else if 0x1D58D < v then
          if v < 0x1D59D then
            if v < 0x1D595 then
              if v < 0x1D591 then
                if v < 0x1D58F then
                  if v == 0x1D58E then some ("MATHEMATICAL BOLD FRAKTUR SMALL I") else none
                else if 0x1D58F < v then
                  if v == 0x1D590 then some ("MATHEMATICAL BOLD FRAKTUR SMALL K") else none
                else some ("MATHEMATICAL BOLD FRAKTUR SMALL J")
              else if 0x1D591 < v then
                if v < 0x1D593 then
                  if v == 0x1D592 then some ("MATHEMATICAL BOLD FRAKTUR SMALL M") else none
                else if 0x1D593 < v then
                  if v == 0x1D594 then some ("MATHEMATICAL BOLD FRAKTUR SMALL O") else none
                else some ("MATHEMATICAL BOLD FRAKTUR SMALL N")
              else some ("MATHEMATICAL BOLD FRAKTUR SMALL L")
            else if 0x1D595 < v then
              if v < 0x1D599 then
                if v < 0x1D597 then
                  if v == 0x1D596 then some ("MATHEMATICAL BOLD FRAKTUR SMALL Q") else none
                else if 0x1D597 < v then
                  if v == 0x1D598 then some ("MATHEMATICAL BOLD FRAKTUR SMALL S") else none
                else some ("MATHEMATICAL BOLD FRAKTUR SMALL R")
              else if 0x1D599 < v then
                if v < 0x1D59B then
                  if v == 0x1D59A then some ("MATHEMATICAL BOLD FRAKTUR SMALL U") else none
                else if 0x1D59B < v then
                  if v == 0x1D59C then some ("MATHEMATICAL BOLD FRAKTUR SMALL W") else none
                else some ("MATHEMATICAL BOLD FRAKTUR SMALL V")
              else some ("MATHEMATICAL BOLD FRAKTUR SMALL T")
            else some ("MATHEMATICAL BOLD FRAKTUR SMALL P")
          else if 0x1D59D < v then
            if v < 0x1D5A5 then
              if v < 0x1D5A1 then
                if v < 0x1D59F then
                  if v == 0x1D59E then some ("MATHEMATICAL BOLD FRAKTUR SMALL Y") else none
                else if 0x1D59F < v then
                  if v == 0x1D5A0 then some ("MATHEMATICAL SANS-SERIF CAPITAL A") else none
                else some ("MATHEMATICAL BOLD FRAKTUR SMALL Z")
              else if 0x1D5A1 < v then
                if v < 0x1D5A3 then
                  if v == 0x1D5A2 then some ("MATHEMATICAL SANS-SERIF CAPITAL C") else none
                else if 0x1D5A3 < v then
                  if v == 0x1D5A4 then some ("MATHEMATICAL SANS-SERIF CAPITAL E") else none
                else some ("MATHEMATICAL SANS-SERIF CAPITAL D")
              else some ("MATHEMATICAL SANS-SERIF CAPITAL B")
            else if 0x1D5A5 < v then
              if v < 0x1D5A9 then
                if v < 0x1D5A7 then
                  if v == 0x1D5A6 then some ("MATHEMATICAL SANS-SERIF CAPITAL G") else none
                else if 0x1D5A7 < v then
                  if v == 0x1D5A8 then some ("MATHEMATICAL SANS-SERIF CAPITAL I") else none
                else some ("MATHEMATICAL SANS-SERIF CAPITAL H")
              else if 0x1D5A9 < v then
                if v < 0x1D5AB then
                  if v == 0x1D5AA then some ("MATHEMATICAL SANS-SERIF CAPITAL K") else none
                else if 0x1D5AB < v then
                  if v == 0x1D5AC then some ("MATHEMATICAL SANS-SERIF CAPITAL M") else none
                else some ("MATHEMATICAL SANS-SERIF CAPITAL L")
              else some ("MATHEMATICAL SANS-SERIF CAPITAL J")
            else some ("MATHEMATICAL SANS-SERIF CAPITAL F")
          else some ("MATHEMATICAL BOLD FRAKTUR SMALL X")
        else some ("MATHEMATICAL BOLD FRAKTUR SMALL H")
      else if 0x1D5AD < v then
        if v < 0x1D5CD then
          if v < 0x1D5BD then
            if v < 0x1D5B5 then
              if v < 0x1D5B1 then
                if v < 0x1D5AF then
                  if v == 0x1D5AE then some ("MATHEMATICAL SANS-SERIF CAPITAL O") else none
                else if 0x1D5AF < v then
                  if v == 0x1D5B0 then some ("MATHEMATICAL SANS-SERIF CAPITAL Q") else none
                else some ("MATHEMATICAL SANS-SERIF CAPITAL P")
              else if 0x1D5B1 < v then
                if v < 0x1D5B3 then
                  if v == 0x1D5B2 then some ("MATHEMATICAL SANS-SERIF CAPITAL S") else none
                else if 0x1D5B3 < v then
                  if v == 0x1D5B4 then some ("MATHEMATICAL SANS-SERIF CAPITAL U") else none
                else some ("MATHEMATICAL SANS-SERIF CAPITAL T")
              else some ("MATHEMATICAL SANS-SERIF CAPITAL R")
            else if 0x1D5B5 < v then
              if v < 0x1D5B9 then
                if v < 0x1D5B7 then
                  if v == 0x1D5B6 then some ("MATHEMATICAL SANS-SERIF CAPITAL W") else none
                else if 0x1D5B7 < v then
                  if v == 0x1D5B8 then some ("MATHEMATICAL SANS-SERIF CAPITAL Y") else none
                else some ("MATHEMATICAL SANS-SERIF CAPITAL X")
              else if 0x1D5B9 < v then
                if v < 0x1D5BB then
                  if v == 0x1D5BA then some ("MATHEMATICAL SANS-SERIF SMALL A") else none
                else if 0x1D5BB < v then
                  if v == 0x1D5BC then some ("MATHEMATICAL SANS-SERIF SMALL C") else none
                else some ("MATHEMATICAL SANS-SERIF SMALL B")
              else some ("MATHEMATICAL SANS-SERIF CAPITAL Z")
            else some ("MATHEMATICAL SANS-SERIF CAPITAL V")
          else if 0x1D5BD < v then
            if v < 0x1D5C5 then
              if v < 0x1D5C1 then
                if v < 0x1D5BF then
                  if v == 0x1D5BE then some ("MATHEMATICAL SANS-SERIF SMALL E") else none
                else if 0x1D5BF < v then
                  if v == 0x1D5C0 then some ("MATHEMATICAL SANS-SERIF SMALL G") else none
                else some ("MATHEMATICAL SANS-SERIF SMALL F")
              else if 0x1D5C1 < v then
                if v < 0x1D5C3 then
                  if v == 0x1D5C2 then some ("MATHEMATICAL SANS-SERIF SMALL I") else none
                else if 0x1D5C3 < v then
                  if v == 0x1D5C4 then some ("MATHEMATICAL SANS-SERIF SMALL K") else none
                else some ("MATHEMATICAL SANS-SERIF SMALL J")
              else some ("MATHEMATICAL SANS-SERIF SMALL H")
            else if 0x1D5C5 < v then
              if v < 0x1D5C9 then
                if v < 0x1D5C7 then
                  if v == 0x1D5C6 then some ("MATHEMATICAL SANS-SERIF SMALL M") else none
                else if 0x1D5C7 < v then
                  if v == 0x1D5C8 then some ("MATHEMATICAL SANS-SERIF SMALL O") else none
                else some ("MATHEMATICAL SANS-SERIF SMALL N")
              else if 0x1D5C9 < v then
                if v < 0x1D5CB then
                  if v == 0x1D5CA then some ("MATHEMATICAL SANS-SERIF SMALL Q") else none
                else if 0x1D5CB < v then
                  if v == 0x1D5CC then some ("MATHEMATICAL SANS-SERIF SMALL S") else none
                else some ("MATHEMATICAL SANS-SERIF SMALL R")
              else some ("MATHEMATICAL SANS-SERIF SMALL P")
            else some ("MATHEMATICAL SANS-SERIF SMALL L")
          else some ("MATHEMATICAL SANS-SERIF SMALL D")
        else if 0x1D5CD < v then
          if v < 0x1D5DD then
            if v < 0x1D5D5 then
              if v < 0x1D5D1 then
                if v < 0x1D5CF then
                  if v == 0x1D5CE then some ("MATHEMATICAL SANS-SERIF SMALL U") else none
                else if 0x1D5CF < v then
                  if v == 0x1D5D0 then some ("MATHEMATICAL SANS-SERIF SMALL W") else none
                else some ("MATHEMATICAL SANS-SERIF SMALL V")
              else if 0x1D5D1 < v then
                if v < 0x1D5D3 then
                  if v == 0x1D5D2 then some ("MATHEMATICAL SANS-SERIF SMALL Y") else none
                else if 0x1D5D3 < v then
                  if v == 0x1D5D4 then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL A") else none
                else some ("MATHEMATICAL SANS-SERIF SMALL Z")
              else some ("MATHEMATICAL SANS-SERIF SMALL X")
            else if 0x1D5D5 < v then
              if v < 0x1D5D9 then
                if v < 0x1D5D7 then
                  if v == 0x1D5D6 then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL C") else none
                else if 0x1D5D7 < v then
                  if v == 0x1D5D8 then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL E") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL D")
              else if 0x1D5D9 < v then
                if v < 0x1D5DB then
                  if v == 0x1D5DA then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL G") else none
                else if 0x1D5DB < v then
                  if v == 0x1D5DC then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL I") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL H")
              else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL F")
            else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL B")
          else if 0x1D5DD < v then
            if v < 0x1D5E5 then
              if v < 0x1D5E1 then
                if v < 0x1D5DF then
                  if v == 0x1D5DE then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL K") else none
                else if 0x1D5DF < v then
                  if v == 0x1D5E0 then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL M") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL L")
              else if 0x1D5E1 < v then
                if v < 0x1D5E3 then
                  if v == 0x1D5E2 then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL O") else none
                else if 0x1D5E3 < v then
                  if v == 0x1D5E4 then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL Q") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL P")
              else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL N")
            else if 0x1D5E5 < v then
              if v < 0x1D5E9 then
                if v < 0x1D5E7 then
                  if v == 0x1D5E6 then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL S") else none
                else if 0x1D5E7 < v then
                  if v == 0x1D5E8 then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL U") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL T")
              else if 0x1D5E9 < v then
                if v < 0x1D5EB then
                  if v == 0x1D5EA then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL W") else none
                else if 0x1D5EB < v then
                  if v == 0x1D5EC then some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL Y") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL X")
              else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL V")
            else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL R")
          else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL J")
        else some ("MATHEMATICAL SANS-SERIF SMALL T")
      else some ("MATHEMATICAL SANS-SERIF CAPITAL N")
    else some ("MATHEMATICAL BOLD FRAKTUR CAPITAL B")
  else if 0x1D5ED < v then
    if v < 0x1D66D then
      if v < 0x1D62D then
        if v < 0x1D60D then
          if v < 0x1D5FD then
            if v < 0x1D5F5 then
              if v < 0x1D5F1 then
                if v < 0x1D5EF then
                  if v == 0x1D5EE then some ("MATHEMATICAL SANS-SERIF BOLD SMALL A") else none
                else if 0x1D5EF < v then
                  if v == 0x1D5F0 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL C") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD SMALL B")
              else if 0x1D5F1 < v then
                if v < 0x1D5F3 then
                  if v == 0x1D5F2 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL E") else none
                else if 0x1D5F3 < v then
                  if v == 0x1D5F4 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL G") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD SMALL F")
              else some ("MATHEMATICAL SANS-SERIF BOLD SMALL D")
            else if 0x1D5F5 < v then
              if v < 0x1D5F9 then
                if v < 0x1D5F7 then
                  if v == 0x1D5F6 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL I") else none
                else if 0x1D5F7 < v then
                  if v == 0x1D5F8 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL K") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD SMALL J")
              else if 0x1D5F9 < v then
                if v < 0x1D5FB then
                  if v == 0x1D5FA then some ("MATHEMATICAL SANS-SERIF BOLD SMALL M") else none
                else if 0x1D5FB < v then
                  if v == 0x1D5FC then some ("MATHEMATICAL SANS-SERIF BOLD SMALL O") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD SMALL N")
              else some ("MATHEMATICAL SANS-SERIF BOLD SMALL L")
            else some ("MATHEMATICAL SANS-SERIF BOLD SMALL H")
          else if 0x1D5FD < v then
            if v < 0x1D605 then
              if v < 0x1D601 then
                if v < 0x1D5FF then
                  if v == 0x1D5FE then some ("MATHEMATICAL SANS-SERIF BOLD SMALL Q") else none
                else if 0x1D5FF < v then
                  if v == 0x1D600 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL S") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD SMALL R")
              else if 0x1D601 < v then
                if v < 0x1D603 then
                  if v == 0x1D602 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL U") else none
                else if 0x1D603 < v then
                  if v == 0x1D604 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL W") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD SMALL V")
              else some ("MATHEMATICAL SANS-SERIF BOLD SMALL T")
            else if 0x1D605 < v then
              if v < 0x1D609 then
                if v < 0x1D607 then
                  if v == 0x1D606 then some ("MATHEMATICAL SANS-SERIF BOLD SMALL Y") else none
                else if 0x1D607 < v then
                  if v == 0x1D608 then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL A") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD SMALL Z")
              else if 0x1D609 < v then
                if v < 0x1D60B then
                  if v == 0x1D60A then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL C") else none
                else if 0x1D60B < v then
                  if v == 0x1D60C then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL E") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL D")
              else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL B")
            else some ("MATHEMATICAL SANS-SERIF BOLD SMALL X")
          else some ("MATHEMATICAL SANS-SERIF BOLD SMALL P")
        else if 0x1D60D < v then
          if v < 0x1D61D then
            if v < 0x1D615 then
              if v < 0x1D611 then
                if v < 0x1D60F then
                  if v == 0x1D60E then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL G") else none
                else if 0x1D60F < v then
                  if v == 0x1D610 then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL I") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL H")
              else if 0x1D611 < v then
                if v < 0x1D613 then
                  if v == 0x1D612 then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL K") else none
                else if 0x1D613 < v then
                  if v == 0x1D614 then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL M") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL L")
              else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL J")
            else if 0x1D615 < v then
              if v < 0x1D619 then
                if v < 0x1D617 then
                  if v == 0x1D616 then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL O") else none
                else if 0x1D617 < v then
                  if v == 0x1D618 then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL Q") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL P")
              else if 0x1D619 < v then
                if v < 0x1D61B then
                  if v == 0x1D61A then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL S") else none
                else if 0x1D61B < v then
                  if v == 0x1D61C then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL U") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL T")
              else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL R")
            else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL N")
          else if 0x1D61D < v then
            if v < 0x1D625 then
              if v < 0x1D621 then
                if v < 0x1D61F then
                  if v == 0x1D61E then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL W") else none
                else if 0x1D61F < v then
                  if v == 0x1D620 then some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL Y") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL X")
              else if 0x1D621 < v then
                if v < 0x1D623 then
                  if v == 0x1D622 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL A") else none
                else if 0x1D623 < v then
                  if v == 0x1D624 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL C") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL B")
              else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL Z")
            else if 0x1D625 < v then
              if v < 0x1D629 then
                if v < 0x1D627 then
                  if v == 0x1D626 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL E") else none
                else if 0x1D627 < v then
                  if v == 0x1D628 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL G") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL F")
              else if 0x1D629 < v then
                if v < 0x1D62B then
                  if v == 0x1D62A then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL I") else none
                else if 0x1D62B < v then
                  if v == 0x1D62C then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL K") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL J")
              else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL H")
            else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL D")
          else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL V")
        else some ("MATHEMATICAL SANS-SERIF ITALIC CAPITAL F")
      else if 0x1D62D < v then
        if v < 0x1D64D then
          if v < 0x1D63D then
            if v < 0x1D635 then
              if v < 0x1D631 then
                if v < 0x1D62F then
                  if v == 0x1D62E then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL M") else none
                else if 0x1D62F < v then
                  if v == 0x1D630 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL O") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL N")
              else if 0x1D631 < v then
                if v < 0x1D633 then
                  if v == 0x1D632 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL Q") else none
                else if 0x1D633 < v then
                  if v == 0x1D634 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL S") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL R")
              else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL P")
            else if 0x1D635 < v then
              if v < 0x1D639 then
                if v < 0x1D637 then
                  if v == 0x1D636 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL U") else none
                else if 0x1D637 < v then
                  if v == 0x1D638 then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL W") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL V")
              else if 0x1D639 < v then
                if v < 0x1D63B then
                  if v == 0x1D63A then some ("MATHEMATICAL SANS-SERIF ITALIC SMALL Y") else none
                else if 0x1D63B < v then
                  if v == 0x1D63C then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL A") else none
                else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL Z")
              else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL X")
            else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL T")
          else if 0x1D63D < v then
            if v < 0x1D645 then
              if v < 0x1D641 then
                if v < 0x1D63F then
                  if v == 0x1D63E then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL C") else none
                else if 0x1D63F < v then
                  if v == 0x1D640 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL E") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL D")
              else if 0x1D641 < v then
                if v < 0x1D643 then
                  if v == 0x1D642 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL G") else none
                else if 0x1D643 < v then
                  if v == 0x1D644 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL I") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL H")
              else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL F")
            else if 0x1D645 < v then
              if v < 0x1D649 then
                if v < 0x1D647 then
                  if v == 0x1D646 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL K") else none
                else if 0x1D647 < v then
                  if v == 0x1D648 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL M") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL L")
              else if 0x1D649 < v then
                if v < 0x1D64B then
                  if v == 0x1D64A then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL O") else none
                else if 0x1D64B < v then
                  if v == 0x1D64C then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Q") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL P")
              else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL N")
            else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL J")
          else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL B")
        else if 0x1D64D < v then
          if v < 0x1D65D then
            if v < 0x1D655 then
              if v < 0x1D651 then
                if v < 0x1D64F then
                  if v == 0x1D64E then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL S") else none
                else if 0x1D64F < v then
                  if v == 0x1D650 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL U") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL T")
              else if 0x1D651 < v then
                if v < 0x1D653 then
                  if v == 0x1D652 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL W") else none
                else if 0x1D653 < v then
                  if v == 0x1D654 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Y") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL X")
              else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL V")
            else if 0x1D655 < v then
              if v < 0x1D659 then
                if v < 0x1D657 then
                  if v == 0x1D656 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL A") else none
                else if 0x1D657 < v then
                  if v == 0x1D658 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL C") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL B")
              else if 0x1D659 < v then
                if v < 0x1D65B then
                  if v == 0x1D65A then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL E") else none
                else if 0x1D65B < v then
                  if v == 0x1D65C then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL G") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL F")
              else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL D")
            else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Z")
          else if 0x1D65D < v then
            if v < 0x1D665 then
              if v < 0x1D661 then
                if v < 0x1D65F then
                  if v == 0x1D65E then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL I") else none
                else if 0x1D65F < v then
                  if v == 0x1D660 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL K") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL J")
              else if 0x1D661 < v then
                if v < 0x1D663 then
                  if v == 0x1D662 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL M") else none
                else if 0x1D663 < v then
                  if v == 0x1D664 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL O") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL N")
              else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL L")
            else if 0x1D665 < v then
              if v < 0x1D669 then
                if v < 0x1D667 then
                  if v == 0x1D666 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Q") else none
                else if 0x1D667 < v then
                  if v == 0x1D668 then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL S") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL R")
              else if 0x1D669 < v then
                if v < 0x1D66B then
                  if v == 0x1D66A then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL U") else none
                else if 0x1D66B < v then
                  if v == 0x1D66C then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL W") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL V")
              else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL T")
            else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL P")
          else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL H")
        else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL R")
      else some ("MATHEMATICAL SANS-SERIF ITALIC SMALL L")
    else if 0x1D66D < v then
      if v < 0x1D6AF then
        if v < 0x1D68D then
          if v < 0x1D67D then
            if v < 0x1D675 then
              if v < 0x1D671 then
                if v < 0x1D66F then
                  if v == 0x1D66E then some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Y") else none
                else if 0x1D66F < v then
                  if v == 0x1D670 then some ("MATHEMATICAL MONOSPACE CAPITAL A") else none
                else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Z")
              else if 0x1D671 < v then
                if v < 0x1D673 then
                  if v == 0x1D672 then some ("MATHEMATICAL MONOSPACE CAPITAL C") else none
                else if 0x1D673 < v then
                  if v == 0x1D674 then some ("MATHEMATICAL MONOSPACE CAPITAL E") else none
                else some ("MATHEMATICAL MONOSPACE CAPITAL D")
              else some ("MATHEMATICAL MONOSPACE CAPITAL B")
            else if 0x1D675 < v then
              if v < 0x1D679 then
                if v < 0x1D677 then
                  if v == 0x1D676 then some ("MATHEMATICAL MONOSPACE CAPITAL G") else none
                else if 0x1D677 < v then
                  if v == 0x1D678 then some ("MATHEMATICAL MONOSPACE CAPITAL I") else none
                else some ("MATHEMATICAL MONOSPACE CAPITAL H")
              else if 0x1D679 < v then
                if v < 0x1D67B then
                  if v == 0x1D67A then some ("MATHEMATICAL MONOSPACE CAPITAL K") else none
                else if 0x1D67B < v then
                  if v == 0x1D67C then some ("MATHEMATICAL MONOSPACE CAPITAL M") else none
                else some ("MATHEMATICAL MONOSPACE CAPITAL L")
              else some ("MATHEMATICAL MONOSPACE CAPITAL J")
            else some ("MATHEMATICAL MONOSPACE CAPITAL F")
          else if 0x1D67D < v then
            if v < 0x1D685 then
              if v < 0x1D681 then
                if v < 0x1D67F then
                  if v == 0x1D67E then some ("MATHEMATICAL MONOSPACE CAPITAL O") else none
                else if 0x1D67F < v then
                  if v == 0x1D680 then some ("MATHEMATICAL MONOSPACE CAPITAL Q") else none
                else some ("MATHEMATICAL MONOSPACE CAPITAL P")
              else if 0x1D681 < v then
                if v < 0x1D683 then
                  if v == 0x1D682 then some ("MATHEMATICAL MONOSPACE CAPITAL S") else none
                else if 0x1D683 < v then
                  if v == 0x1D684 then some ("MATHEMATICAL MONOSPACE CAPITAL U") else none
                else some ("MATHEMATICAL MONOSPACE CAPITAL T")
              else some ("MATHEMATICAL MONOSPACE CAPITAL R")
            else if 0x1D685 < v then
              if v < 0x1D689 then
                if v < 0x1D687 then
                  if v == 0x1D686 then some ("MATHEMATICAL MONOSPACE CAPITAL W") else none
                else if 0x1D687 < v then
                  if v == 0x1D688 then some ("MATHEMATICAL MONOSPACE CAPITAL Y") else none
                else some ("MATHEMATICAL MONOSPACE CAPITAL X")
              else if 0x1D689 < v then
                if v < 0x1D68B then
                  if v == 0x1D68A then some ("MATHEMATICAL MONOSPACE SMALL A") else none
                else if 0x1D68B < v then
                  if v == 0x1D68C then some ("MATHEMATICAL MONOSPACE SMALL C") else none
                else some ("MATHEMATICAL MONOSPACE SMALL B")
              else some ("MATHEMATICAL MONOSPACE CAPITAL Z")
            else some ("MATHEMATICAL MONOSPACE CAPITAL V")
          else some ("MATHEMATICAL MONOSPACE CAPITAL N")
        else if 0x1D68D < v then
          if v < 0x1D69D then
            if v < 0x1D695 then
              if v < 0x1D691 then
                if v < 0x1D68F then
                  if v == 0x1D68E then some ("MATHEMATICAL MONOSPACE SMALL E") else none
                else if 0x1D68F < v then
                  if v == 0x1D690 then some ("MATHEMATICAL MONOSPACE SMALL G") else none
                else some ("MATHEMATICAL MONOSPACE SMALL F")
              else if 0x1D691 < v then
                if v < 0x1D693 then
                  if v == 0x1D692 then some ("MATHEMATICAL MONOSPACE SMALL I") else none
                else if 0x1D693 < v then
                  if v == 0x1D694 then some ("MATHEMATICAL MONOSPACE SMALL K") else none
                else some ("MATHEMATICAL MONOSPACE SMALL J")
              else some ("MATHEMATICAL MONOSPACE SMALL H")
            else if 0x1D695 < v then
              if v < 0x1D699 then
                if v < 0x1D697 then
                  if v == 0x1D696 then some ("MATHEMATICAL MONOSPACE SMALL M") else none
                else if 0x1D697 < v then
                  if v == 0x1D698 then some ("MATHEMATICAL MONOSPACE SMALL O") else none
                else some ("MATHEMATICAL MONOSPACE SMALL N")
              else if 0x1D699 < v then
                if v < 0x1D69B then
                  if v == 0x1D69A then some ("MATHEMATICAL MONOSPACE SMALL Q") else none
                else if 0x1D69B < v then
                  if v == 0x1D69C then some ("MATHEMATICAL MONOSPACE SMALL S") else none
                else some ("MATHEMATICAL MONOSPACE SMALL R")
              else some ("MATHEMATICAL MONOSPACE SMALL P")
            else some ("MATHEMATICAL MONOSPACE SMALL L")
          else if 0x1D69D < v then
            if v < 0x1D6A5 then
              if v < 0x1D6A1 then
                if v < 0x1D69F then
                  if v == 0x1D69E then some ("MATHEMATICAL MONOSPACE SMALL U") else none
                else if 0x1D69F < v then
                  if v == 0x1D6A0 then some ("MATHEMATICAL MONOSPACE SMALL W") else none
                else some ("MATHEMATICAL MONOSPACE SMALL V")
              else if 0x1D6A1 < v then
                if v < 0x1D6A3 then
                  if v == 0x1D6A2 then some ("MATHEMATICAL MONOSPACE SMALL Y") else none
                else if 0x1D6A3 < v then
                  if v == 0x1D6A4 then some ("MATHEMATICAL ITALIC SMALL DOTLESS I") else none
                else some ("MATHEMATICAL MONOSPACE SMALL Z")
              else some ("MATHEMATICAL MONOSPACE SMALL X")
            else if 0x1D6A5 < v then
              if v < 0x1D6AB then
                if v < 0x1D6A9 then
                  if v == 0x1D6A8 then some ("MATHEMATICAL BOLD CAPITAL ALPHA") else none
                else if 0x1D6A9 < v then
                  if v == 0x1D6AA then some ("MATHEMATICAL BOLD CAPITAL GAMMA") else none
                else some ("MATHEMATICAL BOLD CAPITAL BETA")
              else if 0x1D6AB < v then
                if v < 0x1D6AD then
                  if v == 0x1D6AC then some ("MATHEMATICAL BOLD CAPITAL EPSILON") else none
                else if 0x1D6AD < v then
                  if v == 0x1D6AE then some ("MATHEMATICAL BOLD CAPITAL ETA") else none
                else some ("MATHEMATICAL BOLD CAPITAL ZETA")
              else some ("MATHEMATICAL BOLD CAPITAL DELTA")
            else some ("MATHEMATICAL ITALIC SMALL DOTLESS J")
          else some ("MATHEMATICAL MONOSPACE SMALL T")
        else some ("MATHEMATICAL MONOSPACE SMALL D")
      else if 0x1D6AF < v then
        if v < 0x1D6CF then
          if v < 0x1D6BF then
            if v < 0x1D6B7 then
              if v < 0x1D6B3 then
                if v < 0x1D6B1 then
                  if v == 0x1D6B0 then some ("MATHEMATICAL BOLD CAPITAL IOTA") else none
                else if 0x1D6B1 < v then
                  if v == 0x1D6B2 then some ("MATHEMATICAL BOLD CAPITAL LAMDA") else none
                else some ("MATHEMATICAL BOLD CAPITAL KAPPA")
              else if 0x1D6B3 < v then
                if v < 0x1D6B5 then
                  if v == 0x1D6B4 then some ("MATHEMATICAL BOLD CAPITAL NU") else none
                else if 0x1D6B5 < v then
                  if v == 0x1D6B6 then some ("MATHEMATICAL BOLD CAPITAL OMICRON") else none
                else some ("MATHEMATICAL BOLD CAPITAL XI")
              else some ("MATHEMATICAL BOLD CAPITAL MU")
            else if 0x1D6B7 < v then
              if v < 0x1D6BB then
                if v < 0x1D6B9 then
                  if v == 0x1D6B8 then some ("MATHEMATICAL BOLD CAPITAL RHO") else none
                else if 0x1D6B9 < v then
                  if v == 0x1D6BA then some ("MATHEMATICAL BOLD CAPITAL SIGMA") else none
                else some ("MATHEMATICAL BOLD CAPITAL THETA SYMBOL")
              else if 0x1D6BB < v then
                if v < 0x1D6BD then
                  if v == 0x1D6BC then some ("MATHEMATICAL BOLD CAPITAL UPSILON") else none
                else if 0x1D6BD < v then
                  if v == 0x1D6BE then some ("MATHEMATICAL BOLD CAPITAL CHI") else none
                else some ("MATHEMATICAL BOLD CAPITAL PHI")
              else some ("MATHEMATICAL BOLD CAPITAL TAU")
            else some ("MATHEMATICAL BOLD CAPITAL PI")
          else if 0x1D6BF < v then
            if v < 0x1D6C7 then
              if v < 0x1D6C3 then
                if v < 0x1D6C1 then
                  if v == 0x1D6C0 then some ("MATHEMATICAL BOLD CAPITAL OMEGA") else none
                else if 0x1D6C1 < v then
                  if v == 0x1D6C2 then some ("MATHEMATICAL BOLD SMALL ALPHA") else none
                else some ("MATHEMATICAL BOLD NABLA")
              else if 0x1D6C3 < v then
                if v < 0x1D6C5 then
                  if v == 0x1D6C4 then some ("MATHEMATICAL BOLD SMALL GAMMA") else none
                else if 0x1D6C5 < v then
                  if v == 0x1D6C6 then some ("MATHEMATICAL BOLD SMALL EPSILON") else none
                else some ("MATHEMATICAL BOLD SMALL DELTA")
              else some ("MATHEMATICAL BOLD SMALL BETA")
            else if 0x1D6C7 < v then
              if v < 0x1D6CB then
                if v < 0x1D6C9 then
                  if v == 0x1D6C8 then some ("MATHEMATICAL BOLD SMALL ETA") else none
                else if 0x1D6C9 < v then
                  if v == 0x1D6CA then some ("MATHEMATICAL BOLD SMALL IOTA") else none
                else some ("MATHEMATICAL BOLD SMALL THETA")
              else if 0x1D6CB < v then
                if v < 0x1D6CD then
                  if v == 0x1D6CC then some ("MATHEMATICAL BOLD SMALL LAMDA") else none
                else if 0x1D6CD < v then
                  if v == 0x1D6CE then some ("MATHEMATICAL BOLD SMALL NU") else none
                else some ("MATHEMATICAL BOLD SMALL MU")
              else some ("MATHEMATICAL BOLD SMALL KAPPA")
            else some ("MATHEMATICAL BOLD SMALL ZETA")
          else some ("MATHEMATICAL BOLD CAPITAL PSI")
        else if 0x1D6CF < v then
          if v < 0x1D6DF then
            if v < 0x1D6D7 then
              if v < 0x1D6D3 then
                if v < 0x1D6D1 then
                  if v == 0x1D6D0 then some ("MATHEMATICAL BOLD SMALL OMICRON") else none
                else if 0x1D6D1 < v then
                  if v == 0x1D6D2 then some ("MATHEMATICAL BOLD SMALL RHO") else none
                else some ("MATHEMATICAL BOLD SMALL PI")
              else if 0x1D6D3 < v then
                if v < 0x1D6D5 then
                  if v == 0x1D6D4 then some ("MATHEMATICAL BOLD SMALL SIGMA") else none
                else if 0x1D6D5 < v then
                  if v == 0x1D6D6 then some ("MATHEMATICAL BOLD SMALL UPSILON") else none
                else some ("MATHEMATICAL BOLD SMALL TAU")
              else some ("MATHEMATICAL BOLD SMALL FINAL SIGMA")
            else if 0x1D6D7 < v then
              if v < 0x1D6DB then
                if v < 0x1D6D9 then
                  if v == 0x1D6D8 then some ("MATHEMATICAL BOLD SMALL CHI") else none
                else if 0x1D6D9 < v then
                  if v == 0x1D6DA then some ("MATHEMATICAL BOLD SMALL OMEGA") else none
                else some ("MATHEMATICAL BOLD SMALL PSI")
              else if 0x1D6DB < v then
                if v < 0x1D6DD then
                  if v == 0x1D6DC then some ("MATHEMATICAL BOLD EPSILON SYMBOL") else none
                else if 0x1D6DD < v then
                  if v == 0x1D6DE then some ("MATHEMATICAL BOLD KAPPA SYMBOL") else none
                else some ("MATHEMATICAL BOLD THETA SYMBOL")
              else some ("MATHEMATICAL BOLD PARTIAL DIFFERENTIAL")
            else some ("MATHEMATICAL BOLD SMALL PHI")
          else if 0x1D6DF < v then
            if v < 0x1D6E7 then
              if v < 0x1D6E3 then
                if v < 0x1D6E1 then
                  if v == 0x1D6E0 then some ("MATHEMATICAL BOLD RHO SYMBOL") else none
                else if 0x1D6E1 < v then
                  if v == 0x1D6E2 then some ("MATHEMATICAL ITALIC CAPITAL ALPHA") else none
                else some ("MATHEMATICAL BOLD PI SYMBOL")
              else if 0x1D6E3 < v then
                if v < 0x1D6E5 then
                  if v == 0x1D6E4 then some ("MATHEMATICAL ITALIC CAPITAL GAMMA") else none
                else if 0x1D6E5 < v then
                  if v == 0x1D6E6 then some ("MATHEMATICAL ITALIC CAPITAL EPSILON") else none
                else some ("MATHEMATICAL ITALIC CAPITAL DELTA")
              else some ("MATHEMATICAL ITALIC CAPITAL BETA")
            else if 0x1D6E7 < v then
              if v < 0x1D6EB then
                if v < 0x1D6E9 then
                  if v == 0x1D6E8 then some ("MATHEMATICAL ITALIC CAPITAL ETA") else none
                else if 0x1D6E9 < v then
                  if v == 0x1D6EA then some ("MATHEMATICAL ITALIC CAPITAL IOTA") else none
                else some ("MATHEMATICAL ITALIC CAPITAL THETA")
              else if 0x1D6EB < v then
                if v < 0x1D6ED then
                  if v == 0x1D6EC then some ("MATHEMATICAL ITALIC CAPITAL LAMDA") else none
                else if 0x1D6ED < v then
                  if v == 0x1D6EE then some ("MATHEMATICAL ITALIC CAPITAL NU") else none
                else some ("MATHEMATICAL ITALIC CAPITAL MU")
              else some ("MATHEMATICAL ITALIC CAPITAL KAPPA")
            else some ("MATHEMATICAL ITALIC CAPITAL ZETA")
          else some ("MATHEMATICAL BOLD PHI SYMBOL")
        else some ("MATHEMATICAL BOLD SMALL XI")
      else some ("MATHEMATICAL BOLD CAPITAL THETA")
    else some ("MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X")
  else some ("MATHEMATICAL SANS-SERIF BOLD CAPITAL Z")

end Unicode.TableLookupTables.Name.Chunk63
