name = "UnicodeBasicUtilities"
precompileModules = true
description = "Basic Unicode support for Lean 4"
keywords = ["unicode"]
defaultTargets = ["MakeCLib", "MakeTables", "TestTables"]

[[require]]
name = "UnicodeBasic"
path = ".."

[[require]]
name = "UnicodeData"
git = "https://github.com/fgdorais/lean4-unicode-data"
rev = "main"

[[lean_exe]]
name = "MakeCLib"

[[lean_exe]]
name = "MakeTables"

[[lean_exe]]
name = "TestTables"
