name = "util"
reservoir = false
defaultTargets = ["MakeCLib", "MakeTables", "TestTables"]

[[require]]
name = "UnicodeData"
git = "https://github.com/fgdorais/lean4-unicode-data"
rev = "main"

[[require]]
name = "UnicodeBasic"
path = ".."

[[lean_exe]]
name = "MakeCLib"

[[lean_exe]]
name = "MakeTables"

[[lean_exe]]
name = "TestTables"
