name: Build

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main", "nightly-testing"]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v7

      - name: install lean and build
        uses: leanprover/lean-action@v1
        with:
          build: true
          build-args: "--wfail UnicodeBasic UnicodeData lookup makeCLib makeTables"
          test: false
          use-mathlib-cache: false

      - name: test package
        working-directory: tests
        run: lake test
