name: Build

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main", "nightly-testing"]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build Common
        uses: leanprover/lean-action@v1
        with:
          build: true
          build-args: "--wfail"
          lake-package-directory: common
          test: false
          use-mathlib-cache: false

      - name: Build Table Generators
        uses: leanprover/lean-action@v1
        with:
          build: true
          build-args: "--wfail"
          lake-package-directory: table-generators
          test: false
          use-mathlib-cache: false

      - name: Build Library
        uses: leanprover/lean-action@v1
        with:
          build: true
          build-args: "--wfail"
          lake-package-directory: lib
          test: false

      - name: Build Lean Scripts
        uses: leanprover/lean-action@v1
        with:
          build: true
          build-args: "--wfail"
          lake-package-directory: lean-scripts
          test: false

      - name: Build Tests
        uses: leanprover/lean-action@v1
        with:
          build: true
          build-args: "--wfail"
          lake-package-directory: tests
          test: false

      - name: Run Tests
        working-directory: tests
        run: lake exe testAll -- --timeout 120
