name: Publish Docs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build UnicodeBasic Docs
        uses: leanprover/lean-action@v1
        with:
          build: true
          build-args: "--keep-toolchain UnicodeBasic:docs"
          lake-package-directory: lib
          test: false

      - name: Build UnicodeData Docs
        uses: leanprover/lean-action@v1
        with:
          build: true
          build-args: "--keep-toolchain UnicodeData:docs"
          lake-package-directory: table-generators
          test: false

      - name: Build Docs
        working-directory: docs
        run: lake build --keep-toolchain UnicodeBasic:docs UnicodeData:docs

      - name: Deploy Docs
        run: |
          git config user.name "unicode-basic-bot"
          git config user.email "unicode-basic-bot@users.noreply.github.com"
          git checkout -b docs
          git add docs/doc docs/doc-data
          git commit -m "chore: generate docs"
          git push origin docs --force
