name: Update Toolchain

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-toolchain:
    name: update toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: nightly-testing
          fetch-depth: 0

      # - name: Fetch Main
      #   run: git fetch origin main:refs/remotes/origin/main --depth=1

      - name: Install jq
        uses: dcarbone/install-jq-action@v4

      - name: Get Toolchain Tags
        id: toolchain-tag
        run: |
          REPO_TAG=$(git show origin/main:common/lean-toolchain | cut -d':' -f2 | tr -d '\n')
          LEAN_TAG=$(curl -s "https://api.github.com/repos/leanprover/lean4/releases" | jq -r '.[0].tag_name' | tr -d '\n')
          echo "repo_tag=$REPO_TAG" >> $GITHUB_OUTPUT
          echo "lean_tag=$LEAN_TAG" >> $GITHUB_OUTPUT

      - name: Update Toolchain Files
        if: ${{ steps.toolchain-tag.outputs.lean_tag != steps.toolchain-tag.outputs.repo_tag }}
        run: just set-toolchain "${{ steps.toolchain-tag.outputs.lean_tag }}"

      - name: Create Pull Request
        if: ${{ steps.toolchain-tag.outputs.lean_tag != steps.toolchain-tag.outputs.repo_tag }}
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.UNICODE_BASIC_TOKEN }}
          commit-message: "chore: update toolchain ${{ steps.toolchain-tag.outputs.lean_tag }}"
          branch: update-toolchain-${{ steps.toolchain-tag.outputs.lean_tag }}
          base: main
          delete-branch: true
          title: "chore: update toolchain ${{ steps.toolchain-tag.outputs.lean_tag }}"
